export const belt_level_options = {
  ["어둠의 허리띠"]: {
    0: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
    ],
    1: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
    ],
    2: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 25 },
      { stat_name: "마법공격력", stat_value: 25 },
      { stat_name: "대항력", stat_value: 7 },
    ],
    3: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 37 },
      { stat_name: "마법공격력", stat_value: 37 },
      { stat_name: "대항력", stat_value: 11 },
    ],
    4: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 50 },
      { stat_name: "마법공격력", stat_value: 50 },
      { stat_name: "대항력", stat_value: 14 },
    ],
    5: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 62 },
      { stat_name: "마법공격력", stat_value: 62 },
      { stat_name: "대항력", stat_value: 18 },
    ],
    6: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 75 },
      { stat_name: "마법공격력", stat_value: 75 },
      { stat_name: "대항력", stat_value: 21 },
    ],
    7: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 87 },
      { stat_name: "마법공격력", stat_value: 87 },
      { stat_name: "대항력", stat_value: 25 },
    ],
    8: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 100 },
      { stat_name: "마법공격력", stat_value: 100 },
      { stat_name: "대항력", stat_value: 28 },
    ],
    9: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 112 },
      { stat_name: "마법공격력", stat_value: 112 },
      { stat_name: "대항력", stat_value: 32 },
    ],
    10: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 125 },
      { stat_name: "마법공격력", stat_value: 125 },
      { stat_name: "대항력", stat_value: 35 },
    ],
    11: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 137 },
      { stat_name: "마법공격력", stat_value: 137 },
      { stat_name: "대항력", stat_value: 39 },
    ],
    12: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 150 },
      { stat_name: "마법공격력", stat_value: 150 },
      { stat_name: "대항력", stat_value: 42 },
    ],
    13: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 162 },
      { stat_name: "마법공격력", stat_value: 162 },
      { stat_name: "대항력", stat_value: 46 },
    ],
    14: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 175 },
      { stat_name: "마법공격력", stat_value: 175 },
      { stat_name: "대항력", stat_value: 49 },
    ],
    15: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 187 },
      { stat_name: "마법공격력", stat_value: 187 },
      { stat_name: "대항력", stat_value: 53 },
    ],
    16: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 200 },
      { stat_name: "마법공격력", stat_value: 200 },
      { stat_name: "대항력", stat_value: 56 },
    ],
    17: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 212 },
      { stat_name: "마법공격력", stat_value: 212 },
      { stat_name: "대항력", stat_value: 60 },
    ],
    18: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 225 },
      { stat_name: "마법공격력", stat_value: 225 },
      { stat_name: "대항력", stat_value: 63 },
    ],
    19: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 237 },
      { stat_name: "마법공격력", stat_value: 237 },
      { stat_name: "대항력", stat_value: 67 },
    ],
    20: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 250 },
      { stat_name: "마법공격력", stat_value: 250 },
      { stat_name: "대항력", stat_value: 70 },
    ],
  },
  ["투쟁의 허리띠"]: {
    0: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
    ],
    1: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
    ],
    2: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 25 },
      { stat_name: "마법공격력", stat_value: 25 },
      { stat_name: "대항력", stat_value: 7 },
    ],
    3: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 37 },
      { stat_name: "마법공격력", stat_value: 37 },
      { stat_name: "대항력", stat_value: 11 },
    ],
    4: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 50 },
      { stat_name: "마법공격력", stat_value: 50 },
      { stat_name: "대항력", stat_value: 14 },
    ],
    5: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 62 },
      { stat_name: "마법공격력", stat_value: 62 },
      { stat_name: "대항력", stat_value: 18 },
    ],
    6: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 75 },
      { stat_name: "마법공격력", stat_value: 75 },
      { stat_name: "대항력", stat_value: 21 },
    ],
    7: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 87 },
      { stat_name: "마법공격력", stat_value: 87 },
      { stat_name: "대항력", stat_value: 25 },
    ],
    8: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 100 },
      { stat_name: "마법공격력", stat_value: 100 },
      { stat_name: "대항력", stat_value: 28 },
    ],
    9: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 112 },
      { stat_name: "마법공격력", stat_value: 112 },
      { stat_name: "대항력", stat_value: 32 },
    ],
    10: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 125 },
      { stat_name: "마법공격력", stat_value: 125 },
      { stat_name: "대항력", stat_value: 35 },
    ],
    11: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 137 },
      { stat_name: "마법공격력", stat_value: 137 },
      { stat_name: "대항력", stat_value: 39 },
    ],
    12: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 150 },
      { stat_name: "마법공격력", stat_value: 150 },
      { stat_name: "대항력", stat_value: 42 },
    ],
    13: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 162 },
      { stat_name: "마법공격력", stat_value: 162 },
      { stat_name: "대항력", stat_value: 46 },
    ],
    14: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 175 },
      { stat_name: "마법공격력", stat_value: 175 },
      { stat_name: "대항력", stat_value: 49 },
    ],
    15: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 187 },
      { stat_name: "마법공격력", stat_value: 187 },
      { stat_name: "대항력", stat_value: 53 },
    ],
    16: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 200 },
      { stat_name: "마법공격력", stat_value: 200 },
      { stat_name: "대항력", stat_value: 56 },
    ],
    17: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 212 },
      { stat_name: "마법공격력", stat_value: 212 },
      { stat_name: "대항력", stat_value: 60 },
    ],
    18: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 225 },
      { stat_name: "마법공격력", stat_value: 225 },
      { stat_name: "대항력", stat_value: 63 },
    ],
    19: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 237 },
      { stat_name: "마법공격력", stat_value: 237 },
      { stat_name: "대항력", stat_value: 67 },
    ],
    20: [
      { stat_name: "밸런스", stat_value: 6 },
      { stat_name: "힘", stat_value: 145 },
      { stat_name: "민첩", stat_value: 95 },
      { stat_name: "지능", stat_value: 193 },
      { stat_name: "의지", stat_value: 105 },
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "공격력", stat_value: 250 },
      { stat_name: "마법공격력", stat_value: 250 },
      { stat_name: "대항력", stat_value: 70 },
    ],
  },
};
