export const earring_level_options = {
  ["태양의 비원"]: {
    0: [
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    1: [
      { stat_name: "공격력", stat_value: 15 },
      { stat_name: "마법공격력", stat_value: 15 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 6 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    2: [
      { stat_name: "공격력", stat_value: 30 },
      { stat_name: "마법공격력", stat_value: 30 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 11 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    3: [
      { stat_name: "공격력", stat_value: 45 },
      { stat_name: "마법공격력", stat_value: 45 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 17 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    4: [
      { stat_name: "공격력", stat_value: 60 },
      { stat_name: "마법공격력", stat_value: 60 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 22 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    5: [
      { stat_name: "공격력", stat_value: 75 },
      { stat_name: "마법공격력", stat_value: 75 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 28 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    6: [
      { stat_name: "공격력", stat_value: 90 },
      { stat_name: "마법공격력", stat_value: 90 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 33 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    7: [
      { stat_name: "공격력", stat_value: 105 },
      { stat_name: "마법공격력", stat_value: 105 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 39 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    8: [
      { stat_name: "공격력", stat_value: 120 },
      { stat_name: "마법공격력", stat_value: 120 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 44 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    9: [
      { stat_name: "공격력", stat_value: 135 },
      { stat_name: "마법공격력", stat_value: 135 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 50 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    10: [
      { stat_name: "공격력", stat_value: 150 },
      { stat_name: "마법공격력", stat_value: 150 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 55 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    11: [
      { stat_name: "공격력", stat_value: 165 },
      { stat_name: "마법공격력", stat_value: 165 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 61 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    12: [
      { stat_name: "공격력", stat_value: 180 },
      { stat_name: "마법공격력", stat_value: 180 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 66 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    13: [
      { stat_name: "공격력", stat_value: 195 },
      { stat_name: "마법공격력", stat_value: 195 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 72 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    14: [
      { stat_name: "공격력", stat_value: 210 },
      { stat_name: "마법공격력", stat_value: 210 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 77 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    15: [
      { stat_name: "공격력", stat_value: 225 },
      { stat_name: "마법공격력", stat_value: 225 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 83 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    16: [
      { stat_name: "공격력", stat_value: 240 },
      { stat_name: "마법공격력", stat_value: 240 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 88 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    17: [
      { stat_name: "공격력", stat_value: 255 },
      { stat_name: "마법공격력", stat_value: 255 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 94 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    18: [
      { stat_name: "공격력", stat_value: 270 },
      { stat_name: "마법공격력", stat_value: 270 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 99 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    19: [
      { stat_name: "공격력", stat_value: 285 },
      { stat_name: "마법공격력", stat_value: 285 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 105 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    20: [
      { stat_name: "공격력", stat_value: 300 },
      { stat_name: "마법공격력", stat_value: 300 },
      { stat_name: "크리티컬", stat_value: 11 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 110 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
  },
  ["성소의 귀걸이"]: {
    0: [
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    1: [
      { stat_name: "공격력", stat_value: 14 },
      { stat_name: "마법공격력", stat_value: 14 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    2: [
      { stat_name: "공격력", stat_value: 28 },
      { stat_name: "마법공격력", stat_value: 28 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 8 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    3: [
      { stat_name: "공격력", stat_value: 42 },
      { stat_name: "마법공격력", stat_value: 42 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 13 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    4: [
      { stat_name: "공격력", stat_value: 56 },
      { stat_name: "마법공격력", stat_value: 56 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 18 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    5: [
      { stat_name: "공격력", stat_value: 70 },
      { stat_name: "마법공격력", stat_value: 70 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 22 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    6: [
      { stat_name: "공격력", stat_value: 84 },
      { stat_name: "마법공격력", stat_value: 84 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 27 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    7: [
      { stat_name: "공격력", stat_value: 98 },
      { stat_name: "마법공격력", stat_value: 98 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 31 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    8: [
      { stat_name: "공격력", stat_value: 112 },
      { stat_name: "마법공격력", stat_value: 112 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 36 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    9: [
      { stat_name: "공격력", stat_value: 126 },
      { stat_name: "마법공격력", stat_value: 126 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 40 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    10: [
      { stat_name: "공격력", stat_value: 140 },
      { stat_name: "마법공격력", stat_value: 140 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 45 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    11: [
      { stat_name: "공격력", stat_value: 154 },
      { stat_name: "마법공격력", stat_value: 154 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 49 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    12: [
      { stat_name: "공격력", stat_value: 168 },
      { stat_name: "마법공격력", stat_value: 168 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 54 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    13: [
      { stat_name: "공격력", stat_value: 182 },
      { stat_name: "마법공격력", stat_value: 182 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 58 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    14: [
      { stat_name: "공격력", stat_value: 196 },
      { stat_name: "마법공격력", stat_value: 196 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 63 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    15: [
      { stat_name: "공격력", stat_value: 210 },
      { stat_name: "마법공격력", stat_value: 210 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 67 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    16: [
      { stat_name: "공격력", stat_value: 224 },
      { stat_name: "마법공격력", stat_value: 224 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 72 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    17: [
      { stat_name: "공격력", stat_value: 238 },
      { stat_name: "마법공격력", stat_value: 238 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 76 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    18: [
      { stat_name: "공격력", stat_value: 252 },
      { stat_name: "마법공격력", stat_value: 252 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 81 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    19: [
      { stat_name: "공격력", stat_value: 266 },
      { stat_name: "마법공격력", stat_value: 266 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 85 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    20: [
      { stat_name: "공격력", stat_value: 280 },
      { stat_name: "마법공격력", stat_value: 280 },
      { stat_name: "크리티컬", stat_value: 7 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 90 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
  },
  ["차원의 귀걸이"]: {
    0: [
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    1: [
      { stat_name: "공격력", stat_value: 12 },
      { stat_name: "마법공격력", stat_value: 12 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 4 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    2: [
      { stat_name: "공격력", stat_value: 25 },
      { stat_name: "마법공격력", stat_value: 25 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 7 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    3: [
      { stat_name: "공격력", stat_value: 37 },
      { stat_name: "마법공격력", stat_value: 37 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 11 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    4: [
      { stat_name: "공격력", stat_value: 50 },
      { stat_name: "마법공격력", stat_value: 50 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 14 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    5: [
      { stat_name: "공격력", stat_value: 62 },
      { stat_name: "마법공격력", stat_value: 62 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 18 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    6: [
      { stat_name: "공격력", stat_value: 75 },
      { stat_name: "마법공격력", stat_value: 75 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 21 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    7: [
      { stat_name: "공격력", stat_value: 87 },
      { stat_name: "마법공격력", stat_value: 87 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 25 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    8: [
      { stat_name: "공격력", stat_value: 100 },
      { stat_name: "마법공격력", stat_value: 100 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 28 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    9: [
      { stat_name: "공격력", stat_value: 112 },
      { stat_name: "마법공격력", stat_value: 112 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 32 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    10: [
      { stat_name: "공격력", stat_value: 125 },
      { stat_name: "마법공격력", stat_value: 125 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 35 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    11: [
      { stat_name: "공격력", stat_value: 137 },
      { stat_name: "마법공격력", stat_value: 137 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 39 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    12: [
      { stat_name: "공격력", stat_value: 150 },
      { stat_name: "마법공격력", stat_value: 150 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 42 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    13: [
      { stat_name: "공격력", stat_value: 162 },
      { stat_name: "마법공격력", stat_value: 162 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 46 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    14: [
      { stat_name: "공격력", stat_value: 175 },
      { stat_name: "마법공격력", stat_value: 175 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 49 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    15: [
      { stat_name: "공격력", stat_value: 187 },
      { stat_name: "마법공격력", stat_value: 187 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 53 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    16: [
      { stat_name: "공격력", stat_value: 200 },
      { stat_name: "마법공격력", stat_value: 200 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 56 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    17: [
      { stat_name: "공격력", stat_value: 212 },
      { stat_name: "마법공격력", stat_value: 212 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 60 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    18: [
      { stat_name: "공격력", stat_value: 225 },
      { stat_name: "마법공격력", stat_value: 225 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 63 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    19: [
      { stat_name: "공격력", stat_value: 237 },
      { stat_name: "마법공격력", stat_value: 237 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 67 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
    20: [
      { stat_name: "공격력", stat_value: 250 },
      { stat_name: "마법공격력", stat_value: 250 },
      { stat_name: "크리티컬", stat_value: 5 },
      { stat_name: "힘", stat_value: 125 },
      { stat_name: "민첩", stat_value: 50 },
      { stat_name: "지능", stat_value: 167 },
      { stat_name: "의지", stat_value: 58 },
      { stat_name: "대항력", stat_value: 70 },
      { stat_name: "스태미나", stat_value: 4 },
    ],
  },
};
