export const hand_level_options = {
  ['아르드리']: {
    0: [
      { stat_name: '방어력', stat_value: 3475 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 10 },
      { stat_name: '방어력', stat_value: 3488 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 22 },
      { stat_name: '방어력', stat_value: 3501 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 34 },
      { stat_name: '방어력', stat_value: 3514 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 46 },
      { stat_name: '방어력', stat_value: 3532 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 58 },
      { stat_name: '방어력', stat_value: 3550 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    6: [
      { stat_name: '추가피해', stat_value: 70 },
      { stat_name: '방어력', stat_value: 3568 },
      { stat_name: '파괴시 방어력', stat_value: 1320 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 50 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    7: [
      { stat_name: '추가피해', stat_value: 82 },
      { stat_name: '방어력', stat_value: 3592 },
      { stat_name: '파괴시 방어력', stat_value: 1459 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 70 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    8: [
      { stat_name: '추가피해', stat_value: 97 },
      { stat_name: '방어력', stat_value: 3616 },
      { stat_name: '파괴시 방어력', stat_value: 1598 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 100 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    9: [
      { stat_name: '추가피해', stat_value: 112 },
      { stat_name: '방어력', stat_value: 3640 },
      { stat_name: '파괴시 방어력', stat_value: 1737 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 130 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    10: [
      { stat_name: '추가피해', stat_value: 130 },
      { stat_name: '방어력', stat_value: 3664 },
      { stat_name: '파괴시 방어력', stat_value: 1876 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 170 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    11: [
      { stat_name: '추가피해', stat_value: 240 },
      { stat_name: '방어력', stat_value: 3699 },
      { stat_name: '파괴시 방어력', stat_value: 2015 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 220 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    12: [
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '방어력', stat_value: 3734 },
      { stat_name: '파괴시 방어력', stat_value: 2154 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 300 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    13: [
      { stat_name: '추가피해', stat_value: 460 },
      { stat_name: '방어력', stat_value: 3769 },
      { stat_name: '파괴시 방어력', stat_value: 2432 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    14: [
      { stat_name: '추가피해', stat_value: 570 },
      { stat_name: '방어력', stat_value: 3814 },
      { stat_name: '파괴시 방어력', stat_value: 2780 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
    15: [
      { stat_name: '추가피해', stat_value: 680 },
      { stat_name: '방어력', stat_value: 3859 },
      { stat_name: '파괴시 방어력', stat_value: 3127 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 27 },
    ],
  },
  ['오르나']: {
    0: [
      { stat_name: '방어력', stat_value: 3449 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 50 },
      { stat_name: '방어력', stat_value: 3474 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 100 },
      { stat_name: '방어력', stat_value: 3499 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 150 },
      { stat_name: '방어력', stat_value: 3524 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 200 },
      { stat_name: '방어력', stat_value: 3549 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 250 },
      { stat_name: '방어력', stat_value: 3574 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    6: [
      { stat_name: '추가피해', stat_value: 300 },
      { stat_name: '방어력', stat_value: 3599 },
      { stat_name: '파괴시 방어력', stat_value: 1310 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 50 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    7: [
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '방어력', stat_value: 3624 },
      { stat_name: '파괴시 방어력', stat_value: 1448 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 70 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    8: [
      { stat_name: '추가피해', stat_value: 400 },
      { stat_name: '방어력', stat_value: 3649 },
      { stat_name: '파괴시 방어력', stat_value: 1586 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 100 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    9: [
      { stat_name: '추가피해', stat_value: 450 },
      { stat_name: '방어력', stat_value: 3674 },
      { stat_name: '파괴시 방어력', stat_value: 1724 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 130 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    10: [
      { stat_name: '추가피해', stat_value: 500 },
      { stat_name: '방어력', stat_value: 3699 },
      { stat_name: '파괴시 방어력', stat_value: 1862 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 170 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    11: [
      { stat_name: '추가피해', stat_value: 550 },
      { stat_name: '방어력', stat_value: 3724 },
      { stat_name: '파괴시 방어력', stat_value: 2000 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 220 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    12: [
      { stat_name: '추가피해', stat_value: 600 },
      { stat_name: '방어력', stat_value: 3749 },
      { stat_name: '파괴시 방어력', stat_value: 2138 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 300 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    13: [
      { stat_name: '추가피해', stat_value: 650 },
      { stat_name: '방어력', stat_value: 3774 },
      { stat_name: '파괴시 방어력', stat_value: 2414 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    14: [
      { stat_name: '추가피해', stat_value: 700 },
      { stat_name: '방어력', stat_value: 3799 },
      { stat_name: '파괴시 방어력', stat_value: 2759 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
    15: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 3833 },
      { stat_name: '파괴시 방어력', stat_value: 3104 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 23 },
    ],
  },
  ['15오르나']: {
    15: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 4085 },
      // { stat_name: '파괴시 방어력', stat_value: 3558 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 26 },
    ],
  },
  ['와드네']: {
    0: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 4338 },
      // { stat_name: '파괴시 방어력', stat_value: 3904 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 780 },
      { stat_name: '방어력', stat_value: 4448 },
      // { stat_name: '파괴시 방어력', stat_value: 4003 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 810 },
      { stat_name: '방어력', stat_value: 4558 },
      // { stat_name: '파괴시 방어력', stat_value: 4102 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 840 },
      { stat_name: '방어력', stat_value: 4668 },
      // { stat_name: '파괴시 방어력', stat_value: 4201 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 870 },
      { stat_name: '방어력', stat_value: 4778 },
      // { stat_name: '파괴시 방어력', stat_value: 4300 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 900 },
      { stat_name: '방어력', stat_value: 4888 },
      // { stat_name: '파괴시 방어력', stat_value: 4399 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
  },
};
