export const lower_level_options = {
  ['아르드리']: {
    0: [
      { stat_name: '방어력', stat_value: 3342 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 10 },
      { stat_name: '방어력', stat_value: 3355 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 22 },
      { stat_name: '방어력', stat_value: 3368 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 34 },
      { stat_name: '방어력', stat_value: 3381 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 46 },
      { stat_name: '방어력', stat_value: 3399 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 58 },
      { stat_name: '방어력', stat_value: 3417 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    6: [
      { stat_name: '추가피해', stat_value: 70 },
      { stat_name: '방어력', stat_value: 3435 },
      { stat_name: '파괴시 방어력', stat_value: 1269 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 50 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    7: [
      { stat_name: '추가피해', stat_value: 82 },
      { stat_name: '방어력', stat_value: 3459 },
      { stat_name: '파괴시 방어력', stat_value: 1403 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 70 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    8: [
      { stat_name: '추가피해', stat_value: 97 },
      { stat_name: '방어력', stat_value: 3483 },
      { stat_name: '파괴시 방어력', stat_value: 1537 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 100 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    9: [
      { stat_name: '추가피해', stat_value: 112 },
      { stat_name: '방어력', stat_value: 3507 },
      { stat_name: '파괴시 방어력', stat_value: 1671 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 130 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    10: [
      { stat_name: '추가피해', stat_value: 130 },
      { stat_name: '방어력', stat_value: 3531 },
      { stat_name: '파괴시 방어력', stat_value: 1804 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 170 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    11: [
      { stat_name: '추가피해', stat_value: 240 },
      { stat_name: '방어력', stat_value: 3566 },
      { stat_name: '파괴시 방어력', stat_value: 1938 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 220 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    12: [
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '방어력', stat_value: 3601 },
      { stat_name: '파괴시 방어력', stat_value: 2072 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 300 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    13: [
      { stat_name: '추가피해', stat_value: 460 },
      { stat_name: '방어력', stat_value: 3636 },
      { stat_name: '파괴시 방어력', stat_value: 2339 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    14: [
      { stat_name: '추가피해', stat_value: 570 },
      { stat_name: '방어력', stat_value: 3681 },
      { stat_name: '파괴시 방어력', stat_value: 2673 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
    15: [
      { stat_name: '추가피해', stat_value: 680 },
      { stat_name: '방어력', stat_value: 3726 },
      { stat_name: '파괴시 방어력', stat_value: 3007 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 40 },
    ],
  },
  ['오르나']: {
    0: [
      { stat_name: '방어력', stat_value: 3442 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 50 },
      { stat_name: '방어력', stat_value: 3467 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 100 },
      { stat_name: '방어력', stat_value: 3492 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 150 },
      { stat_name: '방어력', stat_value: 3517 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 200 },
      { stat_name: '방어력', stat_value: 3542 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 250 },
      { stat_name: '방어력', stat_value: 3567 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    6: [
      { stat_name: '추가피해', stat_value: 300 },
      { stat_name: '방어력', stat_value: 3592 },
      { stat_name: '파괴시 방어력', stat_value: 1307 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 50 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    7: [
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '방어력', stat_value: 3617 },
      { stat_name: '파괴시 방어력', stat_value: 1445 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 70 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    8: [
      { stat_name: '추가피해', stat_value: 400 },
      { stat_name: '방어력', stat_value: 3642 },
      { stat_name: '파괴시 방어력', stat_value: 1583 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 100 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    9: [
      { stat_name: '추가피해', stat_value: 450 },
      { stat_name: '방어력', stat_value: 3667 },
      { stat_name: '파괴시 방어력', stat_value: 1721 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 130 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    10: [
      { stat_name: '추가피해', stat_value: 500 },
      { stat_name: '방어력', stat_value: 3692 },
      { stat_name: '파괴시 방어력', stat_value: 1858 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 170 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    11: [
      { stat_name: '추가피해', stat_value: 550 },
      { stat_name: '방어력', stat_value: 3717 },
      { stat_name: '파괴시 방어력', stat_value: 1996 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 220 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    12: [
      { stat_name: '추가피해', stat_value: 600 },
      { stat_name: '방어력', stat_value: 3742 },
      { stat_name: '파괴시 방어력', stat_value: 2134 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 300 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    13: [
      { stat_name: '추가피해', stat_value: 650 },
      { stat_name: '방어력', stat_value: 3767 },
      { stat_name: '파괴시 방어력', stat_value: 2409 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    14: [
      { stat_name: '추가피해', stat_value: 700 },
      { stat_name: '방어력', stat_value: 3792 },
      { stat_name: '파괴시 방어력', stat_value: 2753 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
    15: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 3826 },
      { stat_name: '파괴시 방어력', stat_value: 3097 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
  },
  ['15오르나']: {
    15: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 3826 },
      { stat_name: '파괴시 방어력', stat_value: 3518 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 33 },
    ],
  },
  ['와드네']: {
    0: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 4293 },
      { stat_name: '파괴시 방어력', stat_value: 3863 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 52 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 780 },
      { stat_name: '방어력', stat_value: 4403 },
      { stat_name: '파괴시 방어력', stat_value: 3962 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 52 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 810 },
      { stat_name: '방어력', stat_value: 4513 },
      { stat_name: '파괴시 방어력', stat_value: 4061 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 52 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 840 },
      { stat_name: '방어력', stat_value: 4623 },
      { stat_name: '파괴시 방어력', stat_value: 4160 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 52 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 870 },
      { stat_name: '방어력', stat_value: 4733 },
      { stat_name: '파괴시 방어력', stat_value: 4259 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 52 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 900 },
      { stat_name: '방어력', stat_value: 4843 },
      { stat_name: '파괴시 방어력', stat_value: 4358 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 52 },
    ],
  },
};

// export const lower_level_options = {
//   아르드리: {
//     0: [
//       { stat_name: "방어력", stat_value: 3342 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     1: [
//       { stat_name: "추가피해", stat_value: 10 },
//       { stat_name: "방어력", stat_value: 3355 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     2: [
//       { stat_name: "추가피해", stat_value: 22 },
//       { stat_name: "방어력", stat_value: 3368 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     3: [
//       { stat_name: "추가피해", stat_value: 34 },
//       { stat_name: "방어력", stat_value: 3381 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     4: [
//       { stat_name: "추가피해", stat_value: 46 },
//       { stat_name: "방어력", stat_value: 3399 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     5: [
//       { stat_name: "추가피해", stat_value: 58 },
//       { stat_name: "방어력", stat_value: 3417 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     6: [
//       { stat_name: "추가피해", stat_value: 70 },
//       { stat_name: "방어력", stat_value: 3435 },
//       { stat_name: "파괴시 방어력", stat_value: 1269 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 50 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     7: [
//       { stat_name: "추가피해", stat_value: 82 },
//       { stat_name: "방어력", stat_value: 3459 },
//       { stat_name: "파괴시 방어력", stat_value: 1403 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 70 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     8: [
//       { stat_name: "추가피해", stat_value: 97 },
//       { stat_name: "방어력", stat_value: 3483 },
//       { stat_name: "파괴시 방어력", stat_value: 1537 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 100 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     9: [
//       { stat_name: "추가피해", stat_value: 112 },
//       { stat_name: "방어력", stat_value: 3507 },
//       { stat_name: "파괴시 방어력", stat_value: 1671 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 130 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     10: [
//       { stat_name: "추가피해", stat_value: 130 },
//       { stat_name: "방어력", stat_value: 3531 },
//       { stat_name: "파괴시 방어력", stat_value: 1804 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 170 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     11: [
//       { stat_name: "추가피해", stat_value: 240 },
//       { stat_name: "방어력", stat_value: 3566 },
//       { stat_name: "파괴시 방어력", stat_value: 1938 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 220 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     12: [
//       { stat_name: "추가피해", stat_value: 350 },
//       { stat_name: "방어력", stat_value: 3601 },
//       { stat_name: "파괴시 방어력", stat_value: 2072 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 300 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     13: [
//       { stat_name: "추가피해", stat_value: 460 },
//       { stat_name: "방어력", stat_value: 3636 },
//       { stat_name: "파괴시 방어력", stat_value: 2339 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     14: [
//       { stat_name: "추가피해", stat_value: 570 },
//       { stat_name: "방어력", stat_value: 3681 },
//       { stat_name: "파괴시 방어력", stat_value: 2673 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//     15: [
//       { stat_name: "추가피해", stat_value: 680 },
//       { stat_name: "방어력", stat_value: 3726 },
//       { stat_name: "파괴시 방어력", stat_value: 3007 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 40 },
//     ],
//   },
//   오르나: {
//     0: [
//       { stat_name: "방어력", stat_value: 3442 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     1: [
//       { stat_name: "추가피해", stat_value: 50 },
//       { stat_name: "방어력", stat_value: 3467 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     2: [
//       { stat_name: "추가피해", stat_value: 100 },
//       { stat_name: "방어력", stat_value: 3492 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     3: [
//       { stat_name: "추가피해", stat_value: 150 },
//       { stat_name: "방어력", stat_value: 3517 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     4: [
//       { stat_name: "추가피해", stat_value: 200 },
//       { stat_name: "방어력", stat_value: 3542 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     5: [
//       { stat_name: "추가피해", stat_value: 250 },
//       { stat_name: "방어력", stat_value: 3567 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     6: [
//       { stat_name: "추가피해", stat_value: 300 },
//       { stat_name: "방어력", stat_value: 3592 },
//       { stat_name: "파괴시 방어력", stat_value: 1307 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 50 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     7: [
//       { stat_name: "추가피해", stat_value: 350 },
//       { stat_name: "방어력", stat_value: 3617 },
//       { stat_name: "파괴시 방어력", stat_value: 1445 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 70 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     8: [
//       { stat_name: "추가피해", stat_value: 400 },
//       { stat_name: "방어력", stat_value: 3642 },
//       { stat_name: "파괴시 방어력", stat_value: 1583 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 100 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     9: [
//       { stat_name: "추가피해", stat_value: 450 },
//       { stat_name: "방어력", stat_value: 3667 },
//       { stat_name: "파괴시 방어력", stat_value: 1721 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 130 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     10: [
//       { stat_name: "추가피해", stat_value: 500 },
//       { stat_name: "방어력", stat_value: 3692 },
//       { stat_name: "파괴시 방어력", stat_value: 1858 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 170 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     11: [
//       { stat_name: "추가피해", stat_value: 550 },
//       { stat_name: "방어력", stat_value: 3717 },
//       { stat_name: "파괴시 방어력", stat_value: 1996 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 220 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     12: [
//       { stat_name: "추가피해", stat_value: 600 },
//       { stat_name: "방어력", stat_value: 3742 },
//       { stat_name: "파괴시 방어력", stat_value: 2134 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 300 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     13: [
//       { stat_name: "추가피해", stat_value: 650 },
//       { stat_name: "방어력", stat_value: 3767 },
//       { stat_name: "파괴시 방어력", stat_value: 2409 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     14: [
//       { stat_name: "추가피해", stat_value: 700 },
//       { stat_name: "방어력", stat_value: 3792 },
//       { stat_name: "파괴시 방어력", stat_value: 2753 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//     15: [
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "방어력", stat_value: 3826 },
//       { stat_name: "파괴시 방어력", stat_value: 3097 },
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 33 },
//     ],
//   },
//   와드네: {
//     ["와드네 그리브즈"]: [
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "방어력", stat_value: 4293 },
//       { stat_name: "파괴시 방어력", stat_value: 3863 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//     ["초급 와드네 그리브즈"]: [
//       { stat_name: "추가피해", stat_value: 780 },
//       { stat_name: "방어력", stat_value: 4403 },
//       { stat_name: "파괴시 방어력", stat_value: 3962 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//     ["중급 와드네 그리브즈"]: [
//       { stat_name: "추가피해", stat_value: 810 },
//       { stat_name: "방어력", stat_value: 4513 },
//       { stat_name: "파괴시 방어력", stat_value: 4061 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//     ["고급 와드네 그리브즈"]: [
//       { stat_name: "추가피해", stat_value: 840 },
//       { stat_name: "방어력", stat_value: 4623 },
//       { stat_name: "파괴시 방어력", stat_value: 4160 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//     ["레어 와드네 그리브즈"]: [
//       { stat_name: "추가피해", stat_value: 870 },
//       { stat_name: "방어력", stat_value: 4733 },
//       { stat_name: "파괴시 방어력", stat_value: 4259 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//     ["전설 와드네 그리브즈"]: [
//       { stat_name: "추가피해", stat_value: 900 },
//       { stat_name: "방어력", stat_value: 4843 },
//       { stat_name: "파괴시 방어력", stat_value: 4358 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//   },
// };
