export const right_hand_level_options = {
  ['아르드리']: {
    0: [
      { stat_name: '공격력', stat_value: 26800 },
      { stat_name: '마법공격력', stat_value: 26800 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 9 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    1: [
      { stat_name: '공격력', stat_value: 26850 },
      { stat_name: '마법공격력', stat_value: 26850 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 11 },
      { stat_name: '추가피해', stat_value: 200 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    2: [
      { stat_name: '공격력', stat_value: 26900 },
      { stat_name: '마법공격력', stat_value: 26900 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 13 },
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    3: [
      { stat_name: '공격력', stat_value: 26950 },
      { stat_name: '마법공격력', stat_value: 26950 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 15 },
      { stat_name: '추가피해', stat_value: 500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    4: [
      { stat_name: '공격력', stat_value: 27050 },
      { stat_name: '마법공격력', stat_value: 27050 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 17 },
      { stat_name: '추가피해', stat_value: 650 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    5: [
      { stat_name: '공격력', stat_value: 27150 },
      { stat_name: '마법공격력', stat_value: 27150 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 19 },
      { stat_name: '추가피해', stat_value: 800 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    6: [
      { stat_name: '공격력', stat_value: 27250 },
      { stat_name: '마법공격력', stat_value: 27250 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 21 },
      { stat_name: '추가피해', stat_value: 1000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    7: [
      { stat_name: '공격력', stat_value: 27350 },
      { stat_name: '마법공격력', stat_value: 27350 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 23 },
      { stat_name: '추가피해', stat_value: 1200 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    8: [
      { stat_name: '공격력', stat_value: 27500 },
      { stat_name: '마법공격력', stat_value: 27500 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 25 },
      { stat_name: '추가피해', stat_value: 1450 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    9: [
      { stat_name: '공격력', stat_value: 27650 },
      { stat_name: '마법공격력', stat_value: 27650 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 27 },
      { stat_name: '추가피해', stat_value: 1700 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    10: [
      { stat_name: '공격력', stat_value: 27800 },
      { stat_name: '마법공격력', stat_value: 27800 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 29 },
      { stat_name: '추가피해', stat_value: 1950 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    11: [
      { stat_name: '공격력', stat_value: 28300 },
      { stat_name: '마법공격력', stat_value: 28300 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 33 },
      { stat_name: '추가피해', stat_value: 2280 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    12: [
      { stat_name: '공격력', stat_value: 28800 },
      { stat_name: '마법공격력', stat_value: 28800 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 37 },
      { stat_name: '추가피해', stat_value: 2610 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    13: [
      { stat_name: '공격력', stat_value: 29400 },
      { stat_name: '마법공격력', stat_value: 29400 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 42 },
      { stat_name: '추가피해', stat_value: 2940 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    14: [
      { stat_name: '공격력', stat_value: 30100 },
      { stat_name: '마법공격력', stat_value: 30100 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 45 },
      { stat_name: '추가피해', stat_value: 3270 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    15: [
      { stat_name: '공격력', stat_value: 30900 },
      { stat_name: '마법공격력', stat_value: 30900 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3600 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
  ['오르나']: {
    0: [
      { stat_name: '공격력', stat_value: 28644 },
      { stat_name: '마법공격력', stat_value: 28644 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 7 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    1: [
      { stat_name: '공격력', stat_value: 28914 },
      { stat_name: '마법공격력', stat_value: 28914 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 10 },
      { stat_name: '추가피해', stat_value: 250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    2: [
      { stat_name: '공격력', stat_value: 29184 },
      { stat_name: '마법공격력', stat_value: 29184 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 13 },
      { stat_name: '추가피해', stat_value: 500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    3: [
      { stat_name: '공격력', stat_value: 29454 },
      { stat_name: '마법공격력', stat_value: 29454 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 16 },
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    4: [
      { stat_name: '공격력', stat_value: 29724 },
      { stat_name: '마법공격력', stat_value: 29724 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 19 },
      { stat_name: '추가피해', stat_value: 1000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    5: [
      { stat_name: '공격력', stat_value: 29994 },
      { stat_name: '마법공격력', stat_value: 29994 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 22 },
      { stat_name: '추가피해', stat_value: 1250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    6: [
      { stat_name: '공격력', stat_value: 30264 },
      { stat_name: '마법공격력', stat_value: 30264 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 25 },
      { stat_name: '추가피해', stat_value: 1500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    7: [
      { stat_name: '공격력', stat_value: 30534 },
      { stat_name: '마법공격력', stat_value: 30534 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 28 },
      { stat_name: '추가피해', stat_value: 1750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    8: [
      { stat_name: '공격력', stat_value: 30804 },
      { stat_name: '마법공격력', stat_value: 30804 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 31 },
      { stat_name: '추가피해', stat_value: 2000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    9: [
      { stat_name: '공격력', stat_value: 31074 },
      { stat_name: '마법공격력', stat_value: 31074 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 33 },
      { stat_name: '추가피해', stat_value: 2250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    10: [
      { stat_name: '공격력', stat_value: 31344 },
      { stat_name: '마법공격력', stat_value: 31344 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 35 },
      { stat_name: '추가피해', stat_value: 2500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    11: [
      { stat_name: '공격력', stat_value: 31614 },
      { stat_name: '마법공격력', stat_value: 31614 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 37 },
      { stat_name: '추가피해', stat_value: 2750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    12: [
      { stat_name: '공격력', stat_value: 31884 },
      { stat_name: '마법공격력', stat_value: 31884 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 39 },
      { stat_name: '추가피해', stat_value: 3000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    13: [
      { stat_name: '공격력', stat_value: 32154 },
      { stat_name: '마법공격력', stat_value: 32154 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 41 },
      { stat_name: '추가피해', stat_value: 3250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    14: [
      { stat_name: '공격력', stat_value: 32424 },
      { stat_name: '마법공격력', stat_value: 32424 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 43 },
      { stat_name: '추가피해', stat_value: 3500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    15: [
      { stat_name: '공격력', stat_value: 32744 },
      { stat_name: '마법공격력', stat_value: 32744 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 45 },
      { stat_name: '추가피해', stat_value: 3750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
  ['15오르나']: {
    15: [
      { stat_name: '공격력', stat_value: 32744 },
      { stat_name: '마법공격력', stat_value: 34900 },
      { stat_name: '밸런스', stat_value: 52 },
      { stat_name: '크리티컬', stat_value: 105 },
      { stat_name: '공격속도', stat_value: 45 },
      { stat_name: '추가피해', stat_value: 3750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
  ['와드네']: {
    0: [
      { stat_name: '공격력', stat_value: 34900 },
      { stat_name: '마법공격력', stat_value: 34900 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    1: [
      { stat_name: '공격력', stat_value: 35400 },
      { stat_name: '마법공격력', stat_value: 35400 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3850 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    2: [
      { stat_name: '공격력', stat_value: 35900 },
      { stat_name: '마법공격력', stat_value: 35900 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3950 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    3: [
      { stat_name: '공격력', stat_value: 36400 },
      { stat_name: '마법공격력', stat_value: 36400 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4050 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    4: [
      { stat_name: '공격력', stat_value: 36900 },
      { stat_name: '마법공격력', stat_value: 36900 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4150 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    5: [
      { stat_name: '공격력', stat_value: 37400 },
      { stat_name: '마법공격력', stat_value: 37400 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
};
