export const right_hand_level_options = {
  ['아르드리']: {
    0: [
      { stat_name: '공격력', stat_value: 26800 },
      { stat_name: '마법공격력', stat_value: 26800 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 9 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    1: [
      { stat_name: '공격력', stat_value: 26850 },
      { stat_name: '마법공격력', stat_value: 26850 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 11 },
      { stat_name: '추가피해', stat_value: 200 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    2: [
      { stat_name: '공격력', stat_value: 26900 },
      { stat_name: '마법공격력', stat_value: 26900 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 13 },
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    3: [
      { stat_name: '공격력', stat_value: 26950 },
      { stat_name: '마법공격력', stat_value: 26950 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 15 },
      { stat_name: '추가피해', stat_value: 500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    4: [
      { stat_name: '공격력', stat_value: 27050 },
      { stat_name: '마법공격력', stat_value: 27050 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 17 },
      { stat_name: '추가피해', stat_value: 650 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    5: [
      { stat_name: '공격력', stat_value: 27150 },
      { stat_name: '마법공격력', stat_value: 27150 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 19 },
      { stat_name: '추가피해', stat_value: 800 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    6: [
      { stat_name: '공격력', stat_value: 27250 },
      { stat_name: '마법공격력', stat_value: 27250 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 21 },
      { stat_name: '추가피해', stat_value: 1000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    7: [
      { stat_name: '공격력', stat_value: 27350 },
      { stat_name: '마법공격력', stat_value: 27350 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 23 },
      { stat_name: '추가피해', stat_value: 1200 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    8: [
      { stat_name: '공격력', stat_value: 27500 },
      { stat_name: '마법공격력', stat_value: 27500 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 25 },
      { stat_name: '추가피해', stat_value: 1450 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    9: [
      { stat_name: '공격력', stat_value: 27650 },
      { stat_name: '마법공격력', stat_value: 27650 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 27 },
      { stat_name: '추가피해', stat_value: 1700 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    10: [
      { stat_name: '공격력', stat_value: 27800 },
      { stat_name: '마법공격력', stat_value: 27800 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 29 },
      { stat_name: '추가피해', stat_value: 1950 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    11: [
      { stat_name: '공격력', stat_value: 28300 },
      { stat_name: '마법공격력', stat_value: 28300 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 33 },
      { stat_name: '추가피해', stat_value: 2280 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    12: [
      { stat_name: '공격력', stat_value: 28800 },
      { stat_name: '마법공격력', stat_value: 28800 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 37 },
      { stat_name: '추가피해', stat_value: 2610 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    13: [
      { stat_name: '공격력', stat_value: 29400 },
      { stat_name: '마법공격력', stat_value: 29400 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 42 },
      { stat_name: '추가피해', stat_value: 2940 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    14: [
      { stat_name: '공격력', stat_value: 30100 },
      { stat_name: '마법공격력', stat_value: 30100 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 45 },
      { stat_name: '추가피해', stat_value: 3270 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    15: [
      { stat_name: '공격력', stat_value: 30900 },
      { stat_name: '마법공격력', stat_value: 30900 },
      { stat_name: '밸런스', stat_value: 51 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3600 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
  ['오르나']: {
    0: [
      { stat_name: '공격력', stat_value: 29722 },
      { stat_name: '마법공격력', stat_value: 29722 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 8 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    1: [
      { stat_name: '공격력', stat_value: 29992 },
      { stat_name: '마법공격력', stat_value: 29992 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 11 },
      { stat_name: '추가피해', stat_value: 250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    2: [
      { stat_name: '공격력', stat_value: 30262 },
      { stat_name: '마법공격력', stat_value: 30262 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 14 },
      { stat_name: '추가피해', stat_value: 500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    3: [
      { stat_name: '공격력', stat_value: 30532 },
      { stat_name: '마법공격력', stat_value: 30532 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 17 },
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    4: [
      { stat_name: '공격력', stat_value: 30802 },
      { stat_name: '마법공격력', stat_value: 30802 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 20 },
      { stat_name: '추가피해', stat_value: 1000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    5: [
      { stat_name: '공격력', stat_value: 31072 },
      { stat_name: '마법공격력', stat_value: 31072 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 23 },
      { stat_name: '추가피해', stat_value: 1250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    6: [
      { stat_name: '공격력', stat_value: 31342 },
      { stat_name: '마법공격력', stat_value: 31342 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 26 },
      { stat_name: '추가피해', stat_value: 1500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    7: [
      { stat_name: '공격력', stat_value: 31612 },
      { stat_name: '마법공격력', stat_value: 31612 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 29 },
      { stat_name: '추가피해', stat_value: 1750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    8: [
      { stat_name: '공격력', stat_value: 31882 },
      { stat_name: '마법공격력', stat_value: 31882 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 32 },
      { stat_name: '추가피해', stat_value: 2000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    9: [
      { stat_name: '공격력', stat_value: 32152 },
      { stat_name: '마법공격력', stat_value: 32152 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 34 },
      { stat_name: '추가피해', stat_value: 2250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    10: [
      { stat_name: '공격력', stat_value: 32422 },
      { stat_name: '마법공격력', stat_value: 32422 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 36 },
      { stat_name: '추가피해', stat_value: 2500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    11: [
      { stat_name: '공격력', stat_value: 32692 },
      { stat_name: '마법공격력', stat_value: 32692 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 38 },
      { stat_name: '추가피해', stat_value: 2750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    12: [
      { stat_name: '공격력', stat_value: 32962 },
      { stat_name: '마법공격력', stat_value: 32962 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 40 },
      { stat_name: '추가피해', stat_value: 3000 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    13: [
      { stat_name: '공격력', stat_value: 33232 },
      { stat_name: '마법공격력', stat_value: 33232 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 42 },
      { stat_name: '추가피해', stat_value: 3250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    14: [
      { stat_name: '공격력', stat_value: 33502 },
      { stat_name: '마법공격력', stat_value: 33502 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 44 },
      { stat_name: '추가피해', stat_value: 3500 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    15: [
      { stat_name: '공격력', stat_value: 33822 },
      { stat_name: '마법공격력', stat_value: 33822 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 46 },
      { stat_name: '추가피해', stat_value: 3750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
  ['15오르나']: {
    15: [
      { stat_name: '공격력', stat_value: 33822 },
      { stat_name: '마법공격력', stat_value: 34900 },
      { stat_name: '밸런스', stat_value: 55 },
      { stat_name: '크리티컬', stat_value: 112 },
      { stat_name: '공격속도', stat_value: 46 },
      { stat_name: '추가피해', stat_value: 3750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
  ['와드네']: {
    0: [
      { stat_name: '공격력', stat_value: 34900 },
      { stat_name: '마법공격력', stat_value: 34900 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3750 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    1: [
      { stat_name: '공격력', stat_value: 35400 },
      { stat_name: '마법공격력', stat_value: 35400 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3850 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    2: [
      { stat_name: '공격력', stat_value: 35900 },
      { stat_name: '마법공격력', stat_value: 35900 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 3950 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    3: [
      { stat_name: '공격력', stat_value: 36400 },
      { stat_name: '마법공격력', stat_value: 36400 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4050 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    4: [
      { stat_name: '공격력', stat_value: 36900 },
      { stat_name: '마법공격력', stat_value: 36900 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4150 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    5: [
      { stat_name: '공격력', stat_value: 37400 },
      { stat_name: '마법공격력', stat_value: 37400 },
      { stat_name: '밸런스', stat_value: 67 },
      { stat_name: '크리티컬', stat_value: 128 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
  ['에리우']: {
    0: [
      { stat_name: '공격력', stat_value: 37400 },
      { stat_name: '마법공격력', stat_value: 37400 },
      { stat_name: '밸런스', stat_value: 75 },
      { stat_name: '크리티컬', stat_value: 136 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4250 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    1: [
      { stat_name: '공격력', stat_value: 38650 },
      { stat_name: '마법공격력', stat_value: 38650 },
      { stat_name: '밸런스', stat_value: 75 },
      { stat_name: '크리티컬', stat_value: 137 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4400 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
    2: [
      { stat_name: '공격력', stat_value: 39900 },
      { stat_name: '마법공격력', stat_value: 39900 },
      { stat_name: '밸런스', stat_value: 77 },
      { stat_name: '크리티컬', stat_value: 138 },
      { stat_name: '공격속도', stat_value: 47 },
      { stat_name: '추가피해', stat_value: 4550 },
      { stat_name: '힘', stat_value: 110 },
      { stat_name: '민첩', stat_value: 60 },
      { stat_name: '지능', stat_value: 148 },
      { stat_name: '의지', stat_value: 80 },
    ],
  },
};
