export const upper_level_options = {
  ['아르드리']: {
    0: [
      { stat_name: '방어력', stat_value: 3528 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 10 },
      { stat_name: '방어력', stat_value: 3541 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 22 },
      { stat_name: '방어력', stat_value: 3554 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 34 },
      { stat_name: '방어력', stat_value: 3567 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 46 },
      { stat_name: '방어력', stat_value: 3585 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 58 },
      { stat_name: '방어력', stat_value: 3603 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    6: [
      { stat_name: '추가피해', stat_value: 70 },
      { stat_name: '방어력', stat_value: 3621 },
      { stat_name: '파괴시 방어력', stat_value: 1340 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 50 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    7: [
      { stat_name: '추가피해', stat_value: 82 },
      { stat_name: '방어력', stat_value: 3645 },
      { stat_name: '파괴시 방어력', stat_value: 1481 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 70 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    8: [
      { stat_name: '추가피해', stat_value: 97 },
      { stat_name: '방어력', stat_value: 3669 },
      { stat_name: '파괴시 방어력', stat_value: 1622 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 100 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    9: [
      { stat_name: '추가피해', stat_value: 112 },
      { stat_name: '방어력', stat_value: 3693 },
      { stat_name: '파괴시 방어력', stat_value: 1764 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 130 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    10: [
      { stat_name: '추가피해', stat_value: 130 },
      { stat_name: '방어력', stat_value: 3717 },
      { stat_name: '파괴시 방어력', stat_value: 1905 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 170 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    11: [
      { stat_name: '추가피해', stat_value: 240 },
      { stat_name: '방어력', stat_value: 3752 },
      { stat_name: '파괴시 방어력', stat_value: 2046 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 220 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    12: [
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '방어력', stat_value: 3787 },
      { stat_name: '파괴시 방어력', stat_value: 2187 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 300 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    13: [
      { stat_name: '추가피해', stat_value: 460 },
      { stat_name: '방어력', stat_value: 3822 },
      { stat_name: '파괴시 방어력', stat_value: 2469 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    14: [
      { stat_name: '추가피해', stat_value: 570 },
      { stat_name: '방어력', stat_value: 3867 },
      { stat_name: '파괴시 방어력', stat_value: 2822 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
    15: [
      { stat_name: '추가피해', stat_value: 680 },
      { stat_name: '방어력', stat_value: 3912 },
      { stat_name: '파괴시 방어력', stat_value: 3175 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 34 },
    ],
  },
  ['오르나']: {
    0: [
      { stat_name: '방어력', stat_value: 3633 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 50 },
      { stat_name: '방어력', stat_value: 3658 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 100 },
      { stat_name: '방어력', stat_value: 3683 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 150 },
      { stat_name: '방어력', stat_value: 3708 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 200 },
      { stat_name: '방어력', stat_value: 3733 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 250 },
      { stat_name: '방어력', stat_value: 3758 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    6: [
      { stat_name: '추가피해', stat_value: 300 },
      { stat_name: '방어력', stat_value: 3783 },
      { stat_name: '파괴시 방어력', stat_value: 1380 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 50 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    7: [
      { stat_name: '추가피해', stat_value: 350 },
      { stat_name: '방어력', stat_value: 3808 },
      { stat_name: '파괴시 방어력', stat_value: 1525 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 70 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    8: [
      { stat_name: '추가피해', stat_value: 400 },
      { stat_name: '방어력', stat_value: 3833 },
      { stat_name: '파괴시 방어력', stat_value: 1671 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 100 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    9: [
      { stat_name: '추가피해', stat_value: 450 },
      { stat_name: '방어력', stat_value: 3858 },
      { stat_name: '파괴시 방어력', stat_value: 1816 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 130 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    10: [
      { stat_name: '추가피해', stat_value: 500 },
      { stat_name: '방어력', stat_value: 3883 },
      { stat_name: '파괴시 방어력', stat_value: 1961 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 170 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    11: [
      { stat_name: '추가피해', stat_value: 550 },
      { stat_name: '방어력', stat_value: 3908 },
      { stat_name: '파괴시 방어력', stat_value: 2107 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 220 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    12: [
      { stat_name: '추가피해', stat_value: 600 },
      { stat_name: '방어력', stat_value: 3933 },
      { stat_name: '파괴시 방어력', stat_value: 2252 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 300 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    13: [
      { stat_name: '추가피해', stat_value: 650 },
      { stat_name: '방어력', stat_value: 3958 },
      { stat_name: '파괴시 방어력', stat_value: 2543 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    14: [
      { stat_name: '추가피해', stat_value: 700 },
      { stat_name: '방어력', stat_value: 3983 },
      { stat_name: '파괴시 방어력', stat_value: 2906 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
    15: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 4017 },
      { stat_name: '파괴시 방어력', stat_value: 3269 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
  },
  ['15오르나']: {
    15: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 4017 },
      { stat_name: '파괴시 방어력', stat_value: 3711 },
      { stat_name: '힘', stat_value: 180 },
      { stat_name: '민첩', stat_value: 90 },
      { stat_name: '지능', stat_value: 243 },
      { stat_name: '의지', stat_value: 80 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 29 },
    ],
  },
  ['와드네']: {
    0: [
      { stat_name: '추가피해', stat_value: 750 },
      { stat_name: '방어력', stat_value: 4508 },
      { stat_name: '파괴시 방어력', stat_value: 4057 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 44 },
    ],
    1: [
      { stat_name: '추가피해', stat_value: 780 },
      { stat_name: '방어력', stat_value: 4618 },
      { stat_name: '파괴시 방어력', stat_value: 4156 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 44 },
    ],
    2: [
      { stat_name: '추가피해', stat_value: 810 },
      { stat_name: '방어력', stat_value: 4728 },
      { stat_name: '파괴시 방어력', stat_value: 4255 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 44 },
    ],
    3: [
      { stat_name: '추가피해', stat_value: 840 },
      { stat_name: '방어력', stat_value: 4838 },
      { stat_name: '파괴시 방어력', stat_value: 4354 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 44 },
    ],
    4: [
      { stat_name: '추가피해', stat_value: 870 },
      { stat_name: '방어력', stat_value: 4948 },
      { stat_name: '파괴시 방어력', stat_value: 4453 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 44 },
    ],
    5: [
      { stat_name: '추가피해', stat_value: 900 },
      { stat_name: '방어력', stat_value: 5058 },
      { stat_name: '파괴시 방어력', stat_value: 4552 },
      { stat_name: '힘', stat_value: 225 },
      { stat_name: '민첩', stat_value: 113 },
      { stat_name: '지능', stat_value: 304 },
      { stat_name: '의지', stat_value: 100 },
      { stat_name: '최대 생명력', stat_value: 500 },
      { stat_name: '크리티컬 저항', stat_value: 44 },
    ],
  },
};
