import { ItemType } from "@/app/_type/infoInfoType";

export const charm_list: ItemType[] = [
  {
    name: "잿빛 황혼 브로치",
    restrictions: ["110 레벨 이상"],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    rating: "고급",
    category: ["액세서리", "장신구"],
    color: true,
    enhancement_options: {
      0: [
        { stat_name: "크리티컬", stat_value: 4 },
        { stat_name: "공격속도", stat_value: 3 },
        { stat_name: "방어력", stat_value: 200 },
        { stat_name: "힘", stat_value: 50 },
        { stat_name: "민첩", stat_value: 50 },
        { stat_name: "지능", stat_value: 67 },
        { stat_name: "의지", stat_value: 50 },
      ],
    },
  },
  {
    name: "순백 깃털 브로치",
    restrictions: ["105 레벨 이상"],
    quality: 2,
    quality_selection_available: true,
    rating: "고급",
    category: ["액세서리", "장신구"],
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    color: true,
    enhancement_options: {
      0: [
        { stat_name: "크리티컬", stat_value: 2 },
        { stat_name: "공격속도", stat_value: 2 },
        { stat_name: "방어력", stat_value: 100 },
        { stat_name: "힘", stat_value: 50 },
        { stat_name: "민첩", stat_value: 50 },
        { stat_name: "지능", stat_value: 67 },
        { stat_name: "의지", stat_value: 50 },
      ],
    },
  },
  {
    name: "파란 고양이 브로치",
    restrictions: ["70 레벨 이상"],
    quality: 2,
    quality_selection_available: true,
    rating: "중급",
    category: ["액세서리", "장신구"],
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],

    color: true,
    enhancement_options: {
      0: [
        { stat_name: "크리티컬", stat_value: 1 },
        { stat_name: "방어력", stat_value: 50 },
        { stat_name: "힘", stat_value: 33 },
        { stat_name: "민첩", stat_value: 33 },
        { stat_name: "지능", stat_value: 33 },
        { stat_name: "의지", stat_value: 33 },
      ],
    },
  },
  {
    name: "하얀 고양이 브로치",
    restrictions: ["70 레벨 이상"],
    quality: 2,
    quality_selection_available: true,
    rating: "중급",
    category: ["액세서리", "장신구"],
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    color: true,
    enhancement_options: {
      0: [
        { stat_name: "공격속도", stat_value: 2 },
        { stat_name: "힘", stat_value: 48 },
        { stat_name: "민첩", stat_value: 48 },
        { stat_name: "지능", stat_value: 48 },
        { stat_name: "의지", stat_value: 48 },
      ],
    },
  },
  {
    name: "고양이 브로치",
    restrictions: ["40 레벨 이상"],
    quality: 2,
    quality_selection_available: true,
    rating: "중급",
    category: ["액세서리", "장신구"],
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    enhancement_options: {
      0: [
        { stat_name: "공격력", stat_value: 85 },
        { stat_name: "마법공격력", stat_value: 85 },
        { stat_name: "힘", stat_value: 19 },
        { stat_name: "민첩", stat_value: 19 },
        { stat_name: "지능", stat_value: 19 },
        { stat_name: "의지", stat_value: 19 },
      ],
    },
    color: true,
  },
];
