import { ItemType } from "@/app/_type/infoInfoType";
import { hand_level_options } from "../item_level_options/hand_level_options";

export const hand_list: ItemType[] = [
  {
    name: "아르드리 건틀릿",
    restrictions: [
      "110 레벨 이상",
      "방어구 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "손 방어구"],
    set: "아르드리",
    enhancement_options: hand_level_options.아르드리,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    grinding: true,
  },
  {
    name: "오르나 건틀릿",
    restrictions: [
      "115 레벨 이상",
      "방어구 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "손 방어구"],
    set: "오르나",
    enhancement_options: hand_level_options.오르나,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    grinding: true,
  },
];
// import { ItemType } from "@/app/_type/infoInfoType";

// export const hand_list: ItemType[] = [
//   {
//     name: "아르드리 건틀릿",
//     restrictions: [
//       "110 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "손 방어구"],
//     set: "아르드리",
//     grinding: true,
//     stats: [
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "방어력", stat_value: 4338 },
//       { stat_name: "파괴시 방어력", stat_value: 3558 },
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "크리티컬 저항", stat_value: 29 },
//     ],
//   },
//   {
//     name: "오르나 건틀릿",
//     restrictions: [
//       "115 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "손 방어구"],
//     set: "오르나",
//     grinding: true,
//     stats: [
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "방어력", stat_value: 4338 },
//       { stat_name: "파괴시 방어력", stat_value: 3558 },
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "크리티컬 저항", stat_value: 29 },
//     ],
//   },
//   {
//     name: "+15 오르나 건틀릿",
//     restrictions: [
//       "115 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "손 방어구"],
//     set: "오르나",
//     grinding: true,
//     stats: [
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "방어력", stat_value: 4338 },
//       { stat_name: "파괴시 방어력", stat_value: 3558 },
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "크리티컬 저항", stat_value: 29 },
//     ],
//   },
// ];
