import { ItemType } from "@/app/_type/infoInfoType";

export const head_list: ItemType[] = [
  {
    name: "+15 오르나 헬름",
    restrictions: [
      "115 레벨 이상",
      "방어구 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "머리 방어구"],
    set: "오르나",
    grinding: true,
    stats: [
      { stat_name: "힘", stat_value: 180 },
      { stat_name: "지능", stat_value: 243 },
      { stat_name: "민첩", stat_value: 90 },
      { stat_name: "의지", stat_value: 80 },
      { stat_name: "생명력", stat_value: 500 },
      { stat_name: "방어력", stat_value: 4338 },
      { stat_name: "파괴시 방어력", stat_value: 3558 },
      { stat_name: "추가피해", stat_value: 750 },
      { stat_name: "크리티컬 저항", stat_value: 29 },
    ],
  },
  {
    name: "와드네 헬름",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "일반",
    category: ["플레이트", "머리 방어구"],
    color: false,
    set: "와드네",

    stats: [
      { stat_name: "추가피해", stat_value: 750 },
      { stat_name: "방어력", stat_value: 4338 },
      { stat_name: "파괴시 방어력", stat_value: 3904 },
      { stat_name: "힘", stat_value: 180 },
      { stat_name: "민첩", stat_value: 90 },
      { stat_name: "지능", stat_value: 243 },
      { stat_name: "의지", stat_value: 80 },
      { stat_name: "생명력", stat_value: 500 },
      { stat_name: "크리티컬 저항", stat_value: 33 },
    ],
  },
  {
    name: "초급 와드네 헬름",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "초급",
    category: ["플레이트", "머리 방어구"],
    color: false,
    set: "와드네",

    stats: [
      { stat_name: "추가피해", stat_value: 780 },
      { stat_name: "방어력", stat_value: 4448 },
      { stat_name: "파괴시 방어력", stat_value: 4003 },
      { stat_name: "힘", stat_value: 180 },
      { stat_name: "민첩", stat_value: 90 },
      { stat_name: "지능", stat_value: 243 },
      { stat_name: "의지", stat_value: 80 },
      { stat_name: "생명력", stat_value: 500 },
      { stat_name: "크리티컬 저항", stat_value: 33 },
    ],
  },
  {
    name: "중급 와드네 헬름",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "중급",
    category: ["플레이트", "머리 방어구"],
    color: false,
    set: "와드네",

    stats: [
      { stat_name: "추가피해", stat_value: 810 },
      { stat_name: "방어력", stat_value: 4558 },
      { stat_name: "파괴시 방어력", stat_value: 4102 },
      { stat_name: "힘", stat_value: 180 },
      { stat_name: "민첩", stat_value: 90 },
      { stat_name: "지능", stat_value: 243 },
      { stat_name: "의지", stat_value: 80 },
      { stat_name: "생명력", stat_value: 500 },
      { stat_name: "크리티컬 저항", stat_value: 33 },
    ],
  },
  {
    name: "고급 와드네 헬름",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "고급",
    category: ["플레이트", "머리 방어구"],
    color: false,
    set: "와드네",

    stats: [
      { stat_name: "추가피해", stat_value: 840 },
      { stat_name: "방어력", stat_value: 4668 },
      { stat_name: "파괴시 방어력", stat_value: 4201 },
      { stat_name: "힘", stat_value: 180 },
      { stat_name: "민첩", stat_value: 90 },
      { stat_name: "지능", stat_value: 243 },
      { stat_name: "의지", stat_value: 80 },
      { stat_name: "생명력", stat_value: 500 },
      { stat_name: "크리티컬 저항", stat_value: 33 },
    ],
  },
  {
    name: "레어 와드네 헬름",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "머리 방어구"],
    set: "와드네",

    stats: [
      { stat_name: "추가피해", stat_value: 870 },
      { stat_name: "방어력", stat_value: 4778 },
      { stat_name: "파괴시 방어력", stat_value: 4300 },
      { stat_name: "힘", stat_value: 180 },
      { stat_name: "민첩", stat_value: 90 },
      { stat_name: "지능", stat_value: 243 },
      { stat_name: "의지", stat_value: 80 },
      { stat_name: "생명력", stat_value: 500 },
      { stat_name: "크리티컬 저항", stat_value: 33 },
    ],
  },
  {
    name: "전설 와드네 헬름",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "전설",
    category: ["플레이트", "머리 방어구"],
    color: false,
    set: "와드네",

    stats: [
      { stat_name: "추가피해", stat_value: 900 },
      { stat_name: "방어력", stat_value: 4888 },
      { stat_name: "파괴시 방어력", stat_value: 4399 },
      { stat_name: "힘", stat_value: 180 },
      { stat_name: "민첩", stat_value: 90 },
      { stat_name: "지능", stat_value: 243 },
      { stat_name: "의지", stat_value: 80 },
      { stat_name: "생명력", stat_value: 500 },
      { stat_name: "크리티컬 저항", stat_value: 33 },
    ],
  },
];
