import { ItemType } from '@/app/_type/infoInfoType';

export const left_hand_list: ItemType[] = [
  {
    name: '와드네 스몰실드',
    restrictions: ['피오나 전용', '120 레벨 이상', '실드 마스터리 6랭크 이상'],
    category: ['방패'],
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    color: false,
    enhancement_options: {
      0: [
        { stat_name: '공격력', stat_value: 1410 },
        { stat_name: '마법공격력', stat_value: 1410 },
        { stat_name: '크리티컬', stat_value: 10 },
        { stat_name: '공격속도', stat_value: 3 },
        { stat_name: '방어력', stat_value: 3090 },
        { stat_name: '힘', stat_value: 180 },
        { stat_name: '민첩', stat_value: 90 },
        { stat_name: '지능', stat_value: 243 },
        { stat_name: '의지', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 17 },
      ],
    },
  },
  {
    name: '와드네 라지실드',
    restrictions: [
      '피오나 전용',
      '120 레벨 이상',
      '라지실드 마스터리 6랭크 이상',
    ],
    category: ['대형방패'],
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    color: false,
    enhancement_options: {
      0: [
        { stat_name: '공격력', stat_value: 1410 },
        { stat_name: '마법공격력', stat_value: 1410 },
        { stat_name: '크리티컬', stat_value: 10 },
        { stat_name: '공격속도', stat_value: 3 },
        { stat_name: '방어력', stat_value: 3530 },
        { stat_name: '힘', stat_value: 180 },
        { stat_name: '민첩', stat_value: 90 },
        { stat_name: '지능', stat_value: 243 },
        { stat_name: '의지', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 17 },
      ],
    },
  },
  {
    name: '와드네 그랜드타지',
    restrictions: [
      '아켈 전용',
      '120 레벨 이상',
      '그랜드타지 마스터리 6랭크 이상',
    ],
    category: ['그랜드타지'],
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    color: false,
    enhancement_options: {
      0: [
        { stat_name: '공격력', stat_value: 1410 },
        { stat_name: '마법공격력', stat_value: 1410 },
        { stat_name: '크리티컬', stat_value: 10 },
        { stat_name: '공격속도', stat_value: 3 },
        { stat_name: '방어력', stat_value: 3090 },
        { stat_name: '힘', stat_value: 180 },
        { stat_name: '민첩', stat_value: 90 },
        { stat_name: '지능', stat_value: 243 },
        { stat_name: '의지', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 17 },
      ],
    },
  },
  {
    name: '와드네 캐스틀릿',
    restrictions: [
      '아리샤 전용',
      '120 레벨 이상',
      '캐스틀릿 마스터리 A랭크 이상',
    ],
    category: ['캐스틀릿'],
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    color: true,
    enhancement_options: {
      0: [
        { stat_name: '공격력', stat_value: 1410 },
        { stat_name: '마법공격력', stat_value: 1410 },
        { stat_name: '크리티컬', stat_value: 10 },
        { stat_name: '공격속도', stat_value: 3 },
        { stat_name: '방어력', stat_value: 3090 },
        { stat_name: '힘', stat_value: 180 },
        { stat_name: '민첩', stat_value: 90 },
        { stat_name: '지능', stat_value: 243 },
        { stat_name: '의지', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 17 },
      ],
    },
  },
  {
    name: '와드네의 서',
    restrictions: [
      '리시타',
      '이비',
      '카이',
      '벨라',
      '허크',
      '린',
      '헤기',
      '델리아',
      '미리',
      '그림덴',
      '미울',
      '벨',
      '레서',
      '카엘',
      '테사',
      '단아',
      '레티',
      '라티야',
      '체른',
      '소우',
      '사냐',
      '네반',
      '120 레벨 이상',
    ],
    category: ['수호부'],
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    color: true,
    enhancement_options: {
      0: [
        { stat_name: '공격력', stat_value: 1410 },
        { stat_name: '마법공격력', stat_value: 1410 },
        { stat_name: '크리티컬', stat_value: 10 },
        { stat_name: '공격속도', stat_value: 3 },
        { stat_name: '방어력', stat_value: 3090 },
        { stat_name: '힘', stat_value: 180 },
        { stat_name: '민첩', stat_value: 90 },
        { stat_name: '지능', stat_value: 243 },
        { stat_name: '의지', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 17 },
      ],
    },
  },
  {
    name: '전승의 서',
    restrictions: [
      '리시타',
      '이비',
      '카이',
      '벨라',
      '허크',
      '린',
      '헤기',
      '델리아',
      '미리',
      '그림덴',
      '미울',
      '벨',
      '레서',
      '카엘',
      '테사',
      '단아',
      '레티',
      '라티야',
      '체른',
      '소우',
      '사냐',
      '네반',
      '95 레벨 이상',
    ],
    category: ['수호부'],
    quality: 2,
    quality_selection_available: true,
    rating: '고급',
    color: true,
    enhancement_options: {
      0: [
        { stat_name: '크리티컬', stat_value: 3 },
        { stat_name: '방어력', stat_value: 40 },
        { stat_name: '힘', stat_value: 60 },
        { stat_name: '지능', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 1 },
      ],
    },
  },
  {
    name: '아르드리의 서',
    restrictions: [
      '리시타',
      '이비',
      '카이',
      '벨라',
      '허크',
      '린',
      '헤기',
      '델리아',
      '미리',
      '그림덴',
      '미울',
      '벨',
      '레서',
      '카엘',
      '테사',
      '단아',
      '레티',
      '라티야',
      '체른',
      '소우',
      '사냐',
      '네반',
      '110 레벨 이상',
    ],
    category: ['수호부'],
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    color: true,
    enhancement_options: {
      0: [
        { stat_name: '공격력', stat_value: 610 },
        { stat_name: '마법공격력', stat_value: 610 },
        { stat_name: '크리티컬', stat_value: 8 },
        { stat_name: '공격속도', stat_value: 3 },
        { stat_name: '방어력', stat_value: 2290 },
        { stat_name: '힘', stat_value: 180 },
        { stat_name: '민첩', stat_value: 90 },
        { stat_name: '지능', stat_value: 243 },
        { stat_name: '의지', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 12 },
      ],
    },
  },
  {
    name: '오르나의 서',
    restrictions: [
      '리시타',
      '이비',
      '카이',
      '벨라',
      '허크',
      '린',
      '헤기',
      '델리아',
      '미리',
      '그림덴',
      '미울',
      '벨',
      '레서',
      '카엘',
      '테사',
      '단아',
      '레티',
      '라티야',
      '체른',
      '소우',
      '사냐',
      '네반',
      '115 레벨 이상',
    ],
    category: ['수호부'],
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    color: true,
    enhancement_options: {
      0: [
        { stat_name: '공격력', stat_value: 1010 },
        { stat_name: '마법공격력', stat_value: 1010 },
        { stat_name: '크리티컬', stat_value: 7 },
        { stat_name: '공격속도', stat_value: 3 },
        { stat_name: '방어력', stat_value: 2690 },
        { stat_name: '힘', stat_value: 180 },
        { stat_name: '민첩', stat_value: 90 },
        { stat_name: '지능', stat_value: 243 },
        { stat_name: '의지', stat_value: 80 },
        { stat_name: '크리티컬 저항', stat_value: 14 },
      ],
    },
  },
];
