import { ItemType } from "@/app/_type/infoInfoType";
import { lower_level_options } from "../item_level_options/lower_level_options";

export const lower_list: ItemType[] = [
  {
    name: "아르드리 그리브즈",
    restrictions: [
      "110 레벨 이상",
      "방어구 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "다리 방어구"],
    set: "아르드리",
    grinding: true,
    enhancement_options: lower_level_options.아르드리,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
  {
    name: "오르나 그리브즈",
    restrictions: [
      "115 레벨 이상",
      "방어구 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "다리 방어구"],
    set: "오르나",
    grinding: true,
    enhancement_options: lower_level_options.오르나,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
  {
    name: "와드네 그리브즈",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "일반",
    category: ["플레이트", "다리 방어구"],
    set: "와드네",
    enhancement_options: lower_level_options.와드네,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
  {
    name: "초급 와드네 그리브즈",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "초급",
    category: ["플레이트", "다리 방어구"],
    set: "와드네",
    enhancement_options: lower_level_options.와드네,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
  {
    name: "중급 와드네 그리브즈",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "중급",
    category: ["플레이트", "다리 방어구"],
    set: "와드네",
    enhancement_options: lower_level_options.와드네,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
  {
    name: "고급 와드네 그리브즈",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "고급",
    category: ["플레이트", "다리 방어구"],
    set: "와드네",
    enhancement_options: lower_level_options.와드네,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
  {
    name: "레어 와드네 그리브즈",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "다리 방어구"],
    set: "와드네",
    enhancement_options: lower_level_options.와드네,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
  {
    name: "전설 와드네 그리브즈",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "전설",
    category: ["플레이트", "다리 방어구"],
    set: "와드네",
    enhancement_options: lower_level_options.와드네,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
  },
];
// import { ItemType } from "@/app/_type/infoInfoType";
// import { lower_level_options } from "../item_level_options/lower_level_options";

// export const lower_list: ItemType[] = [
//   {
//     name: "아르드리 그리브즈",
//     restrictions: [
//       "110 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "다리 방어구"],
//     set: "아르드리",
//     grinding: true,
//     enhancement_options: lower_level_options,
//     stats: [
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "방어력", stat_value: 4293 },
//       { stat_name: "파괴시 방어력", stat_value: 3518 },
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "크리티컬 저항", stat_value: 46 },
//     ],
//   },
//   {
//     name: "오르나 그리브즈",
//     restrictions: [
//       "115 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "다리 방어구"],
//     set: "오르나",
//     grinding: true,
//     enhancement_options: lower_level_options,
//     stats: [
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "방어력", stat_value: 4293 },
//       { stat_name: "파괴시 방어력", stat_value: 3518 },
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "크리티컬 저항", stat_value: 46 },
//     ],
//   },
//   {
//     name: "+15 오르나 그리브즈",
//     restrictions: [
//       "115 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "다리 방어구"],
//     set: "오르나",
//     grinding: true,
//     enhancement_options: lower_level_options,
//     stats: [
//       { stat_name: "힘", stat_value: 180 },
//       { stat_name: "지능", stat_value: 243 },
//       { stat_name: "민첩", stat_value: 90 },
//       { stat_name: "의지", stat_value: 80 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "방어력", stat_value: 4293 },
//       { stat_name: "파괴시 방어력", stat_value: 3518 },
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "크리티컬 저항", stat_value: 46 },
//     ],
//   },
//   {
//     name: "와드네 그리브즈",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "일반",
//     category: ["플레이트", "다리 방어구"],
//     set: "와드네",
//     enhancement_options: lower_level_options,
//     stats: [
//       { stat_name: "추가피해", stat_value: 750 },
//       { stat_name: "방어력", stat_value: 4293 },
//       { stat_name: "파괴시 방어력", stat_value: 3863 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//   },
//   {
//     name: "초급 와드네 그리브즈",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "초급",
//     category: ["플레이트", "다리 방어구"],
//     set: "와드네",
//     enhancement_options: lower_level_options,
//     stats: [
//       { stat_name: "추가피해", stat_value: 780 },
//       { stat_name: "방어력", stat_value: 4403 },
//       { stat_name: "파괴시 방어력", stat_value: 3962 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//   },
//   {
//     name: "중급 와드네 그리브즈",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "중급",
//     category: ["플레이트", "다리 방어구"],
//     set: "와드네",
//     enhancement_options: lower_level_options,
//     stats: [
//       { stat_name: "추가피해", stat_value: 810 },
//       { stat_name: "방어력", stat_value: 4513 },
//       { stat_name: "파괴시 방어력", stat_value: 4061 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//   },
//   {
//     name: "고급 와드네 그리브즈",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "고급",
//     category: ["플레이트", "다리 방어구"],
//     set: "와드네",
//     enhancement_options: lower_level_options,
//     stats: [
//       { stat_name: "추가피해", stat_value: 840 },
//       { stat_name: "방어력", stat_value: 4623 },
//       { stat_name: "파괴시 방어력", stat_value: 4160 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//   },
//   {
//     name: "레어 와드네 그리브즈",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "다리 방어구"],
//     set: "와드네",
//     stats: [
//       { stat_name: "추가피해", stat_value: 870 },
//       { stat_name: "방어력", stat_value: 4733 },
//       { stat_name: "파괴시 방어력", stat_value: 4259 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//   },
//   {
//     name: "전설 와드네 그리브즈",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "전설",
//     category: ["플레이트", "다리 방어구"],
//     set: "와드네",

//     stats: [
//       { stat_name: "추가피해", stat_value: 900 },
//       { stat_name: "방어력", stat_value: 4843 },
//       { stat_name: "파괴시 방어력", stat_value: 4358 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 52 },
//     ],
//   },
// ];
