import { ItemType } from '@/app/_type/infoInfoType';
import { right_hand_level_options } from '../item_level_options/right_hand_level_options';

export const right_hand_list: ItemType[] = [
  {
    name: '밀레시안 무기',
    restrictions: ['105 레벨 이상', '최대 강화 15단계', '최대 품질 5성'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '레어',
    category: ['무기'],
    set: '밀레시안',
    grinding: true,
  },
  {
    name: '아르드리 무기',
    restrictions: [
      '110 레벨 이상',
      '무기 마스터리 6랭크 이상',
      '최대 강화 15단계',
      '최대 품질 5성',
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '레어',
    category: ['무기'],
    set: '아르드리',
    grinding: true,
    enhancement_options: right_hand_level_options['아르드리'],
  },
  {
    name: '오르나 무기',
    restrictions: [
      '115 레벨 이상',
      '무기 마스터리 6랭크 이상',
      '최대 강화 15단계',
      '최대 품질 5성',
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '레어',
    category: ['무기'],
    set: '오르나',
    grinding: true,
    enhancement_options: right_hand_level_options['오르나'],
  },
  {
    name: '+15 오르나 무기',
    restrictions: [
      '115 레벨 이상',
      '무기 마스터리 6랭크 이상',
      '최대 강화 15단계',
      '최대 품질 5성',
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '레어',
    category: ['무기'],
    set: '오르나',
    grinding: true,
    slot: 'Right Hand',
    enhancement_options: right_hand_level_options['15오르나'],
  },
  {
    name: '와드네 무기',
    restrictions: [
      '120 레벨 이상',
      '무기 마스터리 5랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '일반',
    category: ['무기'],
    color: false,
    set: '와드네',
    enhancement_options: right_hand_level_options['와드네'],
  },
  {
    name: '초급 와드네 무기',
    restrictions: [
      '120 레벨 이상',
      '무기 마스터리 5랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '초급',
    category: ['무기'],
    color: false,
    set: '와드네',
    enhancement_options: right_hand_level_options['와드네'],
  },
  {
    name: '중급 와드네 무기',
    restrictions: [
      '120 레벨 이상',
      '무기 마스터리 5랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '중급',
    category: ['무기'],
    color: false,
    set: '와드네',
    enhancement_options: right_hand_level_options['와드네'],
  },
  {
    name: '고급 와드네 무기',
    restrictions: [
      '120 레벨 이상',
      '무기 마스터리 5랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '고급',
    category: ['무기'],
    color: false,
    set: '와드네',
    enhancement_options: right_hand_level_options['와드네'],
  },
  {
    name: '레어 와드네 무기',
    restrictions: [
      '120 레벨 이상',
      '무기 마스터리 5랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '레어',
    category: ['무기'],
    color: false,
    set: '와드네',
    enhancement_options: right_hand_level_options['와드네'],
  },
  {
    name: '전설 와드네 무기',
    restrictions: [
      '120 레벨 이상',
      '무기 마스터리 5랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '전설',
    category: ['무기'],
    color: false,
    set: '와드네',
    enhancement_options: right_hand_level_options['와드네'],
  },
  {
    name: '에리우 무기',
    restrictions: [
      '125 레벨 이상',
      '무기 마스터리 4랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '일반',
    category: ['무기'],
    color: false,
    set: '에리우',
    enhancement_options: right_hand_level_options['에리우'],
  },
  {
    name: '초급 에리우 무기',
    restrictions: [
      '125 레벨 이상',
      '무기 마스터리 4랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '초급',
    category: ['무기'],
    color: false,
    set: '에리우',
    enhancement_options: right_hand_level_options['에리우'],
  },
  {
    name: '중급 에리우 무기',
    restrictions: [
      '125 레벨 이상',
      '무기 마스터리 4랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '중급',
    category: ['무기'],
    color: false,
    set: '에리우',
    enhancement_options: right_hand_level_options['에리우'],
  },
  {
    name: '고급 에리우 무기',
    restrictions: [
      '125 레벨 이상',
      '무기 마스터리 4랭크 이상',
      '최대 품질 5성',
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ['공격력', '마법공격력', '힘', '민첩', '지능', '의지'],
    rating: '고급',
    category: ['무기'],
    color: false,
    set: '에리우',
    enhancement_options: right_hand_level_options['에리우'],
  },
];
