import { ItemType } from "@/app/_type/infoInfoType";
import { right_hand_level_options } from "../item_level_options/right_hand_level_options";

export const right_hand_list: ItemType[] = [
  {
    name: "아르드리 무기",
    restrictions: [
      "110 레벨 이상",
      "무기 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    rating: "레어",
    category: ["무기"],
    set: "아르드리",
    grinding: true,
    enhancement_options: right_hand_level_options["아르드리"],
  },
  {
    name: "오르나 무기",
    restrictions: [
      "115 레벨 이상",
      "무기 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    rating: "레어",
    category: ["무기"],
    set: "오르나",
    grinding: true,
    enhancement_options: right_hand_level_options["오르나"],
  },
  {
    name: "와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    rating: "일반",
    category: ["무기"],
    color: false,
    set: "와드네",
    enhancement_options: right_hand_level_options["와드네"],
  },
  {
    name: "초급 와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    rating: "초급",
    category: ["무기"],
    color: false,
    set: "와드네",
    enhancement_options: right_hand_level_options["와드네"],
  },
  {
    name: "중급 와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    rating: "중급",
    category: ["무기"],
    color: false,
    set: "와드네",
    enhancement_options: right_hand_level_options["와드네"],
  },
  {
    name: "고급 와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["공격력", "마법공격력", "힘", "민첩", "지능", "의지"],
    rating: "고급",
    category: ["무기"],
    color: false,
    set: "와드네",
    enhancement_options: right_hand_level_options["와드네"],
  },
];
// import { ItemType } from "@/app/_type/infoInfoType";
// export const right_hand_list: ItemType[] = [
//   {
//     // 15강에 연마 제외 풀 연마된 아이템
//     name: "+15 오르나 무기",
//     restrictions: [
//       "115 레벨 이상",
//       "무기 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["무기"],
//     set: "오르나",
//     grinding: true,
//     stats: [
//       { stat_name: "공격력", stat_value: 34900 },
//       { stat_name: "마법공격력", stat_value: 34900 },
//       { stat_name: "밸런스", stat_value: 59 },
//       { stat_name: "크리티컬", stat_value: 120 },
//       { stat_name: "공격속도", stat_value: 47 },
//       { stat_name: "추가피해", stat_value: 3750 },
//       { stat_name: "힘", stat_value: 110 },
//       { stat_name: "민첩", stat_value: 60 },
//       { stat_name: "지능", stat_value: 148 },
//       { stat_name: "의지", stat_value: 80 },
//     ],
//   },
//   {
//     name: "와드네 무기",
//     restrictions: [
//       "120 레벨 이상",
//       "무기 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     quality: 2,
//     quality_selection_available: true,
//     rating: "일반",
//     category: ["무기"],
//     color: false,
//     set: "와드네",
//     stats: [
//       { stat_name: "공격력", stat_value: 34900 },
//       { stat_name: "마법공격력", stat_value: 34900 },
//       { stat_name: "밸런스", stat_value: 67 },
//       { stat_name: "크리티컬", stat_value: 128 },
//       { stat_name: "공격속도", stat_value: 47 },
//       { stat_name: "추가피해", stat_value: 3750 },
//       { stat_name: "힘", stat_value: 110 },
//       { stat_name: "민첩", stat_value: 60 },
//       { stat_name: "지능", stat_value: 148 },
//       { stat_name: "의지", stat_value: 80 },
//     ],
//   },
//   {
//     name: "초급 와드네 무기",
//     restrictions: [
//       "120 레벨 이상",
//       "무기 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     quality: 2,
//     quality_selection_available: true,
//     rating: "초급",
//     category: ["무기"],
//     color: false,
//     set: "와드네",
//     stats: [
//       { stat_name: "공격력", stat_value: 35400 },
//       { stat_name: "마법공격력", stat_value: 35400 },
//       { stat_name: "밸런스", stat_value: 67 },
//       { stat_name: "크리티컬", stat_value: 128 },
//       { stat_name: "공격속도", stat_value: 47 },
//       { stat_name: "추가피해", stat_value: 3850 },
//       { stat_name: "힘", stat_value: 110 },
//       { stat_name: "민첩", stat_value: 60 },
//       { stat_name: "지능", stat_value: 148 },
//       { stat_name: "의지", stat_value: 80 },
//     ],
//   },
//   {
//     name: "중급 와드네 무기",
//     restrictions: [
//       "120 레벨 이상",
//       "무기 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     quality: 2,
//     quality_selection_available: true,
//     rating: "중급",
//     category: ["무기"],
//     color: false,
//     set: "와드네",

//     stats: [
//       { stat_name: "공격력", stat_value: 35900 },
//       { stat_name: "마법공격력", stat_value: 35900 },
//       { stat_name: "밸런스", stat_value: 67 },
//       { stat_name: "크리티컬", stat_value: 128 },
//       { stat_name: "공격속도", stat_value: 47 },
//       { stat_name: "추가피해", stat_value: 3950 },
//       { stat_name: "힘", stat_value: 110 },
//       { stat_name: "민첩", stat_value: 60 },
//       { stat_name: "지능", stat_value: 148 },
//       { stat_name: "의지", stat_value: 80 },
//     ],
//   },
//   {
//     name: "고급 와드네 무기",
//     restrictions: [
//       "120 레벨 이상",
//       "무기 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "고급",
//     category: ["무기"],
//     set: "와드네",

//     stats: [
//       { stat_name: "공격력", stat_value: 36400 },
//       { stat_name: "마법공격력", stat_value: 36400 },
//       { stat_name: "밸런스", stat_value: 67 },
//       { stat_name: "크리티컬", stat_value: 128 },
//       { stat_name: "공격속도", stat_value: 47 },
//       { stat_name: "추가피해", stat_value: 4050 },
//       { stat_name: "힘", stat_value: 110 },
//       { stat_name: "민첩", stat_value: 60 },
//       { stat_name: "지능", stat_value: 148 },
//       { stat_name: "의지", stat_value: 80 },
//     ],
//   },
// ];
