import { ItemType } from "@/app/_type/infoInfoType";
export const right_hand_list: ItemType[] = [
  {
    name: "+15 오르나 무기",
    restrictions: [
      "115 레벨 이상",
      "무기 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["무기"],
    set: "오르나",
    grinding: true,
    stats: [
      { stat_name: "공격력", stat_value: 34900 },
      { stat_name: "마법공격력", stat_value: 34900 },
      { stat_name: "밸런스", stat_value: 59 },
      { stat_name: "크리티컬", stat_value: 120 },
      { stat_name: "공격속도", stat_value: 47 },
      { stat_name: "추가피해", stat_value: 3750 },
      { stat_name: "힘", stat_value: 110 },
      { stat_name: "민첩", stat_value: 60 },
      { stat_name: "지능", stat_value: 148 },
      { stat_name: "의지", stat_value: 80 },
    ],
  },
  {
    name: "와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "일반",
    category: ["무기"],
    color: false,
    set: "와드네",
    stats: [
      { stat_name: "공격력", stat_value: 34900 },
      { stat_name: "마법공격력", stat_value: 34900 },
      { stat_name: "밸런스", stat_value: 67 },
      { stat_name: "크리티컬", stat_value: 128 },
      { stat_name: "공격속도", stat_value: 47 },
      { stat_name: "추가피해", stat_value: 3750 },
      { stat_name: "힘", stat_value: 110 },
      { stat_name: "민첩", stat_value: 60 },
      { stat_name: "지능", stat_value: 148 },
      { stat_name: "의지", stat_value: 80 },
    ],
  },
  {
    name: "초급 와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "초급",
    category: ["무기"],
    color: false,
    set: "와드네",
    stats: [
      { stat_name: "공격력", stat_value: 35400 },
      { stat_name: "마법공격력", stat_value: 35400 },
      { stat_name: "밸런스", stat_value: 67 },
      { stat_name: "크리티컬", stat_value: 128 },
      { stat_name: "공격속도", stat_value: 47 },
      { stat_name: "추가피해", stat_value: 3850 },
      { stat_name: "힘", stat_value: 110 },
      { stat_name: "민첩", stat_value: 60 },
      { stat_name: "지능", stat_value: 148 },
      { stat_name: "의지", stat_value: 80 },
    ],
  },
  {
    name: "중급 와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    quality: 2,
    quality_selection_available: true,
    rating: "중급",
    category: ["무기"],
    color: false,
    set: "와드네",

    stats: [
      { stat_name: "공격력", stat_value: 35900 },
      { stat_name: "마법공격력", stat_value: 35900 },
      { stat_name: "밸런스", stat_value: 67 },
      { stat_name: "크리티컬", stat_value: 128 },
      { stat_name: "공격속도", stat_value: 47 },
      { stat_name: "추가피해", stat_value: 3950 },
      { stat_name: "힘", stat_value: 110 },
      { stat_name: "민첩", stat_value: 60 },
      { stat_name: "지능", stat_value: 148 },
      { stat_name: "의지", stat_value: 80 },
    ],
  },
  {
    name: "고급 와드네 무기",
    restrictions: [
      "120 레벨 이상",
      "무기 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "고급",
    category: ["무기"],
    set: "와드네",

    stats: [
      { stat_name: "공격력", stat_value: 36400 },
      { stat_name: "마법공격력", stat_value: 36400 },
      { stat_name: "밸런스", stat_value: 67 },
      { stat_name: "크리티컬", stat_value: 128 },
      { stat_name: "공격속도", stat_value: 47 },
      { stat_name: "추가피해", stat_value: 4050 },
      { stat_name: "힘", stat_value: 110 },
      { stat_name: "민첩", stat_value: 60 },
      { stat_name: "지능", stat_value: 148 },
      { stat_name: "의지", stat_value: 80 },
    ],
  },
];
