import { ItemType } from "@/app/_type/infoInfoType";
import { upper_level_options } from "../item_level_options/upper_level_options";

export const upper_list: ItemType[] = [
  {
    name: "아르드리 메일",
    restrictions: [
      "110 레벨 이상",
      "방어구 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "가슴 방어구"],
    set: "아르드리",
    enhancement_options: upper_level_options.아르드리,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    grinding: true,
  },
  {
    name: "오르나 메일",
    restrictions: [
      "115 레벨 이상",
      "방어구 마스터리 6랭크 이상",
      "최대 강화 15단계",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: "레어",
    category: ["플레이트", "가슴 방어구"],
    set: "오르나",
    enhancement_options: upper_level_options.오르나,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    grinding: true,
  },
  {
    name: "와드네 메일",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    rating: "일반",
    set: "와드네",
    enhancement_options: upper_level_options.와드네,
    category: ["플레이트", "가슴 방어구"],
  },
  {
    name: "초급 와드네 메일",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    rating: "초급",
    set: "와드네",
    enhancement_options: upper_level_options.와드네,
    category: ["플레이트", "가슴 방어구"],
  },
  {
    name: "중급 와드네 메일",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    rating: "중급",
    set: "와드네",
    enhancement_options: upper_level_options.와드네,
    category: ["플레이트", "가슴 방어구"],
  },
  {
    name: "고급 와드네 메일",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    rating: "고급",
    set: "와드네",
    enhancement_options: upper_level_options.와드네,
    category: ["플레이트", "가슴 방어구"],
  },
  {
    name: "레어 와드네 메일",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    rating: "레어",
    set: "와드네",
    enhancement_options: upper_level_options.와드네,
    category: ["플레이트", "가슴 방어구"],
  },
  {
    name: "전설 와드네 메일",
    restrictions: [
      "120 레벨 이상",
      "방어구 마스터리 5랭크 이상",
      "최대 품질 5성",
    ],
    color: false,
    quality: 2,
    quality_selection_available: true,
    quality_stats: ["방어력", "힘", "민첩", "지능", "의지"],
    rating: "전설",
    set: "와드네",
    enhancement_options: upper_level_options.와드네,
    category: ["플레이트", "가슴 방어구"],
  },
];
// import { ItemType } from "@/app/_type/infoInfoType";

// export const upper_list: ItemType[] = [
//   {
//     name: "아르드리 메일",
//     restrictions: [
//       "110 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "가슴 방어구"],
//     set: "아르드리",
//     grinding: true,
//   },
//   {
//     name: "오르나 메일",
//     restrictions: [
//       "115 레벨 이상",
//       "방어구 마스터리 6랭크 이상",
//       "최대 강화 15단계",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "가슴 방어구"],
//     set: "오르나",
//     grinding: true,
//   },
//   {
//     name: "와드네 메일",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "일반",
//     set: "와드네",
//     category: ["플레이트", "가슴 방어구"],
//   },
//   {
//     name: "초급 와드네 메일",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     quality: 2,
//     quality_selection_available: true,
//     rating: "초급",
//     category: ["플레이트", "가슴 방어구"],
//     set: "와드네",

//     color: false,
//     stats: [
//       { stat_name: "추가피해", stat_value: 780 },
//       { stat_name: "방어력", stat_value: 4618 },
//       { stat_name: "파괴시 방어력", stat_value: 4156 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 44 },
//     ],
//   },
//   {
//     name: "중급 와드네 메일",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     quality: 2,
//     quality_selection_available: true,
//     rating: "중급",
//     category: ["플레이트", "가슴 방어구"],
//     set: "와드네",

//     color: false,
//     stats: [
//       { stat_name: "추가피해", stat_value: 810 },
//       { stat_name: "방어력", stat_value: 4728 },
//       { stat_name: "파괴시 방어력", stat_value: 4255 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 44 },
//     ],
//   },
//   {
//     name: "고급 와드네 메일",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "고급",
//     category: ["플레이트", "가슴 방어구"],
//     set: "와드네",

//     stats: [
//       { stat_name: "추가피해", stat_value: 840 },
//       { stat_name: "방어력", stat_value: 4838 },
//       { stat_name: "파괴시 방어력", stat_value: 4354 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 44 },
//     ],
//   },
//   {
//     name: "레어 와드네 메일",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     quality: 2,
//     quality_selection_available: true,
//     rating: "레어",
//     category: ["플레이트", "가슴 방어구"],
//     set: "와드네",

//     color: false,
//     stats: [
//       { stat_name: "추가피해", stat_value: 870 },
//       { stat_name: "방어력", stat_value: 4948 },
//       { stat_name: "파괴시 방어력", stat_value: 4453 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 44 },
//     ],
//   },
//   {
//     name: "전설 와드네 메일",
//     restrictions: [
//       "120 레벨 이상",
//       "방어구 마스터리 5랭크 이상",
//       "최대 품질 5성",
//     ],
//     color: false,
//     quality: 2,
//     quality_selection_available: true,
//     rating: "전설",
//     category: ["플레이트", "가슴 방어구"],
//     set: "와드네",

//     stats: [
//       { stat_name: "추가피해", stat_value: 900 },
//       { stat_name: "방어력", stat_value: 5058 },
//       { stat_name: "파괴시 방어력", stat_value: 4552 },
//       { stat_name: "힘", stat_value: 225 },
//       { stat_name: "민첩", stat_value: 113 },
//       { stat_name: "지능", stat_value: 304 },
//       { stat_name: "의지", stat_value: 100 },
//       { stat_name: "최대 생명력", stat_value: 500 },
//       { stat_name: "크리티컬 저항", stat_value: 44 },
//     ],
//   },
// ];
