import { ItemType } from '@/app/_type/infoInfoType';

export const wrist_list: ItemType[] = [
  {
    name: '미지의 황금 팔찌',
    restrictions: ['90 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    grinding: false,
    description: `최대 4개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
  {
    name: '미지의 황금 팔찌 (증정)',
    restrictions: ['90 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '레어',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    grinding: false,
    description: `최대 4개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
  {
    name: '미지의 순은 팔찌',
    restrictions: ['85 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '고급',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    description: `최대 3개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
  {
    name: '미지의 순은 팔찌 (증정)',
    restrictions: ['85 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '고급',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    description: `최대 3개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
  {
    name: '미지의 구리 팔찌 (증정)',
    restrictions: ['83 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '중급',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    description: `최대 2개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
  {
    name: '미지의 구리 팔찌',
    restrictions: ['83 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '중급',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    description: `최대 2개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
  {
    name: '미지의 가죽 팔찌',
    restrictions: ['80 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '초급',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    description: `최대 1개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
  {
    name: '미지의 가죽 팔찌 (증정)',
    restrictions: ['80 레벨 이상'],
    color: false,
    quality: 2,
    quality_selection_available: true,
    rating: '초급',
    category: ['액세서리', '팔찌'],
    slot: 'wrist',
    description: `최대 1개의 팔찌 보석과 결합할 수 있는 미지의 힘이 담긴 팔찌. 콜헨 잡화점에서 팔찌 보석을 결합하거나 교체할 수 있다.`,
  },
];
