export const prefix_enchant_options = [
  {
    rank: "4",
    stat_name: "복수의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "550" },
      { stat_name: "마법공격력", stat_value: "550" },
      { stat_name: "공격속도", stat_value: "8" },
      { stat_name: "크리티컬", stat_value: "6" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "5",
    stat_name: "잔혹한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "430" },
      { stat_name: "마법공격력", stat_value: "430" },
      { stat_name: "공격속도", stat_value: "8" },
      { stat_name: "크리티컬", stat_value: "4" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "6",
    stat_name: "혼돈의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "340" },
      { stat_name: "마법공격력", stat_value: "340" },
      { stat_name: "공격속도", stat_value: "4" },
      { stat_name: "크리티컬", stat_value: "9" },
      { stat_name: "크리티컬 저항", stat_value: "-4" },
    ],
  },
  {
    rank: "7",
    stat_name: "불의의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "220" },
      { stat_name: "마법공격력", stat_value: "220" },
      { stat_name: "공격속도", stat_value: "4" },
      { stat_name: "크리티컬", stat_value: "8" },
      { stat_name: "크리티컬 저항", stat_value: "-5" },
    ],
  },
  {
    rank: "7",
    stat_name: "정의로운",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "430" },
      { stat_name: "마법공격력", stat_value: "430" },
      { stat_name: "공격속도", stat_value: "8" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "8",
    stat_name: "확고한",
    description: "",
    stat_value: [
      { stat_name: "공격속도", stat_value: "4" },
      { stat_name: "밸런스", stat_value: "5" },
    ],
  },
  {
    rank: "8",
    stat_name: "표범의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-240" },
      { stat_name: "마법공격력", stat_value: "-240" },
      { stat_name: "공격속도", stat_value: "8" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "8",
    stat_name: "풍요로운",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "120" },
      { stat_name: "마법공격력", stat_value: "120" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "밸런스", stat_value: "1" },
    ],
  },
  {
    rank: "9",
    stat_name: "빛과 같은",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "180" },
      { stat_name: "마법공격력", stat_value: "180" },
      { stat_name: "공격속도", stat_value: "3" },
    ],
  },
  {
    rank: "9",
    stat_name: "결정적인",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "120" },
      { stat_name: "마법공격력", stat_value: "120" },
      { stat_name: "크리티컬", stat_value: "3" },
      { stat_name: "밸런스", stat_value: "1" },
    ],
  },
  {
    rank: "A",
    stat_name: "용감한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "110" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "A",
    stat_name: "고풍스러운",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "320" },
      { stat_name: "마법공격력", stat_value: "320" },
    ],
  },
  {
    rank: "A",
    stat_name: "수호의",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "112" },
      { stat_name: "최대 생명력", stat_value: "50" },
    ],
  },
  {
    rank: "9",
    stat_name: "노력의",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "35" },
      { stat_name: "최대 생명력", stat_value: "50" },
      { stat_name: "공격속도", stat_value: "1" },
    ],
  },
  {
    rank: "8",
    stat_name: "균형 잡힌",
    description: "",
    stat_value: [
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "밸런스", stat_value: "1" },
    ],
  },
  {
    rank: "8",
    stat_name: "꾸준한",
    description: "",
    stat_value: [{ stat_name: "최대 스태미나", stat_value: "15" }],
  },
  {
    rank: "7",
    stat_name: "시간의",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "160" },
      { stat_name: "최대 생명력", stat_value: "50" },
      { stat_name: "최대 스태미나", stat_value: "5" },
      { stat_name: "크리티컬", stat_value: "4" },
      { stat_name: "크리티컬 저항", stat_value: "6" },
      { stat_name: "밸런스", stat_value: "-3" },
    ],
  },
  {
    rank: "6",
    stat_name: "무한의",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "160" },
      { stat_name: "최대 생명력", stat_value: "50" },
      { stat_name: "최대 스태미나", stat_value: "5" },
      { stat_name: "크리티컬", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "8" },
      { stat_name: "밸런스", stat_value: "-3" },
    ],
  },
  {
    rank: "5",
    stat_name: "고결한",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "160" },
      { stat_name: "최대 생명력", stat_value: "100" },
      { stat_name: "최대 스태미나", stat_value: "8" },
      { stat_name: "크리티컬", stat_value: "6" },
      { stat_name: "크리티컬 저항", stat_value: "10" },
      { stat_name: "밸런스", stat_value: "-3" },
    ],
  },
  {
    rank: "4",
    stat_name: "예언의",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "160" },
      { stat_name: "최대 생명력", stat_value: "100" },
      { stat_name: "최대 스태미나", stat_value: "8" },
      { stat_name: "크리티컬", stat_value: "7" },
      { stat_name: "크리티컬 저항", stat_value: "12" },
      { stat_name: "밸런스", stat_value: "-3" },
    ],
  },
  {
    rank: "7",
    stat_name: "기억하는",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "245" },
      { stat_name: "마법공격력", stat_value: "245" },
      { stat_name: "방어력", stat_value: "100" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "2" },
      { stat_name: "밸런스", stat_value: "1" },
    ],
  },
  {
    rank: "6",
    stat_name: "냉정의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "245" },
      { stat_name: "마법공격력", stat_value: "245" },
      { stat_name: "방어력", stat_value: "200" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "4" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "5",
    stat_name: "냉철의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "245" },
      { stat_name: "마법공격력", stat_value: "245" },
      { stat_name: "방어력", stat_value: "200" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "3" },
      { stat_name: "크리티컬 저항", stat_value: "6" },
      { stat_name: "밸런스", stat_value: "3" },
    ],
  },
  {
    rank: "4",
    stat_name: "잊혀진",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "245" },
      { stat_name: "마법공격력", stat_value: "245" },
      { stat_name: "방어력", stat_value: "200" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "3" },
      { stat_name: "크리티컬 저항", stat_value: "8" },
      { stat_name: "밸런스", stat_value: "4" },
    ],
  },
  {
    rank: "7",
    stat_name: "되뇌는",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "145" },
      { stat_name: "마법공격력", stat_value: "145" },
      { stat_name: "방어력", stat_value: "150" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "6",
    stat_name: "흐느끼는",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "145" },
      { stat_name: "마법공격력", stat_value: "145" },
      { stat_name: "방어력", stat_value: "300" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "밸런스", stat_value: "3" },
    ],
  },
  {
    rank: "5",
    stat_name: "비통한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "145" },
      { stat_name: "마법공격력", stat_value: "145" },
      { stat_name: "방어력", stat_value: "300" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "3" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "밸런스", stat_value: "4" },
    ],
  },
  {
    rank: "4",
    stat_name: "우아한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "145" },
      { stat_name: "마법공격력", stat_value: "145" },
      { stat_name: "방어력", stat_value: "300" },
      { stat_name: "공격속도", stat_value: "2" },
      { stat_name: "크리티컬", stat_value: "4" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "밸런스", stat_value: "5" },
    ],
  },
  {
    rank: "A",
    stat_name: "강인한",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "35" },
      { stat_name: "최대 스태미나", stat_value: "2" },
      { stat_name: "힘", stat_value: "9" },
      { stat_name: "지능", stat_value: "9" },
    ],
  },
  {
    rank: "9",
    stat_name: "호기심 많은",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "130" },
      { stat_name: "힘", stat_value: "6" },
      { stat_name: "지능", stat_value: "6" },
    ],
  },
  {
    rank: "8",
    stat_name: "의미있는",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "15" },
      { stat_name: "마법공격력", stat_value: "15" },
      { stat_name: "공격속도", stat_value: "1" },
    ],
  },
  {
    rank: "8",
    stat_name: "신속한",
    description: "",
    stat_value: [
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "-8" },
    ],
  },
  {
    rank: "6",
    stat_name: "뜻깊은",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "200" },
      { stat_name: "마법공격력", stat_value: "200" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "3" },
    ],
  },
  {
    rank: "5",
    stat_name: "뒤틀린",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "450" },
      { stat_name: "마법공격력", stat_value: "450" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
    ],
  },
  {
    rank: "8",
    stat_name: "반짝이는",
    description: "",
    stat_value: [
      { stat_name: "밸런스", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "-3" },
      { stat_name: "최대 생명력", stat_value: "-280" },
    ],
  },
  {
    rank: "7",
    stat_name: "죽은자의",
    description: "",
    stat_value: [
      { stat_name: "밸런스", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      { stat_name: "최대 생명력", stat_value: "-450" },
      { stat_name: "힘", stat_value: "-40" },
    ],
  },
  {
    rank: "5",
    stat_name: "추적자의",
    description: "",
    stat_value: [
      { stat_name: "밸런스", stat_value: "7" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      { stat_name: "최대 생명력", stat_value: "-450" },
    ],
  },
  {
    rank: "4",
    stat_name: "대적자의",
    description: "",
    stat_value: [
      { stat_name: "밸런스", stat_value: "9" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      { stat_name: "최대 생명력", stat_value: "-450" },
    ],
  },
  {
    rank: "8",
    stat_name: "조그만",
    description: "",
    stat_value: [
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "-3" },
    ],
  },
  {
    rank: "7",
    stat_name: "은은한",
    description: "",
    stat_value: [
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "-3" },
      { stat_name: "최대 스태미나", stat_value: "5" },
    ],
  },
  {
    rank: "5",
    stat_name: "강렬한",
    description: "",
    stat_value: [
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬", stat_value: "3" },
      { stat_name: "크리티컬 저항", stat_value: "-3" },
      { stat_name: "밸런스", stat_value: "1" },
      { stat_name: "최대 스태미나", stat_value: "5" },
    ],
  },
  {
    rank: "4",
    stat_name: "고대의",
    description: "110 레벨 이상 아이템",
    stat_value: [
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬", stat_value: "4" },
      { stat_name: "크리티컬 저항", stat_value: "-3" },
      { stat_name: "밸런스", stat_value: "2" },
      { stat_name: "최대 스태미나", stat_value: "5" },
    ],
  },
  {
    rank: "5",
    stat_name: "시공의",
    description: "110 레벨 이상 아이템",
    stat_value: [
      { stat_name: "공격력", stat_value: "450" },
      { stat_name: "마법공격력", stat_value: "450" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      { stat_name: "추가피해", stat_value: "100" },
    ],
  },
  {
    rank: "5",
    stat_name: "신중한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "7" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "일정 확률로 SP 회복", stat_value: "125" },
      { stat_name: "해제", stat_value: "50" },
    ],
  },
  {
    rank: "6",
    stat_name: "차분한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "4" },
      { stat_name: "밸런스", stat_value: "5" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "일정 확률로 SP 회복", stat_value: "125" },
    ],
  },
  {
    rank: "7",
    stat_name: "조용한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "3" },
      { stat_name: "밸런스", stat_value: "4" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "일정 확률로 SP 회복", stat_value: "125" },
    ],
  },
  {
    rank: "5",
    stat_name: "집중의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "7" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "매초 마나 회복", stat_value: "2" },
      { stat_name: "해제", stat_value: "50" },
    ],
  },
  {
    rank: "6",
    stat_name: "평온한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "4" },
      { stat_name: "밸런스", stat_value: "5" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "매초 마나 회복", stat_value: "2" },
    ],
  },
  {
    rank: "7",
    stat_name: "명상의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "3" },
      { stat_name: "밸런스", stat_value: "4" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "매초 마나 회복", stat_value: "2" },
    ],
  },
  {
    rank: "5",
    stat_name: "단호한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "7" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "높은 확률로 SP 회복", stat_value: "125" },
      { stat_name: "해제", stat_value: "50" },
    ],
  },
  {
    rank: "6",
    stat_name: "결연한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "4" },
      { stat_name: "밸런스", stat_value: "5" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "높은 확률로 SP 회복", stat_value: "125" },
    ],
  },
  {
    rank: "7",
    stat_name: "결심의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "-280" },
      { stat_name: "마법공격력", stat_value: "-280" },
      { stat_name: "공격속도", stat_value: "3" },
      { stat_name: "밸런스", stat_value: "4" },
      { stat_name: "고유 그룹", stat_value: "자원 회복" },
      { stat_name: "높은 확률로 SP 회복", stat_value: "125" },
    ],
  },
  {
    rank: "A",
    stat_name: "맷집 좋은",
    description: "방패, 캐스틀릿, 그랜드타지",
    stat_value: [{ stat_name: "방어력", stat_value: "190" }],
  },
  {
    rank: "A",
    stat_name: "현자의",
    description: "수호부",
    stat_value: [
      { stat_name: "민첩", stat_value: "-6" },
      { stat_name: "힘", stat_value: "15" },
      { stat_name: "지능", stat_value: "21" },
    ],
  },
  {
    rank: "9",
    stat_name: "짜릿한",
    description: "방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "방어력", stat_value: "145" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "-3" },
    ],
  },
  {
    rank: "7",
    stat_name: "산뜻한",
    description: "방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격력", stat_value: "55" },
      { stat_name: "마법공격력", stat_value: "55" },
      { stat_name: "공격속도", stat_value: "3" },
    ],
  },
  {
    rank: "7",
    stat_name: "봉인된",
    description: "",
    // description: "수호부, 방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "방어력", stat_value: "500" },
    ],
  },
  {
    rank: "5",
    stat_name: "격렬한",
    description: "",
    // description: "수호부, 방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "방어력", stat_value: "800" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "3" },
    ],
  },
  {
    rank: "4",
    stat_name: "승자의",
    description: "",
    // description: "수호부, 방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "방어력", stat_value: "800" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
    ],
  },

  {
    rank: "4",
    stat_name: "굳어버린",
    description: "주시자 아티팩트 전용",
    stat_value: [
      { stat_name: "공격력", stat_value: "450" },
      { stat_name: "마법공격력", stat_value: "450" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      {
        stat_name: "20초간 슈아, 받는 피해 30% 감소",
        stat_value: "",
      },
    ],
  },

  {
    rank: "4",
    stat_name: "꿰뚫는",
    description: "주시자 아티팩트 전용",
    stat_value: [
      { stat_name: "공격력", stat_value: "450" },
      { stat_name: "마법공격력", stat_value: "450" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      {
        stat_name: "20초간 크리티컬 피해량 15 증가",
        stat_value: "",
      },
    ],
  },
  {
    rank: "4",
    stat_name: "파괴하는",
    description: "주시자 아티팩트 전용",
    stat_value: [
      { stat_name: "공격력", stat_value: "450" },
      { stat_name: "마법공격력", stat_value: "450" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      {
        stat_name: "20초간 추가 피해 5% 증가",
        stat_value: "",
      },
    ],
  },
  {
    rank: "4",
    stat_name: "잦아든",
    description: "주시자 아티팩트 전용",
    stat_value: [
      { stat_name: "공격력", stat_value: "450" },
      { stat_name: "마법공격력", stat_value: "450" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      {
        stat_name: "20초간 대미지 일부 SP 전환",
        stat_value: "",
      },
    ],
  },
  {
    rank: "4",
    stat_name: "삼키는",
    description: "주시자 아티팩트 전용",
    stat_value: [
      { stat_name: "공격력", stat_value: "450" },
      { stat_name: "마법공격력", stat_value: "450" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      {
        stat_name: "20초간 추가 대미지 발생",
        stat_value: "",
      },
    ],
  },
];

export const suffix_enchant_options = [
  {
    rank: "A",
    stat_name: "약화",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "35" },
      { stat_name: "마법공격력", stat_value: "35" },
      { stat_name: "공격속도", stat_value: "1" },
    ],
  },
  {
    rank: "A",
    stat_name: "보호막",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "150" },
      { stat_name: "마법공격력", stat_value: "150" },
    ],
  },
  {
    rank: "9",
    stat_name: "야망",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "752" },
      { stat_name: "마법공격력", stat_value: "752" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "밸런스", stat_value: "-2" },
    ],
  },
  {
    rank: "9",
    stat_name: "도전",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "180" },
      { stat_name: "마법공격력", stat_value: "180" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "밸런스", stat_value: "1" },
    ],
  },
  {
    rank: "8",
    stat_name: "꽃잎",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "150" },
      { stat_name: "마법공격력", stat_value: "150" },
      { stat_name: "공격속도", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "3" },
    ],
  },
  {
    rank: "8",
    stat_name: "천벌",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "677" },
      { stat_name: "마법공격력", stat_value: "677" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬", stat_value: "2" },
    ],
  },
  {
    rank: "8",
    stat_name: "용맹",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "130" },
      { stat_name: "마법공격력", stat_value: "130" },
      { stat_name: "공격속도", stat_value: "4" },
      { stat_name: "밸런스", stat_value: "5" },
    ],
  },
  {
    rank: "7",
    stat_name: "단죄",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "680" },
      { stat_name: "마법공격력", stat_value: "680" },
      { stat_name: "크리티컬", stat_value: "6" },
    ],
  },
  {
    rank: "7",
    stat_name: "심판",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "870" },
      { stat_name: "마법공격력", stat_value: "870" },
      { stat_name: "공격속도", stat_value: "3" },
      { stat_name: "크리티컬", stat_value: "4" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "6",
    stat_name: "신념",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "970" },
      { stat_name: "마법공격력", stat_value: "970" },
      { stat_name: "공격속도", stat_value: "3" },
      { stat_name: "크리티컬", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "5",
    stat_name: "원한",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "1000" },
      { stat_name: "마법공격력", stat_value: "1000" },
      { stat_name: "공격속도", stat_value: "3" },
      { stat_name: "크리티컬", stat_value: "7" },
    ],
  },
  {
    rank: "4",
    stat_name: "일격",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "1030" },
      { stat_name: "마법공격력", stat_value: "1030" },
      { stat_name: "공격속도", stat_value: "3" },
      { stat_name: "크리티컬", stat_value: "10" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "A",
    stat_name: "치명",
    description: "",
    stat_value: [
      { stat_name: "크리티컬", stat_value: "3" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "A",
    stat_name: "용기",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "70" },
      { stat_name: "마법공격력", stat_value: "70" },
      { stat_name: "방어력", stat_value: "50" },
      { stat_name: "밸런스", stat_value: "1" },
    ],
  },
  {
    rank: "9",
    stat_name: "아르마딜로",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "336" },
      { stat_name: "최대 스태미나", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "1" },
      {
        stat_name: "확률로 크리티컬 저항(50%) 증가",
        stat_value: "",
      },
    ],
  },
  {
    rank: "9",
    stat_name: "자스민",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "140" },
      { stat_name: "마법공격력", stat_value: "140" },
      { stat_name: "방어력", stat_value: "-28" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "8",
    stat_name: "열의",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "282" },
      { stat_name: "마법공격력", stat_value: "282" },
      { stat_name: "방어력", stat_value: "-370" },
      { stat_name: "밸런스", stat_value: "5" },
    ],
  },
  {
    rank: "8",
    stat_name: "대항",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "340" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      {
        stat_name: "확률로 1초마다 생명력 회복(50)",
        stat_value: "",
      },
    ],
  },
  {
    rank: "8",
    stat_name: "낙엽",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "320" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "2" },
      { stat_name: "밸런스", stat_value: "1" },
    ],
  },
  {
    rank: "8",
    stat_name: "보호",
    description: "",
    stat_value: [
      { stat_name: "크리티컬", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "7",
    stat_name: "낙인",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "70" },
      { stat_name: "최대 스태미나", stat_value: "5" },
      { stat_name: "크리티컬", stat_value: "6" },
      { stat_name: "크리티컬 저항", stat_value: "7" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "6",
    stat_name: "결계",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "120" },
      { stat_name: "최대 스태미나", stat_value: "5" },
      { stat_name: "크리티컬", stat_value: "7" },
      { stat_name: "크리티컬 저항", stat_value: "8" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "5",
    stat_name: "한탄",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "120" },
      { stat_name: "최대 스태미나", stat_value: "5" },
      { stat_name: "크리티컬", stat_value: "9" },
      { stat_name: "크리티컬 저항", stat_value: "10" },
      { stat_name: "밸런스", stat_value: "-1" },
    ],
  },
  {
    rank: "7",
    stat_name: "원정",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "285" },
      { stat_name: "마법공격력", stat_value: "285" },
      { stat_name: "방어력", stat_value: "280" },
      { stat_name: "크리티컬", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "4" },
    ],
  },
  {
    rank: "6",
    stat_name: "포획",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "285" },
      { stat_name: "마법공격력", stat_value: "285" },
      { stat_name: "방어력", stat_value: "280" },
      { stat_name: "크리티컬", stat_value: "3" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
    ],
  },
  {
    rank: "5",
    stat_name: "진격",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "285" },
      { stat_name: "마법공격력", stat_value: "285" },
      { stat_name: "방어력", stat_value: "280" },
      { stat_name: "크리티컬", stat_value: "5" },
      { stat_name: "크리티컬 저항", stat_value: "7" },
    ],
  },
  {
    rank: "7",
    stat_name: "메아리",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "365" },
      { stat_name: "마법공격력", stat_value: "365" },
      { stat_name: "방어력", stat_value: "-260" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "2" },
      { stat_name: "밸런스", stat_value: "4" },
    ],
  },
  {
    rank: "6",
    stat_name: "영혼",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "465" },
      { stat_name: "마법공격력", stat_value: "465" },
      { stat_name: "방어력", stat_value: "-300" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "3" },
      { stat_name: "밸런스", stat_value: "5" },
    ],
  },
  {
    rank: "5",
    stat_name: "광분",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "465" },
      { stat_name: "마법공격력", stat_value: "465" },
      { stat_name: "방어력", stat_value: "-300" },
      { stat_name: "공격속도", stat_value: "1" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
      { stat_name: "밸런스", stat_value: "7" },
    ],
  },
  {
    rank: "4",
    stat_name: "투혼",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "285" },
      { stat_name: "마법공격력", stat_value: "285" },
      { stat_name: "방어력", stat_value: "280" },
      { stat_name: "크리티컬", stat_value: "8" },
      { stat_name: "크리티컬 저항", stat_value: "10" },
    ],
  },
  {
    rank: "A",
    stat_name: "고통",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "10" },
      { stat_name: "마법공격력", stat_value: "10" },
      { stat_name: "방어력", stat_value: "20" },
      { stat_name: "최대 생명력", stat_value: "-5" },
    ],
  },
  {
    rank: "9",
    stat_name: "활력",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "130" },
      { stat_name: "최대 생명력", stat_value: "12" },
    ],
  },
  {
    rank: "8",
    stat_name: "열망",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "200" },
      { stat_name: "최대 스태미나", stat_value: "2" },
    ],
  },
  {
    rank: "8",
    stat_name: "마음",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "30" },
      { stat_name: "마법공격력", stat_value: "30" },
      { stat_name: "스태미나 소량 회복 2단계", stat_value: "" },
    ],
  },
  {
    rank: "6",
    stat_name: "소망",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "300" },
      { stat_name: "최대 스태미나", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "1" },
    ],
  },
  {
    rank: "5",
    stat_name: "격노",
    description: "",
    stat_value: [
      { stat_name: "방어력", stat_value: "400" },
      { stat_name: "최대 스태미나", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "2" },
    ],
  },
  {
    rank: "5",
    stat_name: "신비",
    description: "",
    stat_value: [
      { stat_name: "공격력", stat_value: "200" },
      { stat_name: "마법공격력", stat_value: "200" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "밸런스", stat_value: "2" },
    ],
  },
  {
    rank: "5",
    stat_name: "돌진",
    description: "",
    stat_value: [
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "해제", stat_value: "100" },
      { stat_name: "고유 그룹", stat_value: "공격속도 증가" },
      { stat_name: "발동시 ", stat_value: "공격속도 증가" },
    ],
  },
  {
    rank: "6",
    stat_name: "질주",
    description: "",
    stat_value: [
      { stat_name: "고유 그룹", stat_value: "공격속도 증가" },
      { stat_name: "발동시", stat_value: "공격속도 증가" },
    ],
  },
  {
    rank: "7",
    stat_name: "산책",
    description: "",
    stat_value: [
      { stat_name: "크리티컬", stat_value: "-1" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "고유 그룹", stat_value: "공격속도 증가" },
      { stat_name: "발동시", stat_value: "공격속도 증가" },
    ],
  },
  {
    rank: "5",
    stat_name: "격돌",
    description: "",
    stat_value: [
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "해제", stat_value: "100" },
      { stat_name: "고유 그룹", stat_value: "공격속도 증가" },
      {
        stat_name: "발동시 (쿨 30초)",
        stat_value: "공격속도 증가",
      },
    ],
  },
  {
    rank: "6",
    stat_name: "폭렬",
    description: "",
    stat_value: [
      { stat_name: "고유 그룹", stat_value: "공격속도 증가" },
      {
        stat_name: "발동시 (쿨 30초)",
        stat_value: "공격속도 증가",
      },
    ],
  },
  {
    rank: "7",
    stat_name: "열렬",
    description: "",
    stat_value: [
      { stat_name: "크리티컬", stat_value: "-1" },
      { stat_name: "크리티컬 저항", stat_value: "-1" },
      { stat_name: "고유 그룹", stat_value: "공격속도 증가" },
      {
        stat_name: "발동시 (쿨 30초)",
        stat_value: "공격속도 증가",
      },
    ],
  },

  {
    rank: "A",
    stat_name: "코볼트",
    description: "방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격력", stat_value: "30" },
      { stat_name: "마법공격력", stat_value: "30" },
    ],
  },

  {
    rank: "A",
    stat_name: "장대비",
    description: "마법서",
    stat_value: [{ stat_name: "발동 시 마법공격력 증가", stat_value: "" }],
  },

  {
    rank: "9",
    stat_name: "금강석",
    description: "방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "방어력", stat_value: "62" },
      { stat_name: "최대 생명력", stat_value: "-50" },
      { stat_name: "크리티컬 저항", stat_value: "3" },
    ],
  },

  {
    rank: "7",
    stat_name: "진실",
    description: "",
    // description: "수호부, 방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격력", stat_value: "230" },
      { stat_name: "마법공격력", stat_value: "230" },
      { stat_name: "크리티컬 저항", stat_value: "5" },
    ],
  },

  {
    rank: "5",
    stat_name: "광기",
    description: "",
    // description: "수호부, 방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격력", stat_value: "230" },
      { stat_name: "마법공격력", stat_value: "230" },
      { stat_name: "크리티컬", stat_value: "2" },
      { stat_name: "크리티컬 저항", stat_value: "7" },
    ],
  },
  {
    rank: "4",
    stat_name: "찬미",
    description: "",
    // description: "수호부, 방패, 캐스틀릿, 그랜드타지",
    stat_value: [
      { stat_name: "공격력", stat_value: "230" },
      { stat_name: "마법공격력", stat_value: "230" },
      { stat_name: "크리티컬", stat_value: "4" },
      { stat_name: "크리티컬 저항", stat_value: "9" },
    ],
  },
];

export const prefix_enchant_name_list: { name: string[]; list: string[] }[] = [
  {
    name: ["Right Hand"],
    list: [
      "복수의",
      "잔혹한",
      "차분한",
      "혼돈의",
      "불의의",
      "정의로운",
      "확고한",
      "표범의",
      "풍요로운",
      "빛과 같은",
      "결정적인",
      "용감한",
      "고풍스러운",
    ],
  },
  {
    name: ["Left Hand"],
    list: [
      "맷집 좋은",
      "현자의",
      "짜릿한",
      "산뜻한",
      "봉인된",
      "격렬한",
      "승자의",
    ],
  },
  {
    name: ["Head", "Lower"],
    list: [
      "잊혀진",
      "냉철의",
      "냉정의",
      "기억하는",
      "균형 잡힌",
      "노력의",
      "수호의",
    ],
  },
  {
    name: ["Upper"],
    list: [
      "예언의",
      "고결한",
      "무한의",
      "시간의",
      "균형 잡힌",
      "꾸준한",
      "노력의",
      "수호의",
    ],
  },
  {
    name: ["Hand", "Leg"],
    list: [
      "우아한",
      "비통한",
      "흐느끼는",
      "되뇌는",
      "균형 잡힌",
      "노력의",
      "수호의",
    ],
  },
  {
    name: ["Right Finger", "Left Finger"],
    list: [
      "대적자의",
      "뒤틀린",
      "추적자의",
      "뜻깊은",
      "죽은자의",
      "반짝이는",
      "신속한",
      "의미있는",
      "호기심 많은",
      "강인한",
    ],
  },
  {
    name: ["Charm"],
    list: [
      "시공의",
      "뒤틀린",
      "뜻깊은",
      "의미있는",
      "신속한",
      "호기심 많은",
      "강인한",
    ],
  },
  {
    name: ["Earring", "Necklace"],
    list: ["뒤틀린", "뜻깊은", "의미있는", "신속한", "호기심 많은", "강인한"],
  },
  {
    name: ["Artifact"],
    list: [
      "굳어버린",
      "꿰뚫는",
      "파괴하는",
      "잦아든",
      "삼키는",
      "뒤틀린",
      "뜻깊은",
      "의미있는",
      "신속한",
      "호기심 많은",
      "강인한",
    ],
  },
  {
    name: ["Belt"],
    list: [
      "고대의",
      "강렬한",
      "뒤틀린",
      "뜻깊은",
      "은은한",
      "의미있는",
      "신속한",
      "조그만",
      "호기심 많은",
      "강인한",
    ],
  },

  {
    name: ["Rhod"],
    list: [
      "신중한",
      "집중의",
      "단호한",
      "결연한",
      "차분한",
      "평온한",
      "결심의",
      "조용한",
      "명상의",
    ],
  },
];

export const suffix_enchant_name_list: { name: string[]; list: string[] }[] = [
  {
    name: ["Right Hand"],
    list: [
      "일격",
      "원한",
      "신념",
      "단죄",
      "심판",
      "천벌",
      "용맹",
      "꽃잎",
      "야망",
      "도전",
      "보호막",
      "약화",
    ],
  },
  {
    name: ["Left Hand"],
    list: ["코볼트", "장대비", "금강석", "진실", "광기", "찬미"],
  },
  {
    name: ["Head", "Lower"],
    list: [
      "투혼",
      "진격",
      "질주",
      "포획",
      "원정",
      "열의",
      "대항",
      "낙엽",
      "아르마딜로",
      "자스민",
      "용기",
      "치명",
    ],
  },
  {
    name: ["Upper"],
    list: [
      "한탄",
      "결계",
      "질주",
      "낙인",
      "보호막",
      "열의",
      "대항",
      "낙엽",
      "자스민",
      "아르마딜로",
      "치명",
      "용기",
    ],
  },
  {
    name: ["Hand", "Leg"],
    list: [
      "광분",
      "질주",
      "영혼",
      "메아리",
      "대항",
      "열의",
      "낙엽",
      "자스민",
      "아르마딜로",
      "치명",
      "용기",
    ],
  },
  {
    name: ["Right Finger", "Left Finger", "Belt"],
    list: ["신비", "격노", "소망", "마음", "열망", "활력", "고통"],
  },
  {
    name: ["Earring", "Charm", "Necklace"],
    list: ["격노", "소망", "마음", "열망", "활력", "고통"],
  },
  {
    name: ["Artifact"],
    list: ["격노", "소망", "마음", "열망", "활력", "고통"],
  },
  {
    name: ["Rhod"],
    list: ["격돌", "돌진", "폭렬", "질주", "열렬", "산책"],
  },
];

export const left_hand_prefix_enchant_list = [
  { name: "맷집 좋은", item: ["방패", "캐스틀릿", "그랜드타지"] },
  { name: "현자의", item: ["수호부"] },
  { name: "짜릿한", item: ["방패", "캐스틀릿", "그랜드타지"] },
  { name: "산뜻한", item: ["방패", "캐스틀릿", "그랜드타지"] },
  { name: "봉인된", item: ["수호부", "방패", "캐스틀릿", "그랜드타지"] },
  { name: "격렬한", item: ["수호부", "방패", "캐스틀릿", "그랜드타지"] },
  { name: "승자의", item: ["수호부", "방패", "캐스틀릿", "그랜드타지"] },
];
export const left_hand_suffix_enchant_list = [
  { name: "코볼트", item: ["방패", "캐스틀릿", "그랜드타지"] },
  { name: "장대비", item: ["마법서"] },
  { name: "금강석", item: ["방패", "캐스틀릿", "그랜드타지"] },
  { name: "진실", item: ["수호부", "방패", "캐스틀릿", "그랜드타지"] },
  { name: "광기", item: ["수호부", "방패", "캐스틀릿", "그랜드타지"] },
  { name: "찬미", item: ["수호부", "방패", "캐스틀릿", "그랜드타지"] },
];
