type EnchantOptionsType = {
  rank: string;
  name: string;
  description: string;
  drop_item_list: string[];
  stat_value: { stat_name: string; stat_value: string }[];
};

export const prefix_enchant_options: EnchantOptionsType[] = [
  {
    rank: '4',
    name: '복수의',
    description: '',
    drop_item_list: ['로흘란의 바람'],
    stat_value: [
      { stat_name: '공격력', stat_value: '550' },
      { stat_name: '마법공격력', stat_value: '550' },
      { stat_name: '공격속도', stat_value: '8' },
      { stat_name: '크리티컬', stat_value: '6' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '5',
    name: '잔혹한',
    description: '',
    drop_item_list: ['으스름달 아래서', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '430' },
      { stat_name: '마법공격력', stat_value: '430' },
      { stat_name: '공격속도', stat_value: '8' },
      { stat_name: '크리티컬', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '6',
    name: '혼돈의',
    description: '',
    drop_item_list: ['급습', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '340' },
      { stat_name: '마법공격력', stat_value: '340' },
      { stat_name: '공격속도', stat_value: '4' },
      { stat_name: '크리티컬', stat_value: '9' },
      { stat_name: '크리티컬 저항', stat_value: '-4' },
    ],
  },
  {
    rank: '7',
    name: '불의의',
    description: '',
    drop_item_list: ['영혼의 부재', '실패와 대가', '통제', '왜곡된 진실'],
    stat_value: [
      { stat_name: '공격력', stat_value: '220' },
      { stat_name: '마법공격력', stat_value: '220' },
      { stat_name: '공격속도', stat_value: '4' },
      { stat_name: '크리티컬', stat_value: '8' },
      { stat_name: '크리티컬 저항', stat_value: '-5' },
    ],
  },
  {
    rank: '7',
    name: '정의로운',
    description: '',
    drop_item_list: ['영혼의 부재', '실패와 대가', '통제', '왜곡된 진실'],
    stat_value: [
      { stat_name: '공격력', stat_value: '430' },
      { stat_name: '마법공격력', stat_value: '430' },
      { stat_name: '공격속도', stat_value: '8' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '8',
    name: '확고한',
    description: '',
    drop_item_list: ['지하 도시', '끝없는 질문', '황폐한 모르반', '죽음의 신'],
    stat_value: [
      { stat_name: '공격속도', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '5' },
    ],
  },
  {
    rank: '8',
    name: '표범의',
    description: '',
    drop_item_list: ['지하 도시', '끝없는 질문', '황폐한 모르반', '죽음의 신'],
    stat_value: [
      { stat_name: '공격력', stat_value: '-240' },
      { stat_name: '마법공격력', stat_value: '-240' },
      { stat_name: '공격속도', stat_value: '8' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '8',
    name: '풍요로운',
    description: '',
    drop_item_list: ['지하 도시', '끝없는 질문', '황폐한 모르반', '죽음의 신'],
    stat_value: [
      { stat_name: '공격력', stat_value: '120' },
      { stat_name: '마법공격력', stat_value: '120' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '밸런스', stat_value: '1' },
    ],
  },
  {
    rank: '9',
    name: '빛과 같은',
    description: '',
    drop_item_list: ['바다의 악마'],
    stat_value: [
      { stat_name: '공격력', stat_value: '180' },
      { stat_name: '마법공격력', stat_value: '180' },
      { stat_name: '공격속도', stat_value: '3' },
    ],
  },
  {
    rank: '9',
    name: '결정적인',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '120' },
      { stat_name: '마법공격력', stat_value: '120' },
      { stat_name: '크리티컬', stat_value: '3' },
      { stat_name: '밸런스', stat_value: '1' },
    ],
  },
  {
    rank: 'A',
    name: '용감한',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '110' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: 'A',
    name: '고풍스러운',
    description: '',
    drop_item_list: [], // 추격
    stat_value: [
      { stat_name: '공격력', stat_value: '320' },
      { stat_name: '마법공격력', stat_value: '320' },
    ],
  },
  {
    rank: 'A',
    name: '수호의',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '방어력', stat_value: '112' },
      { stat_name: '최대 생명력', stat_value: '50' },
    ],
  },
  {
    rank: '9',
    name: '노력의',
    description: '',
    drop_item_list: ['바다의 악마'],
    stat_value: [
      { stat_name: '방어력', stat_value: '35' },
      { stat_name: '최대 생명력', stat_value: '50' },
      { stat_name: '공격속도', stat_value: '1' },
    ],
  },
  {
    rank: '8',
    name: '균형 잡힌',
    description: '',
    drop_item_list: [
      '지배자의 안식처',
      '사막의 공주',
      '흘러간 기억',
      '죽음의 그림자',
      '황폐한 모르반',
      '죽음의 신',
    ],

    stat_value: [
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '밸런스', stat_value: '1' },
    ],
  },
  {
    rank: '8',
    name: '꾸준한',
    description: '',
    drop_item_list: [],
    stat_value: [{ stat_name: '최대 스태미나', stat_value: '15' }],
  },
  {
    rank: '7',
    name: '시간의',
    description: '',
    drop_item_list: ['영혼의 부재', '실패와 대가', '통제', '왜곡된 진실'],
    stat_value: [
      { stat_name: '방어력', stat_value: '160' },
      { stat_name: '최대 생명력', stat_value: '50' },
      { stat_name: '최대 스태미나', stat_value: '5' },
      { stat_name: '크리티컬', stat_value: '4' },
      { stat_name: '크리티컬 저항', stat_value: '6' },
      { stat_name: '밸런스', stat_value: '-3' },
    ],
  },
  {
    rank: '6',
    name: '무한의',
    description: '',
    drop_item_list: ['광기의 무덤', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '방어력', stat_value: '160' },
      { stat_name: '최대 생명력', stat_value: '50' },
      { stat_name: '최대 스태미나', stat_value: '5' },
      { stat_name: '크리티컬', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '8' },
      { stat_name: '밸런스', stat_value: '-3' },
    ],
  },
  {
    rank: '5',
    name: '고결한',
    description: '',
    drop_item_list: ['어둠의 일족', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '방어력', stat_value: '160' },
      { stat_name: '최대 생명력', stat_value: '100' },
      { stat_name: '최대 스태미나', stat_value: '8' },
      { stat_name: '크리티컬', stat_value: '6' },
      { stat_name: '크리티컬 저항', stat_value: '10' },
      { stat_name: '밸런스', stat_value: '-3' },
    ],
  },
  {
    rank: '4',
    name: '예언의',
    description: '',
    drop_item_list: ['로흘란의 바람'],
    stat_value: [
      { stat_name: '방어력', stat_value: '160' },
      { stat_name: '최대 생명력', stat_value: '100' },
      { stat_name: '최대 스태미나', stat_value: '8' },
      { stat_name: '크리티컬', stat_value: '7' },
      { stat_name: '크리티컬 저항', stat_value: '12' },
      { stat_name: '밸런스', stat_value: '-3' },
    ],
  },
  {
    rank: '7',
    name: '기억하는',
    description: '',
    drop_item_list: ['영혼의 부재', '실패와 대가', '통제', '왜곡된 진실'],
    stat_value: [
      { stat_name: '공격력', stat_value: '245' },
      { stat_name: '마법공격력', stat_value: '245' },
      { stat_name: '방어력', stat_value: '100' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '2' },
      { stat_name: '밸런스', stat_value: '1' },
    ],
  },
  {
    rank: '6',
    name: '냉정의',
    description: '',
    drop_item_list: ['마신의 탑', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '245' },
      { stat_name: '마법공격력', stat_value: '245' },
      { stat_name: '방어력', stat_value: '200' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '5',
    name: '냉철의',
    description: '',
    drop_item_list: ['로체스트 공방전', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '245' },
      { stat_name: '마법공격력', stat_value: '245' },
      { stat_name: '방어력', stat_value: '200' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '3' },
      { stat_name: '크리티컬 저항', stat_value: '6' },
      { stat_name: '밸런스', stat_value: '3' },
    ],
  },
  {
    rank: '4',
    name: '잊혀진',
    description: '',
    drop_item_list: ['창조와 파괴의 성소'],
    stat_value: [
      { stat_name: '공격력', stat_value: '245' },
      { stat_name: '마법공격력', stat_value: '245' },
      { stat_name: '방어력', stat_value: '200' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '3' },
      { stat_name: '크리티컬 저항', stat_value: '8' },
      { stat_name: '밸런스', stat_value: '4' },
    ],
  },
  {
    rank: '7',
    name: '되뇌는',
    description: '',
    drop_item_list: ['영혼의 부재', '실패와 대가', '통제', '왜곡된 진실'],
    stat_value: [
      { stat_name: '공격력', stat_value: '145' },
      { stat_name: '마법공격력', stat_value: '145' },
      { stat_name: '방어력', stat_value: '150' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '6',
    name: '흐느끼는',
    description: '',
    drop_item_list: ['이웨카의 몽마', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '145' },
      { stat_name: '마법공격력', stat_value: '145' },
      { stat_name: '방어력', stat_value: '300' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '밸런스', stat_value: '3' },
    ],
  },
  {
    rank: '5',
    name: '비통한',
    description: '',
    drop_item_list: ['라다톤 대교', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '145' },
      { stat_name: '마법공격력', stat_value: '145' },
      { stat_name: '방어력', stat_value: '300' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '3' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '밸런스', stat_value: '4' },
    ],
  },
  {
    rank: '4',
    name: '우아한',
    description: '',
    drop_item_list: ['시드 별궁'],
    stat_value: [
      { stat_name: '공격력', stat_value: '145' },
      { stat_name: '마법공격력', stat_value: '145' },
      { stat_name: '방어력', stat_value: '300' },
      { stat_name: '공격속도', stat_value: '2' },
      { stat_name: '크리티컬', stat_value: '4' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '밸런스', stat_value: '5' },
    ],
  },
  {
    rank: 'A',
    name: '강인한',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '방어력', stat_value: '35' },
      { stat_name: '최대 스태미나', stat_value: '2' },
      { stat_name: '힘', stat_value: '9' },
      { stat_name: '지능', stat_value: '9' },
    ],
  },
  {
    rank: '9',
    name: '호기심 많은',
    description: '',
    drop_item_list: ['바다의 악마'],
    stat_value: [
      { stat_name: '방어력', stat_value: '130' },
      { stat_name: '힘', stat_value: '6' },
      { stat_name: '지능', stat_value: '6' },
    ],
  },
  {
    rank: '8',
    name: '의미있는',
    description: '',
    drop_item_list: [
      '바다의 악마',
      '사막의 공주',
      '흘러간 기억',
      '죽음의 그림자',
      '황폐한 모르반',
      '죽음의 신',
    ],

    stat_value: [
      { stat_name: '공격력', stat_value: '15' },
      { stat_name: '마법공격력', stat_value: '15' },
      { stat_name: '공격속도', stat_value: '1' },
    ],
  },
  {
    rank: '8',
    name: '신속한',
    description: '',
    drop_item_list: [
      '바다의 악마',
      '사막의 공주',
      '흘러간 기억',
      '죽음의 그림자',
      '황폐한 모르반',
      '죽음의 신',
    ],

    stat_value: [
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '-8' },
    ],
  },
  {
    rank: '6',
    name: '뜻깊은',
    description: '',
    drop_item_list: ['잊지 않기 위하여', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '200' },
      { stat_name: '마법공격력', stat_value: '200' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '3' },
    ],
  },
  {
    rank: '5',
    name: '뒤틀린',
    description: '',
    drop_item_list: ['위대한 사역'],
    stat_value: [
      { stat_name: '공격력', stat_value: '450' },
      { stat_name: '마법공격력', stat_value: '450' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
    ],
  },
  {
    rank: '8',
    name: '반짝이는',
    description: '',
    drop_item_list: [
      '사막의 공주',
      '흘러간 기억',
      '죽음의 그림자',
      '기이한 기계',
      '심연에서',
      '황폐한 모르반',
      '죽음의 신',
    ],
    stat_value: [
      { stat_name: '밸런스', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '-3' },
      { stat_name: '최대 생명력', stat_value: '-280' },
    ],
  },
  {
    rank: '7',
    name: '죽은자의',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '밸런스', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      { stat_name: '최대 생명력', stat_value: '-450' },
      { stat_name: '힘', stat_value: '-40' },
    ],
  },
  {
    rank: '5',
    name: '추적자의',
    description: '',
    drop_item_list: ['잊혀진 제단'],
    stat_value: [
      { stat_name: '밸런스', stat_value: '7' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      { stat_name: '최대 생명력', stat_value: '-450' },
    ],
  },
  {
    rank: '4',
    name: '대적자의',
    description: '',
    drop_item_list: ['검의 무덤'],
    stat_value: [
      { stat_name: '밸런스', stat_value: '9' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      { stat_name: '최대 생명력', stat_value: '-450' },
    ],
  },
  {
    rank: '8',
    name: '조그만',
    description: '',
    drop_item_list: ['기이한 기계', '심연에서', '황폐한 모르반', '불타는 신전'],

    stat_value: [
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '-3' },
    ],
  },
  {
    rank: '7',
    name: '은은한',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '-3' },
      { stat_name: '최대 스태미나', stat_value: '5' },
    ],
  },
  {
    rank: '5',
    name: '강렬한',
    description: '',
    drop_item_list: ['왕성 지하감옥'],
    stat_value: [
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬', stat_value: '3' },
      { stat_name: '크리티컬 저항', stat_value: '-3' },
      { stat_name: '밸런스', stat_value: '1' },
      { stat_name: '최대 스태미나', stat_value: '5' },
    ],
  },
  {
    rank: '4',
    name: '고대의',
    description: '110 레벨 이상 아이템',
    drop_item_list: ['창조와 파괴의 성소'],
    stat_value: [
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬', stat_value: '4' },
      { stat_name: '크리티컬 저항', stat_value: '-3' },
      { stat_name: '밸런스', stat_value: '2' },
      { stat_name: '최대 스태미나', stat_value: '5' },
    ],
  },
  {
    rank: '5',
    name: '시공의',
    description: '110 레벨 이상 아이템',
    drop_item_list: ['시공의 상자: 몰락한 기사의 전당'],
    stat_value: [
      { stat_name: '공격력', stat_value: '450' },
      { stat_name: '마법공격력', stat_value: '450' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      { stat_name: '추가피해', stat_value: '100' },
    ],
  },
  {
    rank: '5',
    name: '신중한',
    description: '',
    drop_item_list: ['시공의 상자: 몰락한 기사의 전당'],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '7' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '일정 확률로 SP 회복', stat_value: '125' },
      { stat_name: '해제', stat_value: '50' },
    ],
  },
  {
    rank: '6',
    name: '차분한',
    description: '',
    drop_item_list: [
      '시공의 상자: 찬탈자의 성채',
      '시공의 상자: 몰락한 기사의 전당',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '5' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '일정 확률로 SP 회복', stat_value: '125' },
    ],
  },
  {
    rank: '7',
    name: '조용한',
    description: '',
    drop_item_list: ['시공의 상자: 찬탈자의 성채'],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '3' },
      { stat_name: '밸런스', stat_value: '4' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '일정 확률로 SP 회복', stat_value: '125' },
    ],
  },
  {
    rank: '5',
    name: '집중의',
    description: '',
    drop_item_list: ['시공의 상자: 몰락한 기사의 전당'],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '7' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '매초 마나 회복', stat_value: '2' },
      { stat_name: '해제', stat_value: '50' },
    ],
  },
  {
    rank: '6',
    name: '평온한',
    description: '',
    drop_item_list: [
      '시공의 상자: 찬탈자의 성채',
      '시공의 상자: 몰락한 기사의 전당',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '5' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '매초 마나 회복', stat_value: '2' },
    ],
  },
  {
    rank: '7',
    name: '명상의',
    description: '',
    drop_item_list: ['시공의 상자: 찬탈자의 성채'],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '3' },
      { stat_name: '밸런스', stat_value: '4' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '매초 마나 회복', stat_value: '2' },
    ],
  },
  {
    rank: '5',
    name: '단호한',
    description: '',
    drop_item_list: ['시공의 상자: 몰락한 기사의 전당'],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '7' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '높은 확률로 SP 회복', stat_value: '125' },
      { stat_name: '해제', stat_value: '50' },
    ],
  },
  {
    rank: '6',
    name: '결연한',
    description: '',
    drop_item_list: [
      '시공의 상자: 찬탈자의 성채',
      '시공의 상자: 몰락한 기사의 전당',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '5' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '높은 확률로 SP 회복', stat_value: '125' },
    ],
  },
  {
    rank: '7',
    name: '결심의',
    description: '',
    drop_item_list: ['시공의 상자: 찬탈자의 성채'],
    stat_value: [
      { stat_name: '공격력', stat_value: '-280' },
      { stat_name: '마법공격력', stat_value: '-280' },
      { stat_name: '공격속도', stat_value: '3' },
      { stat_name: '밸런스', stat_value: '4' },
      { stat_name: '고유 그룹', stat_value: '자원 회복' },
      { stat_name: '높은 확률로 SP 회복', stat_value: '125' },
    ],
  },
  {
    rank: 'A',
    name: '맷집 좋은',
    description: '방패, 캐스틀릿, 그랜드타지',
    drop_item_list: [],
    stat_value: [{ stat_name: '방어력', stat_value: '190' }],
  },
  {
    rank: 'A',
    name: '현자의',
    description: '수호부',
    drop_item_list: [],
    stat_value: [
      { stat_name: '민첩', stat_value: '-6' },
      { stat_name: '힘', stat_value: '15' },
      { stat_name: '지능', stat_value: '21' },
    ],
  },
  {
    rank: '9',
    name: '짜릿한',
    description: '방패, 캐스틀릿, 그랜드타지',
    drop_item_list: ['바다의 악마'],
    stat_value: [
      { stat_name: '방어력', stat_value: '145' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '-3' },
    ],
  },
  {
    rank: '7',
    name: '산뜻한',
    description: '방패, 캐스틀릿, 그랜드타지',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '55' },
      { stat_name: '마법공격력', stat_value: '55' },
      { stat_name: '공격속도', stat_value: '3' },
    ],
  },
  {
    rank: '7',
    name: '봉인된',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '방어력', stat_value: '500' },
    ],
  },
  {
    rank: '5',
    name: '격렬한',
    description: '',
    drop_item_list: ['실낙원의 첨병'],
    stat_value: [
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '방어력', stat_value: '800' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '3' },
    ],
  },
  {
    rank: '4',
    name: '승자의',
    description: '',
    drop_item_list: ['검의 무덤'],
    stat_value: [
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '방어력', stat_value: '800' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
    ],
  },

  {
    rank: '4',
    name: '굳어버린',
    description: '주시자 아티팩트',
    drop_item_list: ['시공의 상자: 주시자의 신전'],
    stat_value: [
      { stat_name: '공격력', stat_value: '450' },
      { stat_name: '마법공격력', stat_value: '450' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      {
        stat_name: '20초간 슈아, 받는 피해 30% 감소',
        stat_value: '',
      },
    ],
  },

  {
    rank: '4',
    name: '꿰뚫는',
    description: '주시자 아티팩트',
    drop_item_list: ['시공의 상자: 주시자의 신전'],
    stat_value: [
      { stat_name: '공격력', stat_value: '450' },
      { stat_name: '마법공격력', stat_value: '450' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      {
        stat_name: '20초간 크리티컬 피해량 15 증가',
        stat_value: '',
      },
    ],
  },
  {
    rank: '4',
    name: '파괴하는',
    description: '주시자 아티팩트',
    drop_item_list: ['시공의 상자: 주시자의 신전'],
    stat_value: [
      { stat_name: '공격력', stat_value: '450' },
      { stat_name: '마법공격력', stat_value: '450' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      {
        stat_name: '20초간 추가 피해 5% 증가',
        stat_value: '',
      },
    ],
  },
  {
    rank: '4',
    name: '잦아든',
    description: '주시자 아티팩트',
    drop_item_list: ['시공의 상자: 주시자의 신전'],
    stat_value: [
      { stat_name: '공격력', stat_value: '450' },
      { stat_name: '마법공격력', stat_value: '450' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      {
        stat_name: '20초간 대미지 일부 SP 전환',
        stat_value: '',
      },
    ],
  },
  {
    rank: '4',
    name: '삼키는',
    description: '주시자 아티팩트',
    drop_item_list: ['시공의 상자: 주시자의 신전'],
    stat_value: [
      { stat_name: '공격력', stat_value: '450' },
      { stat_name: '마법공격력', stat_value: '450' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      {
        stat_name: '20초간 추가 대미지 발생',
        stat_value: '',
      },
    ],
  },
  {
    rank: '3',
    name: '비극의',
    description: '',
    drop_item_list: ['정의를 망각한 대성당'],
    stat_value: [
      { stat_name: '공격력', stat_value: '700' },
      { stat_name: '마법공격력', stat_value: '700' },
      { stat_name: '공격속도', stat_value: '8' },
      { stat_name: '크리티컬', stat_value: '8' },
      { stat_name: '밸런스', stat_value: '4' },
    ],
  },
  {
    rank: '4',
    name: '감춰진',
    description: '',
    drop_item_list: ['따를 수 없는 예언'],
    stat_value: [
      { stat_name: '공격력', stat_value: '700' },
      { stat_name: '마법공격력', stat_value: '700' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '7' },
    ],
  },
];

export const suffix_enchant_options: EnchantOptionsType[] = [
  {
    rank: 'A',
    name: '약화',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '35' },
      { stat_name: '마법공격력', stat_value: '35' },
      { stat_name: '공격속도', stat_value: '1' },
    ],
  },
  {
    rank: 'A',
    name: '보호막',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '150' },
      { stat_name: '마법공격력', stat_value: '150' },
    ],
  },
  {
    rank: '9',
    name: '야망',
    description: '',
    drop_item_list: ['흘러간 기억'],
    stat_value: [
      { stat_name: '공격력', stat_value: '752' },
      { stat_name: '마법공격력', stat_value: '752' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '밸런스', stat_value: '-2' },
    ],
  },
  {
    rank: '9',
    name: '도전',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '180' },
      { stat_name: '마법공격력', stat_value: '180' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '밸런스', stat_value: '1' },
    ],
  },
  {
    rank: '8',
    name: '꽃잎',
    description: '',
    drop_item_list: [
      '기이한 기계',
      '심연에서',
      '저승을 지키는 문지기',
      '불타는 신전',
    ],

    stat_value: [
      { stat_name: '공격력', stat_value: '150' },
      { stat_name: '마법공격력', stat_value: '150' },
      { stat_name: '공격속도', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '3' },
    ],
  },
  {
    rank: '8',
    name: '천벌',
    description: '',
    drop_item_list: [
      '기이한 기계',
      '심연에서',
      '저승을 지키는 문지기',
      '불타는 신전',
    ],

    stat_value: [
      { stat_name: '공격력', stat_value: '677' },
      { stat_name: '마법공격력', stat_value: '677' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬', stat_value: '2' },
    ],
  },
  {
    rank: '8',
    name: '용맹',
    description: '',
    drop_item_list: [
      '기이한 기계',
      '심연에서',
      '저승을 지키는 문지기',
      '불타는 신전',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '130' },
      { stat_name: '마법공격력', stat_value: '130' },
      { stat_name: '공격속도', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '5' },
    ],
  },
  {
    rank: '7',
    name: '단죄',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '680' },
      { stat_name: '마법공격력', stat_value: '680' },
      { stat_name: '크리티컬', stat_value: '6' },
    ],
  },
  {
    rank: '7',
    name: '심판',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '870' },
      { stat_name: '마법공격력', stat_value: '870' },
      { stat_name: '공격속도', stat_value: '3' },
      { stat_name: '크리티컬', stat_value: '4' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: '6',
    name: '신념',
    description: '',
    drop_item_list: ['급습', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '970' },
      { stat_name: '마법공격력', stat_value: '970' },
      { stat_name: '공격속도', stat_value: '3' },
      { stat_name: '크리티컬', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: '5',
    name: '원한',
    description: '',
    drop_item_list: ['잊혀진 제단'],
    stat_value: [
      { stat_name: '공격력', stat_value: '1000' },
      { stat_name: '마법공격력', stat_value: '1000' },
      { stat_name: '공격속도', stat_value: '3' },
      { stat_name: '크리티컬', stat_value: '7' },
    ],
  },
  {
    rank: '4',
    name: '일격',
    description: '',
    drop_item_list: ['검의 무덤'],
    stat_value: [
      { stat_name: '공격력', stat_value: '1030' },
      { stat_name: '마법공격력', stat_value: '1030' },
      { stat_name: '공격속도', stat_value: '3' },
      { stat_name: '크리티컬', stat_value: '10' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: 'A',
    name: '치명',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '크리티컬', stat_value: '3' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: 'A',
    name: '용기',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '70' },
      { stat_name: '마법공격력', stat_value: '70' },
      { stat_name: '방어력', stat_value: '50' },
      { stat_name: '밸런스', stat_value: '1' },
    ],
  },
  {
    rank: '9',
    name: '아르마딜로',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '방어력', stat_value: '336' },
      { stat_name: '최대 스태미나', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '1' },
      {
        stat_name: '확률로 크리티컬 저항(50%) 증가',
        stat_value: '',
      },
    ],
  },
  {
    rank: '9',
    name: '자스민',
    description: '',
    drop_item_list: ['흘러간 기억'],
    stat_value: [
      { stat_name: '공격력', stat_value: '140' },
      { stat_name: '마법공격력', stat_value: '140' },
      { stat_name: '방어력', stat_value: '-28' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '8',
    name: '열의',
    description: '',
    drop_item_list: ['지배자의 안식처', '저승을 지키는 문지기', '불타는 신전'],

    stat_value: [
      { stat_name: '공격력', stat_value: '282' },
      { stat_name: '마법공격력', stat_value: '282' },
      { stat_name: '방어력', stat_value: '-370' },
      { stat_name: '밸런스', stat_value: '5' },
    ],
  },
  {
    rank: '8',
    name: '대항',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '방어력', stat_value: '340' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      {
        stat_name: '확률로 1초마다 생명력 회복(50)',
        stat_value: '',
      },
    ],
  },
  {
    rank: '8',
    name: '낙엽',
    description: '',
    drop_item_list: [
      '지배자의 안식처',
      '지하 도시',
      '끝없는 질문',
      '저승을 지키는 문지기',
      '불타는 신전',
    ],

    stat_value: [
      { stat_name: '방어력', stat_value: '320' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '2' },
      { stat_name: '밸런스', stat_value: '1' },
    ],
  },
  {
    rank: '8',
    name: '보호',
    description: '',
    drop_item_list: ['저승을 지키는 문지기', '불타는 신전'],
    stat_value: [
      { stat_name: '크리티컬', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: '7',
    name: '낙인',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '방어력', stat_value: '70' },
      { stat_name: '최대 스태미나', stat_value: '5' },
      { stat_name: '크리티컬', stat_value: '6' },
      { stat_name: '크리티컬 저항', stat_value: '7' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: '6',
    name: '결계',
    description: '',
    drop_item_list: ['광휘의 루', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '방어력', stat_value: '120' },
      { stat_name: '최대 스태미나', stat_value: '5' },
      { stat_name: '크리티컬', stat_value: '7' },
      { stat_name: '크리티컬 저항', stat_value: '8' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: '5',
    name: '한탄',
    description: '',
    drop_item_list: ['죽음의 변증법'],
    stat_value: [
      { stat_name: '방어력', stat_value: '120' },
      { stat_name: '최대 스태미나', stat_value: '5' },
      { stat_name: '크리티컬', stat_value: '9' },
      { stat_name: '크리티컬 저항', stat_value: '10' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: '7',
    name: '원정',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '285' },
      { stat_name: '마법공격력', stat_value: '285' },
      { stat_name: '방어력', stat_value: '280' },
      { stat_name: '크리티컬', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '4' },
    ],
  },
  {
    rank: '6',
    name: '포획',
    description: '',
    drop_item_list: ['붉은 낙인', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '285' },
      { stat_name: '마법공격력', stat_value: '285' },
      { stat_name: '방어력', stat_value: '280' },
      { stat_name: '크리티컬', stat_value: '3' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
    ],
  },
  {
    rank: '5',
    name: '진격',
    description: '',
    drop_item_list: ['왕성 토파즈 홀'],
    stat_value: [
      { stat_name: '공격력', stat_value: '285' },
      { stat_name: '마법공격력', stat_value: '285' },
      { stat_name: '방어력', stat_value: '280' },
      { stat_name: '크리티컬', stat_value: '5' },
      { stat_name: '크리티컬 저항', stat_value: '7' },
    ],
  },
  {
    rank: '7',
    name: '메아리',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '365' },
      { stat_name: '마법공격력', stat_value: '365' },
      { stat_name: '방어력', stat_value: '-260' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '2' },
      { stat_name: '밸런스', stat_value: '4' },
    ],
  },
  {
    rank: '6',
    name: '영혼',
    description: '',
    drop_item_list: ['지저의 실험실', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '465' },
      { stat_name: '마법공격력', stat_value: '465' },
      { stat_name: '방어력', stat_value: '-300' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '3' },
      { stat_name: '밸런스', stat_value: '5' },
    ],
  },
  {
    rank: '5',
    name: '광분',
    description: '',
    drop_item_list: ['원한의 암굴'],
    stat_value: [
      { stat_name: '공격력', stat_value: '465' },
      { stat_name: '마법공격력', stat_value: '465' },
      { stat_name: '방어력', stat_value: '-300' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
      { stat_name: '밸런스', stat_value: '7' },
    ],
  },
  {
    rank: '4',
    name: '투혼',
    description: '',
    drop_item_list: ['제단을 지키는 자'],
    stat_value: [
      { stat_name: '공격력', stat_value: '285' },
      { stat_name: '마법공격력', stat_value: '285' },
      { stat_name: '방어력', stat_value: '280' },
      { stat_name: '크리티컬', stat_value: '8' },
      { stat_name: '크리티컬 저항', stat_value: '10' },
    ],
  },
  {
    rank: 'A',
    name: '고통',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '10' },
      { stat_name: '마법공격력', stat_value: '10' },
      { stat_name: '방어력', stat_value: '20' },
      { stat_name: '최대 생명력', stat_value: '-5' },
    ],
  },
  {
    rank: '9',
    name: '활력',
    description: '',
    drop_item_list: [],
    stat_value: [
      { stat_name: '방어력', stat_value: '130' },
      { stat_name: '최대 생명력', stat_value: '12' },
    ],
  },
  {
    rank: '8',
    name: '열망',
    description: '',
    drop_item_list: ['바다의 악마', '저승을 지키는 문지기', '불타는 신전'],
    stat_value: [
      { stat_name: '방어력', stat_value: '200' },
      { stat_name: '최대 스태미나', stat_value: '2' },
    ],
  },
  {
    rank: '8',
    name: '마음',
    description: '',
    drop_item_list: ['바다의 악마', '저승을 지키는 문지기', '불타는 신전'],
    stat_value: [
      { stat_name: '공격력', stat_value: '30' },
      { stat_name: '마법공격력', stat_value: '30' },
      { stat_name: '고유 그룹', stat_value: '스태미나 회복' },
      { stat_name: '스태미나 소량 회복 2단계', stat_value: '' },
    ],
  },
  {
    rank: '6',
    name: '소망',
    description: '',
    drop_item_list: ['잊지 않기 위하여', '스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '방어력', stat_value: '300' },
      { stat_name: '최대 스태미나', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '1' },
    ],
  },
  {
    rank: '5',
    name: '격노',
    description: '',
    drop_item_list: ['죽음의 변증법'],
    stat_value: [
      { stat_name: '방어력', stat_value: '400' },
      { stat_name: '최대 스태미나', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '2' },
    ],
  },
  {
    rank: '5',
    name: '신비',
    description: '',
    drop_item_list: ['스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '200' },
      { stat_name: '마법공격력', stat_value: '200' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '밸런스', stat_value: '2' },
    ],
  },
  {
    rank: '5',
    name: '돌진',
    description: '',
    drop_item_list: ['시공의 상자: 몰락한 기사의 전당'],
    stat_value: [
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '해제', stat_value: '100' },
      { stat_name: '고유 그룹', stat_value: '공격속도 증가' },
      { stat_name: '발동시 공격속도 증가', stat_value: '' },
    ],
  },
  {
    rank: '6',
    name: '질주',
    description: '',
    drop_item_list: [
      '시공의 상자: 찬탈자의 성채',
      '시공의 상자: 몰락한 기사의 전당',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '고유 그룹', stat_value: '공격속도 증가' },
      { stat_name: '발동시 공격속도 증가', stat_value: '' },
    ],
  },
  {
    rank: '7',
    name: '산책',
    description: '',
    drop_item_list: ['시공의 상자: 찬탈자의 성채'],
    stat_value: [
      { stat_name: '크리티컬', stat_value: '-1' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '고유 그룹', stat_value: '공격속도 증가' },
      { stat_name: '발동시 공격속도 증가', stat_value: '' },
    ],
  },
  {
    rank: '5',
    name: '격돌',
    description: '',
    drop_item_list: ['시공의 상자: 몰락한 기사의 전당'],
    stat_value: [
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '해제', stat_value: '100' },
      { stat_name: '고유 그룹', stat_value: '공격속도 증가' },
      {
        stat_name: '발동시 (쿨 30초) 공격속도 증가',
        stat_value: '',
      },
    ],
  },
  {
    rank: '6',
    name: '폭렬',
    description: '',
    drop_item_list: [
      '시공의 상자: 찬탈자의 성채',
      '시공의 상자: 몰락한 기사의 전당',
    ],
    stat_value: [
      { stat_name: '고유 그룹', stat_value: '공격속도 증가' },
      {
        stat_name: '발동시 (쿨 30초) 공격속도 증가',
        stat_value: '',
      },
    ],
  },
  {
    rank: '7',
    name: '열렬',
    description: '',
    drop_item_list: ['시공의 상자: 찬탈자의 성채'],
    stat_value: [
      { stat_name: '크리티컬', stat_value: '-1' },
      { stat_name: '크리티컬 저항', stat_value: '-1' },
      { stat_name: '고유 그룹', stat_value: '공격속도 증가' },
      {
        stat_name: '발동시 (쿨 30초) 공격속도 증가',
        stat_value: '',
      },
    ],
  },

  {
    rank: 'A',
    name: '코볼트',
    description: '방패, 캐스틀릿, 그랜드타지',
    drop_item_list: [],
    stat_value: [
      { stat_name: '공격력', stat_value: '30' },
      { stat_name: '마법공격력', stat_value: '30' },
    ],
  },

  {
    rank: 'A',
    name: '장대비',
    description: '마법서',
    drop_item_list: [],
    stat_value: [{ stat_name: '발동 시 마법공격력 증가', stat_value: '' }],
  },

  {
    rank: '9',
    name: '금강석',
    description: '방패, 캐스틀릿, 그랜드타지',
    drop_item_list: [],
    stat_value: [
      { stat_name: '방어력', stat_value: '62' },
      { stat_name: '최대 생명력', stat_value: '-50' },
      { stat_name: '크리티컬 저항', stat_value: '3' },
    ],
  },

  {
    rank: '7',
    name: '진실',
    description: '',
    drop_item_list: [
      '영혼의 부재',
      '실패와 대가',
      '통제',
      '왜곡된 진실',
      '스페셜 던전: 인챈트 주머니',
    ],
    stat_value: [
      { stat_name: '공격력', stat_value: '230' },
      { stat_name: '마법공격력', stat_value: '230' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
    ],
  },

  {
    rank: '5',
    name: '광기',
    description: '',
    drop_item_list: ['원한의 암굴'],
    stat_value: [
      { stat_name: '공격력', stat_value: '230' },
      { stat_name: '마법공격력', stat_value: '230' },
      { stat_name: '크리티컬', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '7' },
    ],
  },
  {
    rank: '4',
    name: '찬미',
    description: '',
    drop_item_list: ['시드 별궁'],
    stat_value: [
      { stat_name: '공격력', stat_value: '230' },
      { stat_name: '마법공격력', stat_value: '230' },
      { stat_name: '크리티컬', stat_value: '4' },
      { stat_name: '크리티컬 저항', stat_value: '9' },
    ],
  },
  {
    rank: '4',
    name: '물결',
    description: '110 레벨 이상 아이템',
    drop_item_list: ['스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '300' },
      { stat_name: '마법공격력', stat_value: '300' },
      { stat_name: '크리티컬 저항', stat_value: '3' },
      { stat_name: '고유 그룹', stat_value: '스태미나 회복' },
      { stat_name: '스태미나 소량 회복 3단계', stat_value: '' },
    ],
  },
  {
    rank: '4',
    name: '사념',
    description: '110 레벨 이상 아이템',
    drop_item_list: ['그릇된 고해'],
    stat_value: [
      { stat_name: '밸런스', stat_value: '1' },
      { stat_name: '방어력', stat_value: '500' },
      { stat_name: '최대 스태미나', stat_value: '2' },
      { stat_name: '크리티컬 저항', stat_value: '5' },
    ],
  },
  {
    rank: '4',
    name: '고독',
    description: '',
    drop_item_list: ['따를 수 없는 예언'],
    stat_value: [
      { stat_name: '공격력', stat_value: '465' },
      { stat_name: '마법공격력', stat_value: '465' },
      { stat_name: '방어력', stat_value: '-300' },
      { stat_name: '공격속도', stat_value: '1' },
      { stat_name: '크리티컬 저항', stat_value: '8' },
      { stat_name: '밸런스', stat_value: '10' },
    ],
  },
  {
    rank: '4',
    name: '시련',
    description: '',
    drop_item_list: ['탐욕의 연회장'],
    stat_value: [
      { stat_name: '방어력', stat_value: '120' },
      { stat_name: '스태미나', stat_value: '5' },
      { stat_name: '크리티컬', stat_value: '12' },
      { stat_name: '크리티컬 저항', stat_value: '13' },
      { stat_name: '밸런스', stat_value: '-1' },
    ],
  },
  {
    rank: '4',
    name: '운명',
    description: '',
    drop_item_list: ['스페셜 던전: 인챈트 주머니'],
    stat_value: [
      { stat_name: '공격력', stat_value: '400' },
      { stat_name: '마법 공격력', stat_value: '400' },
      { stat_name: '크리티컬', stat_value: '4' },
      { stat_name: '밸런스', stat_value: '4' },
    ],
  },
];

export const prefix_enchant_name_list: { name: string[]; list: string[] }[] = [
  {
    name: ['Right Hand'],
    list: [
      '비극의',
      '복수의',
      '잔혹한',
      '차분한',
      '혼돈의',
      '불의의',
      '정의로운',
      '확고한',
      '표범의',
      '풍요로운',
      '빛과 같은',
      '결정적인',
      '용감한',
      '고풍스러운',
    ],
  },
  {
    name: ['Left Hand'],
    list: [
      '맷집 좋은',
      '현자의',
      '짜릿한',
      '산뜻한',
      '봉인된',
      '격렬한',
      '승자의',
    ],
  },
  {
    name: ['Head', 'Lower'],
    list: [
      '잊혀진',
      '냉철의',
      '냉정의',
      '기억하는',
      '균형 잡힌',
      '노력의',
      '수호의',
    ],
  },
  {
    name: ['Upper'],
    list: [
      '예언의',
      '고결한',
      '무한의',
      '시간의',
      '균형 잡힌',
      '꾸준한',
      '노력의',
      '수호의',
      '보호',
    ],
  },
  {
    name: ['Hand', 'Leg'],
    list: [
      '우아한',
      '비통한',
      '흐느끼는',
      '되뇌는',
      '균형 잡힌',
      '노력의',
      '수호의',
    ],
  },
  {
    name: ['Right Finger', 'Left Finger'],
    list: [
      '대적자의',
      '감춰진',
      '뒤틀린',
      '추적자의',
      '뜻깊은',
      '죽은자의',
      '반짝이는',
      '신속한',
      '의미있는',
      '호기심 많은',
      '강인한',
    ],
  },
  {
    name: ['Charm'],
    list: [
      '시공의',
      '감춰진',
      '뒤틀린',
      '뜻깊은',
      '의미있는',
      '신속한',
      '호기심 많은',
      '강인한',
    ],
  },
  {
    name: ['Earring', 'Necklace'],
    list: [
      '감춰진',
      '뒤틀린',
      '뜻깊은',
      '의미있는',
      '신속한',
      '호기심 많은',
      '강인한',
    ],
  },
  {
    name: ['Artifact'],
    list: [
      '굳어버린',
      '꿰뚫는',
      '파괴하는',
      '잦아든',
      '삼키는',
      '감춰진',
      '뒤틀린',
      '뜻깊은',
      '의미있는',
      '신속한',
      '호기심 많은',
      '강인한',
    ],
  },
  {
    name: ['Belt'],
    list: [
      '고대의',
      '강렬한',
      '감춰진',
      '뒤틀린',
      '뜻깊은',
      '은은한',
      '의미있는',
      '신속한',
      '조그만',
      '호기심 많은',
      '강인한',
    ],
  },

  {
    name: ['Rhod'],
    list: [
      '신중한',
      '집중의',
      '단호한',
      '결연한',
      '차분한',
      '평온한',
      '결심의',
      '조용한',
      '명상의',
    ],
  },
];

export const suffix_enchant_name_list: { name: string[]; list: string[] }[] = [
  {
    name: ['Right Hand'],
    list: [
      '일격',
      '원한',
      '신념',
      '단죄',
      '심판',
      '천벌',
      '용맹',
      '꽃잎',
      '야망',
      '도전',
      '보호막',
      '약화',
    ],
  },
  {
    name: ['Left Hand'],
    list: ['코볼트', '장대비', '금강석', '진실', '광기', '찬미'],
  },
  {
    name: ['Head', 'Lower'],
    list: [
      '투혼',
      '진격',
      '질주',
      '포획',
      '원정',
      '열의',
      '대항',
      '낙엽',
      '아르마딜로',
      '자스민',
      '용기',
      '치명',
    ],
  },
  {
    name: ['Upper'],
    list: [
      '시련',
      '한탄',
      '결계',
      '질주',
      '낙인',
      '보호막',
      '열의',
      '대항',
      '낙엽',
      '자스민',
      '아르마딜로',
      '치명',
      '용기',
    ],
  },
  {
    name: ['Hand', 'Leg'],
    list: [
      '고독',
      '광분',
      '질주',
      '영혼',
      '메아리',
      '대항',
      '열의',
      '낙엽',
      '자스민',
      '아르마딜로',
      '치명',
      '용기',
    ],
  },
  {
    name: ['Right Finger', 'Left Finger', 'Belt'],
    list: [
      '신비',
      '격노',
      '소망',
      '마음',
      '열망',
      '활력',
      '고통',
      '물결',
      '사념',
      '운명',
    ],
  },
  {
    name: ['Earring', 'Charm', 'Necklace'],
    list: ['격노', '소망', '마음', '열망', '활력', '고통', '물결', '사념'],
  },
  {
    name: ['Artifact'],
    list: ['격노', '소망', '마음', '열망', '활력', '고통', '물결', '사념'],
  },
  {
    name: ['Rhod'],
    list: ['격돌', '돌진', '폭렬', '질주', '열렬', '산책'],
  },
];
