export const imageMap = new Map<string, string>([
  // 캐릭터
  ['리시타', '/images/characters/lethita.png'],
  ['피오나', '/images/characters/fiona.png'],
  ['이비', '/images/characters/evy.png'],
  ['카록', '/images/characters/kalok.png'],
  ['카이', '/images/characters/kay.png'],
  ['벨라', '/images/characters/vella.png'],
  ['허크', '/images/characters/hurk.png'],
  ['린', '/images/characters/lynn.png'],
  ['아리샤', '/images/characters/arisha.png'],
  ['헤기', '/images/characters/hagie.png'],
  ['델리아', '/images/characters/delia.png'],
  ['미리', '/images/characters/miri.png'],
  ['그림덴', '/images/characters/grimden.png'],
  ['미울', '/images/characters/miul.png'],
  ['벨', '/images/characters/bel.png'],
  ['레서', '/images/characters/lethor.png'],
  ['카엘', '/images/characters/kael.png'],
  ['테사', '/images/characters/tessa.png'],
  ['단아', '/images/characters/danah.png'],
  ['레티', '/images/characters/letty.png'],
  ['라티야', '/images/characters/latiya.png'],
  ['체른', '/images/characters/czern.png'],
  ['아켈', '/images/characters/achel.png'],
  ['소우', '/images/characters/sou.png'],
  ['사냐', '/images/characters/sanyaa.png'],
  ['네반', '/images/characters/neamhain.png'],

  // 시즌 2
  ['마신의 탑', '/images/monster/s2/tower-of-demon-god.png'],
  ['죽음의 그림자', '/images/monster/s2/the-shadow-of-death.png'],
  ['지하 도시', '/images/monster/s2/the-underground-city.png'],
  ['끝없는 질문', '/images/monster/s2/endless-questions.png'],
  ['지배자의 안식처', '/images/monster/s2/the-ruler-s-resting-place.png'],
  ['바다의 악마', '/images/monster/s2/sea-devil.png'],
  ['흘러간 기억', '/images/monster/s2/the-memories-that-flowed-away.png'],
  ['사막의 공주', '/images/monster/s2/desert-princess.png'],
  ['기이한 기계', '/images/monster/s2/strange-machine.png'],
  ['심연에서', '/images/monster/s2/in-the-abyss.png'],
  ['불타는 신전', '/images/monster/s2/burning-temple.png'],
  [
    '저승을 지키는 문지기',
    '/images/monster/s2/the-gatekeeper-of-the-underworld.png',
  ],
  ['황폐한 모르반', '/images/monster/s2/the-desolate-morvan.png'],
  ['죽음의 신', '/images/monster/s2/god-of-death.png'],

  // 시즌 3
  ['영혼의 부재', '/images/monster/s3/absence-of-the-soul.png'],
  ['붉은 낙인', '/images/monster/s3/red-brand.png'],
  ['왜곡된 진실', '/images/monster/s3/distorted-truth.png'],
  ['광휘의 루', '/images/monster/s3/tower-of-glory.png'],
  ['통제', '/images/monster/s3/control.png'],
  ['급습', '/images/monster/s3/raid.png'],
  ['실패와 대가', '/images/monster/s3/failure-and-the-price.png'],
  ['이웨카의 몽마', '/images/monster/s3/iweka-s-dream.png'],
  ['광기의 무덤', '/images/monster/s3/tomb-of-madness.png'],
  ['잊지 않기 위하여', '/images/monster/s3/to-not-forget.png'],
  ['지저의 실험실', '/images/monster/s3/laboratory-of-the-underworld.png'],

  // 시즌 4
  ['어둠의 일족', '/images/monster/s4/dark-clan.png'],
  ['라다톤 대교', '/images/monster/s4/ladaton-bridge.png'],
  ['로체스트 공방전', '/images/monster/s4/rochester-s-battle.png'],
  ['으스름달 아래서', '/images/monster/s4/under-the-crimson-moon.png'],
  ['실낙원의 첨병', '/images/monster/s4/the-vanguard-of-paradise-lost.png'],
  ['왕성 지하감옥', '/images/monster/s4/wangseong-dungeon.png'],
  ['잊혀진 제단', '/images/monster/s4/the-forgotten-altar.png'],
  ['왕성 토파즈 홀', '/images/monster/s4/wangseong-topaz-hall.png'],
  ['죽음의 변증법', '/images/monster/s4/dialectics-of-death.png'],
  ['원한의 암굴', '/images/monster/s4/cave-of-grudge.png'],
  ['위대한 사역', '/images/monster/s4/great-mission.png'],
  ['로흘란의 바람', '/images/monster/s4/rohlan-s-wind.png'],
  [
    '창조와 파괴의 성소',
    '/images/monster/s4/sanctuary-of-creation-and-destruction.png',
  ],
  ['검의 무덤', '/images/monster/s4/tomb-of-the-sword.png'],
  ['시드 별궁', '/images/monster/s4/seed-s-palace.png'],
  ['제단을 지키는 자', '/images/monster/s4/the-guardian-of-the-altar.png'],
  ['그릇된 고해', '/images/monster/s4/false-confession.png'],
  ['탐욕의 연회장', '/images/monster/s4/banquet-hall-of-greed.png'],
  ['따를 수 없는 예언', '/images/monster/s4/go.png'],
  ['정의를 망각한 대성당', '/images/monster/s4/cathedral.png'],

  ['신념의 상자: 결사대', '/images/items/reward/belief-box.png'],
  ['결의의 상자: 결사대', '/images/items/reward/resolution-box.png'],
  ['용맹의 상자: 결사대', '/images/items/reward/valor-box.png'],
  ['강림의 상자: 결사대', '/images/items/reward/advent-box.png'],

  ['[스페셜] 와드네 장비 상자', '/images/items/reward/special-box-u.png'],

  // 스페셜
  ['스페셜 전투', '/images/monster/special/garden-of-tears.png'],
  [
    '스페셜 던전: 인챈트 주머니',
    '/images/items/reward/random-special-dungeon-enchant.png',
  ],

  // 결사대
  ['사념의 바다', '/images/monster/forlornhope/the-sea-of-thoughts.png'],
  ['달의 이면', '/images/monster/forlornhope/the-back-side-of-the-moon.png'],
  ['모루 위의 검', '/images/monster/forlornhope/the-sword-on-the-moru.png'],
  ['생명의 나무', '/images/monster/forlornhope/the-tree-of-life.png'],

  // 결사대 [헬]
  ['사념의 바다 [헬]', '/images/monster/forlornhope/the-sea-of-thoughts.png'],
  [
    '달의 이면 [헬]',
    '/images/monster/forlornhope/the-back-side-of-the-moon.png',
  ],
  [
    '모루 위의 검 [헬]',
    '/images/monster/forlornhope/the-sword-on-the-moru.png',
  ],
  ['생명의 나무 [헬]', '/images/monster/forlornhope/the-tree-of-life.png'],

  // 시공간 왜곡
  ['찬탈자의 성채', '/images/monster/space/soul-usurper-taros.png'],
  ['몰락한 기사의 전당', '/images/monster/space/fallen-eisenritter.png'],
  ['주시자의 신전', '/images/monster/space/temple-of-the-watcher.png'],
  [
    '시공의 상자: 찬탈자의 성채',
    '/images/items/reward/space-time-box-usurpers-fortress.png',
  ],
  [
    '시공의 상자: 몰락한 기사의 전당',
    '/images/items/reward/space-time-box-hall-of-fallen-knights.png',
  ],
  [
    '시공의 상자: 주시자의 신전',
    '/images/items/reward/space-time-box-the-watchers-temple.png',
  ],

  // 재료
  [
    '[금속갑옷] 아바타 레시피 스크롤',
    '/images/items/materials/s4/recipe-metal.png',
  ],
  [
    '[재봉] 아바타 레시피 스크롤',
    '/images/items/materials/s4/recipe-sewing.png',
  ],

  ['장인의 섬세한 플라스크', '/images/items/materials/s4/flask_s.png'],
  ['장인의 단단한 플라스크', '/images/items/materials/s4/flask_h.png'],
  ['니플헤임 플라스크', '/images/items/materials/s4/flask_hardcore.png'],
  ['고급 미지의 팔찌 장식함', '/images/items/materials/s4/randomitem.png'],
  ['스렝의 정수', '/images/items/materials/s4/essence-of-sreng.png'],
  ['스피노스의 정수', '/images/items/materials/s4/essence-of-spinos.png'],
  ['모르간트의 정수', '/images/items/materials/s4/essence-of-morgant.png'],
  [
    '와드네의 파편: 무기',
    '/images/items/materials/s4/fragment-of-uaithne-weapon.png',
  ],
  [
    '와드네의 파편: 보조 장비',
    '/images/items/materials/s4/fragment-of-uaithne-weapon-secondary.png',
  ],
  [
    '와드네의 파편: 태양의 비원',
    '/images/items/materials/s4/fragment-of-uaithne-sun.png',
  ],
  [
    '와드네의 파편: 머리 방어구',
    '/images/items/materials/s4/fragment-of-uaithne-head.png',
  ],
  [
    '와드네의 파편: 가슴 방어구',
    '/images/items/materials/s4/fragment-of-uaithne-upper.png',
  ],
  [
    '와드네의 파편: 다리 방어구',
    '/images/items/materials/s4/fragment-of-uaithne-lower.png',
  ],
  [
    '와드네의 파편: 손 방어구',
    '/images/items/materials/s4/fragment-of-uaithne-hand.png',
  ],
  [
    '와드네의 파편: 발 방어구',
    '/images/items/materials/s4/fragment-of-uaithne-leg.png',
  ],
  [
    '와드네의 파편: 저주의 허리띠',
    '/images/items/materials/s4/fragment-of-uaithne-belt.png',
  ],
  [
    '와드네의 파편: 침묵의 증표',
    '/images/items/materials/s4/fragment-of-uaithne-finger-01.png',
  ],
  [
    '와드네의 파편: 고요의 증표',
    '/images/items/materials/s4/fragment-of-uaithne-finger-02.png',
  ],
  [
    '와드네 승급석: 무기',
    '/images/items/materials/s4/uaithne-promotion-stone-weapon.png',
  ],
  [
    '와드네 승급석: 머리 방어구',
    '/images/items/materials/s4/uaithne-promotion-stone-head.png',
  ],
  [
    '와드네 승급석: 가슴 방어구',
    '/images/items/materials/s4/uaithne-promotion-stone-upper.png',
  ],
  [
    '와드네 승급석: 다리 방어구',
    '/images/items/materials/s4/uaithne-promotion-stone-lower.png',
  ],
  [
    '와드네 승급석: 손 방어구',
    '/images/items/materials/s4/uaithne-promotion-stone-hand.png',
  ],
  [
    '와드네 승급석: 발 방어구',
    '/images/items/materials/s4/uaithne-promotion-stone-leg.png',
  ],
  [
    '단단한 와드네의 결정',
    '/images/items/materials/s4/solid-uaithne-crystal.png',
  ],
  [
    '매끈한 와드네의 결정',
    '/images/items/materials/s4/smooth-uaithne-crystal.png',
  ],
  [
    '예리한 와드네의 결정',
    '/images/items/materials/s4/incisive-uaithne-crystal.png',
  ],
  [
    '가벼운 와드네의 결정',
    '/images/items/materials/s4/light-uaithne-crystal.png',
  ],
  [
    '안정된 와드네의 결정',
    '/images/items/materials/s4/stable-uaithne-crystal.png',
  ],
  [
    '견고한 와드네의 결정',
    '/images/items/materials/s4/noble-uaithne-crystal.png',
  ],
  [
    '굳건한 와드네의 결정',
    '/images/items/materials/s4/firm-uaithne-crystal.png',
  ],

  ['아르드리의 봉인된 힘', '/images/items/materials/s4/combine_ardri.png'],
  [
    '아르드리의 봉인된 힘: 발 방어구',
    '/images/items/materials/s4/combine_ardri_leg.png',
  ],
  [
    '아르드리의 봉인된 힘: 가슴 방어구',
    '/images/items/materials/s4/combine_ardri_upper.png',
  ],
  [
    '아르드리의 봉인된 힘: 손 방어구',
    '/images/items/materials/s4/combine_ardri_hand.png',
  ],
  [
    '아르드리의 봉인된 힘: 다리 방어구',
    '/images/items/materials/s4/combine_ardri_lower.png',
  ],
  [
    '아르드리의 봉인된 힘: 머리 방어구',
    '/images/items/materials/s4/combine_ardri_head.png',
  ],
  [
    '아르드리의 봉인된 힘: 무기',
    '/images/items/materials/s4/combine_ardri_weapon.png',
  ],

  ['오롯한 와드네의 결정', '/images/items/materials/s4/a-uaithne-crystal.png'],
  ['미지의 조각 1단계', '/images/items/materials/s4/shard-unknown-1.png'],
  ['미지의 조각 2단계', '/images/items/materials/s4/shard-unknown-2.png'],
  ['미지의 조각 3단계', '/images/items/materials/s4/shard-unknown-3.png'],
  ['투쟁의 조각 1단계', '/images/items/materials/s4/shard_struggle-1.png'],
  ['투쟁의 조각 2단계', '/images/items/materials/s4/shard_struggle-2.png'],
  ['투쟁의 조각 3단계', '/images/items/materials/s4/shard_struggle-3.png'],
  ['미지의 결정', '/images/items/materials/s4/unknown-uaithne-crystal.png'],
  ['투쟁의 결정', '/images/items/materials/s4/fight-uaithne-crystal.png'],
  ['추출의 룬', '/images/items/materials/s4/extraction_rune.png'],
  [
    '고급 강화의 비약',
    '/images/items/materials/s4/elixir-of-advanced-strengthening.png',
  ],
  ['와드네의 결정', '/images/items/materials/s4/uaithne-crystal.png'],
  ['고르바스의 정수', '/images/items/materials/s4/essence-of-gorbas.png'],
  ['강화의 룬', '/images/items/materials/s4/rune-of-strengthening.png'],
  [
    '프리미엄 강화의 룬',
    '/images/items/materials/s4/preminu-rune-of-strengthening.png',
  ],
  [
    '+ 프리미엄 강화의 룬',
    '/images/items/materials/s4/preminu-rune-of-strengthening-plus.png',
  ],
  [
    '프리미엄 방어구 강화의 룬',
    '/images/items/materials/s4/preminu-rune-of-strengthening-armor.png',
  ],
  ['자르딘 강철', '/images/items/materials/s4/jardin-steel.png'],
  ['게브네의 강화석', '/images/items/materials/s4/gevne.png'],
  ['+ 게브네의 강화석', '/images/items/materials/s4/gevne-plus.png'],
  ['전승의 힘: 파편', '/images/items/materials/s4/j-limit-stone.png'],
  ['봉인의 힘: 파편', '/images/items/materials/s4/r-limit-stone.png'],

  [
    '오르나 무기 강화 촉진제',
    '/images/items/materials/s4/orna-accelerator-weapon.png',
  ],
  [
    '오르나 방어구 강화 촉진제: 가슴, 다리',
    '/images/items/materials/s4/orna-accelerator-upper-lower.png',
  ],
  [
    '오르나 방어구 강화 촉진제: 머리, 손, 발',
    '/images/items/materials/s4/orna-accelerator-head-hand-leg.png',
  ],
  ['신비의 힘: 파편', '/images/items/materials/s4/mystical-power-fragment.png'],
  ['불안정한 강화의 룬', '/images/items/materials/s4/rune_unstable.png'],

  ['힘이 주입된 뉴에라의 옷감', '/images/items/materials/s4/power-cloth.png'],
  ['힘이 주입된 뉴에라의 오브', '/images/items/materials/s4/power-orb.png'],
  ['힘이 주입된 뉴에라의 광석', '/images/items/materials/s4/power-ore.png'],
  ['힘이 주입된 뉴에라의 가죽', '/images/items/materials/s4/power-leather.png'],
  ['와드네의 흔적', '/images/items/materials/s4/uaithne-sign.png'],
  ['다마스쿠스 강철', '/images/items/materials/s4/damascus.png'],
  ['뉴에라의 오브', '/images/items/materials/s4/n-orb.png'],
  ['뉴에라의 광석', '/images/items/materials/s4/n-ore.png'],
  ['뉴에라의 가죽', '/images/items/materials/s4/n-leather.png'],
  ['뉴에라의 옷감', '/images/items/materials/s4/n-cloth.png'],

  ['오르나의 봉인된 힘', '/images/items/materials/s4/combine-orna.png'],
  [
    '오르나의 봉인된 힘: 머리 방어구',
    '/images/items/materials/s4/combine-orna-head.png',
  ],
  [
    '오르나의 봉인된 힘: 가슴 방어구',
    '/images/items/materials/s4/combine-orna-upper.png',
  ],
  [
    '오르나의 봉인된 힘: 다리 방어구',
    '/images/items/materials/s4/combine-orna-lower.png',
  ],
  [
    '오르나의 봉인된 힘: 손 방어구',
    '/images/items/materials/s4/combine-orna-hand.png',
  ],
  [
    '오르나의 봉인된 힘: 발 방어구',
    '/images/items/materials/s4/combine-orna-leg.png',
  ],
  [
    '오르나의 봉인된 힘: 무기',
    '/images/items/materials/s4/combine-orna-weapon.png',
  ],
  // ['오르나의 봉인된 힘', '/images/items/materials/s4/combine-orna-b.png'],
  ['골드', '/images/items/materials/basic/gold.png'],
  ['고급 철광석', '/images/items/materials/basic/high-grade-iron-ore.png'],
  ['마나 더스트', '/images/items/materials/basic/mana-dust.png'],
  ['마나 리포머', '/images/items/materials/basic/mana-reformer.png'],
  ['정령의 흔적', '/images/items/materials/basic/trace-of-the-spirit.png'],
  ['불의 흔적', '/images/items/materials/basic/fire-of-the-spirit.png'],
  ['냉기의 흔적', '/images/items/materials/basic/cool-of-the-spirit.png'],
  ['생명의 흔적', '/images/items/materials/basic/life-of-the-spirit.png'],
  ['대지의 흔적', '/images/items/materials/basic/st-of-the-spirit.png'],
  ['마법 가루', '/images/items/materials/basic/magic-powder.png'],
  ['최고급 강화석', '/images/items/materials/basic/best-k-stone.png'],
  ['생명의 에르그 결정', '/images/items/materials/basic/life-erg-crystal.png'],
  ['빈 병', '/images/items/materials/basic/empties.png'],
  ['오브', '/images/items/materials/basic/orb.png'],
  ['상급 생명력 포션', '/images/items/materials/basic/life-p-1.png'],
  ['고급 생명력 포션', '/images/items/materials/basic/life-p-2.png'],
  ['최고급 생명력 포션', '/images/items/materials/basic/life-p-3.png'],

  // 스킬 각성의 돌
  ['각성의 돌: 대미지 증가', '/images/items/skill/damage-stone.png'],
  ['각성의 돌: SP소모 감소', '/images/items/skill/sp-stone.png'],
  ['각성의 돌: 재사용시간 감소', '/images/items/skill/cooltime-stone.png'],
  ['각성의 돌: 스태미나 소모 감소', '/images/items/skill/stamina-stone.png'],
  ['각성의 돌: 부분 파괴 대미지', '/images/items/skill/downdamage-stone.png'],

  ['단단한 계승석 조각', '/images/items/materials/s4/solid-110.png'],
  ['매끈한 계승석 조각', '/images/items/materials/s4/smarmy-110.png'],
  ['예리한 계승석 조각', '/images/items/materials/s4/incisive-110.png'],
  ['안정된 계승석 조각', '/images/items/materials/s4/stable-110.png'],
  ['가벼운 계승석 조각', '/images/items/materials/s4/light-110.png'],
  ['오롯한 계승석 조각', '/images/items/materials/s4/all-110.png'],

  ['단단한 계승 원석', '/images/items/materials/s4/solid-115.png'],
  ['매끈한 계승 원석', '/images/items/materials/s4/smarmy-115.png'],
  ['예리한 계승 원석', '/images/items/materials/s4/incisive-115.png'],
  ['안정된 계승 원석', '/images/items/materials/s4/stable-115.png'],
  ['가벼운 계승 원석', '/images/items/materials/s4/light-115.png'],
  ['오롯한 계승 원석', '/images/items/materials/s4/all-115.png'],
  ['낙원의 강화석', '/images/items/materials/s4/nk.png'],
  ['마법력 엘릭서', '/images/items/materials/s4/ml.png'],
  ['생명의 마법력 엘릭서', '/images/items/materials/s4/sml.png'],
  ['축복의 마법력 엘릭서', '/images/items/materials/s4/csml.png'],
  ['축복받은 마법 가루', '/images/items/materials/s4/cmk.png'],
  ['뉴에라의 강화석', '/images/items/materials/s4/new-era-stone.png'],

  ['밀레드의 봉인된 힘', '/images/items/materials/s4/sealed_power_milled.png'],
  [
    '나베리우스의 봉인된 힘',
    '/images/items/materials/s4/sealed_power_naberius.png',
  ],
  ['카사르의 봉인된 힘', '/images/items/materials/s4/sealed_power_ceasair.png'],
  ['에녹의 봉인된 힘', '/images/items/materials/s4/sealed_power_en.png'],
  [
    '에메트의 봉인된 힘',
    '/images/items/materials/s4/sealed_power_managolem.png',
  ],
  [
    '야르니르의 봉인된 힘',
    '/images/items/materials/s4/sealed_power_barbarian.png',
  ],
  [
    '브레스의 달빛 봉인된 힘',
    '/images/items/materials/s4/sealed_power_bres_1.png',
  ],
  [
    '브레스의 그림자 봉인된 힘',
    '/images/items/materials/s4/sealed_power_bres_2.png',
  ],

  ['[금속무기] 레시피 스크롤', '/images/items/materials/s4/recipe.png'],
  ['[금속갑옷] 레시피 스크롤', '/images/items/materials/s4/recipe.png'],
  ['[세공] 레시피 스크롤', '/images/items/materials/s4/recipe.png'],
  ['[재봉] 레시피 스크롤', '/images/items/materials/s4/recipe.png'],

  ['단단한 에리우의 결정', '/images/items/materials/s4/re_hard.png'],
  ['예리한 에리우의 결정', '/images/items/materials/s4/re_we.png'],
  ['에리우 승급석: 무기', '/images/items/materials/s4/re_s_w.png'],
  ['에리우 승급석: 머리 방어구', '/images/items/materials/s4/re_s_h.png'],

  ['루시안의 정수', '/images/items/materials/s4/ru_j.png'],
  ['에리우의 파편: 머리 방어구', '/images/items/materials/s4/re_h.png'],
  ['에리우의 파편: 무기', '/images/items/materials/s4/re_rw.png'],
  ['에리우의 파편: 보조 장비', '/images/items/materials/s4/re_lw.png'],
  ['타리안 강철', '/images/items/materials/s4/tar.png'],

  // 장비
  // 105 액세서리
  ['황혼의 수호', '/images/items/equipment/105/finger-105-01.png'],
  ['황혼의 칼날', '/images/items/equipment/105/finger-105-02.png'],
  ['묵언의 결의', '/images/items/equipment/105/earring-105.png'],
  ['정신의 허리띠', '/images/items/equipment/105/belt-105.png'],

  // 105 밀레시안 방어구
  ['밀레시안 메일', '/images/items/equipment/105/m-upper.png'],
  ['밀레시안 그리브즈', '/images/items/equipment/105/m-lower.png'],
  ['밀레시안 헬름', '/images/items/equipment/105/m-head.png'],
  ['밀레시안 건틀릿', '/images/items/equipment/105/m-hand.png'],
  ['밀레시안 부츠', '/images/items/equipment/105/m-leg.png'],

  ['밀레시안의 서', '/images/items/equipment/105/m-book-105.png'],

  // 105 밀레시안 무기
  ['밀레시안 듀얼소드', '/images/items/equipment/105/dualsword-105.png'],
  ['밀레시안 듀얼스피어', '/images/items/equipment/105/dualspear-105.png'],
  ['밀레시안 바스타드소드', '/images/items/equipment/105/bastardsword-105.png'],
  ['밀레시안 배틀액스', '/images/items/equipment/105/battleaxe-105.png'],
  ['밀레시안 블뤼테', '/images/items/equipment/105/blute-105.png'],
  ['밀레시안 하스타', '/images/items/equipment/105/hasta-105.png'],
  ['밀레시안 배틀글레이브', '/images/items/equipment/105/battleglaive-105.png'],
  ['밀레시안 블래스터', '/images/items/equipment/105/blaster-105.png'],
  ['밀레시안 보우', '/images/items/equipment/105/bow-105.png'],
  ['밀레시안 드레이커', '/images/items/equipment/105/draker-105.png'],
  ['밀레시안 크레스트', '/images/items/equipment/105/crest-105.png'],
  ['밀레시안 크로스건', '/images/items/equipment/105/crossgun-105.png'],
  ['밀레시안 듀얼블레이드', '/images/items/equipment/105/dualblade-105.png'],
  ['밀레시안 듀얼나이프', '/images/items/equipment/105/dualknife-105.png'],
  ['밀레시안 그레이트소드', '/images/items/equipment/105/greatsword-105.png'],
  ['밀레시안 롱해머', '/images/items/equipment/105/longhammer-105.png'],
  ['밀레시안 롱소드', '/images/items/equipment/105/longsword-105.png'],
  ['밀레시안 롱블레이드', '/images/items/equipment/105/longblade-105.png'],
  ['밀레시안 헤비캐넌', '/images/items/equipment/105/heavycannon-105.png'],
  ['밀레시안 윕', '/images/items/equipment/105/whip-105.png'],
  ['밀레시안 랜스', '/images/items/equipment/105/lance-105.png'],
  ['밀레시안 레이피어', '/images/items/equipment/105/rapier-105.png'],
  ['밀레시안 소울블레이드', '/images/items/equipment/105/soulblade-105.png'],
  ['밀레시안 마나리볼버', '/images/items/equipment/105/manarevolver-105.png'],
  ['밀레시안 스태프', '/images/items/equipment/105/staff-105.png'],
  ['밀레시안 팬텀대거', '/images/items/equipment/105/phantomdagger-105.png'],
  ['밀레시안 테이드', '/images/items/equipment/105/teide-105.png'],
  ['밀레시안 소드스피어', '/images/items/equipment/105/swordspear-105.png'],
  ['밀레시안 배틀필러', '/images/items/equipment/105/battlepillar-105.png'],
  ['밀레시안 카타마르', '/images/items/equipment/105/catamadhar-105.png'],
  ['밀레시안 사이드', '/images/items/equipment/105/scythe-105.png'],
  ['밀레시안 홀리파이크', '/images/items/equipment/105/pike-105.png'],
  ['밀레시안 오르비스', '/images/items/equipment/105/orbis-105.png'],
  [
    '밀레시안 오리엔탈블레이드',
    '/images/items/equipment/105/orientalblade-105.png',
  ],

  // 110 아르드리 방어구
  ['아르드리 무기', '/images/items/equipment/110/a-weapon.png'],
  ['아르드리 메일', '/images/items/equipment/110/a-upper.png'],
  ['아르드리 그리브즈', '/images/items/equipment/110/a-lower.png'],
  ['아르드리 헬름', '/images/items/equipment/110/a-head.png'],
  ['아르드리 건틀릿', '/images/items/equipment/110/a-hand.png'],
  ['아르드리 부츠', '/images/items/equipment/110/a-leg.png'],
  ['아르드리의 서', '/images/items/equipment/110/ar-book.png'],

  // 110 아르드리 무기
  ['아르드리 듀얼소드', '/images/items/equipment/110/dualsword-110.png'],
  ['아르드리 듀얼스피어', '/images/items/equipment/110/dualspear-110.png'],
  ['아르드리 바스타드소드', '/images/items/equipment/110/bastardsword-110.png'],
  ['아르드리 배틀액스', '/images/items/equipment/110/battleaxe-110.png'],
  ['아르드리 블뤼테', '/images/items/equipment/110/blute-110.png'],
  ['아르드리 하스타', '/images/items/equipment/110/hasta-110.png'],
  ['아르드리 배틀글레이브', '/images/items/equipment/110/battleglaive-110.png'],
  ['아르드리 블래스터', '/images/items/equipment/110/blaster-110.png'],
  ['아르드리 보우', '/images/items/equipment/110/bow-110.png'],
  ['아르드리 드레이커', '/images/items/equipment/110/draker-110.png'],
  ['아르드리 크레스트', '/images/items/equipment/110/crest-110.png'],
  ['아르드리 크로스건', '/images/items/equipment/110/crossgun-110.png'],
  ['아르드리 듀얼블레이드', '/images/items/equipment/110/dualblade-110.png'],
  ['아르드리 듀얼나이프', '/images/items/equipment/110/dualknife-110.png'],
  ['아르드리 그레이트소드', '/images/items/equipment/110/greatsword-110.png'],
  ['아르드리 롱해머', '/images/items/equipment/110/longhammer-110.png'],
  ['아르드리 롱소드', '/images/items/equipment/110/longsword-110.png'],
  ['아르드리 롱블레이드', '/images/items/equipment/110/longblade-110.png'],
  ['아르드리 헤비캐넌', '/images/items/equipment/110/heavycannon-110.png'],
  ['아르드리 윕', '/images/items/equipment/110/whip-110.png'],
  ['아르드리 랜스', '/images/items/equipment/110/lance-110.png'],
  ['아르드리 레이피어', '/images/items/equipment/110/rapier-110.png'],
  ['아르드리 소울블레이드', '/images/items/equipment/110/soulblade-110.png'],
  ['아르드리 마나리볼버', '/images/items/equipment/110/manarevolver-110.png'],
  ['아르드리 스태프', '/images/items/equipment/110/staff-110.png'],
  ['아르드리 팬텀대거', '/images/items/equipment/110/phantomdagger-110.png'],
  ['아르드리 테이드', '/images/items/equipment/110/teide-110.png'],
  ['아르드리 소드스피어', '/images/items/equipment/110/swordspear-110.png'],
  ['아르드리 배틀필러', '/images/items/equipment/110/battlepillar-110.png'],
  ['아르드리 카타마르', '/images/items/equipment/110/catamadhar-110.png'],
  ['아르드리 사이드', '/images/items/equipment/110/scythe-110.png'],
  ['아르드리 홀리파이크', '/images/items/equipment/110/pike-110.png'],
  ['아르드리 오르비스', '/images/items/equipment/110/orbis-110.png'],
  [
    '아르드리 오리엔탈블레이드',
    '/images/items/equipment/110/orientalblade-110.png',
  ],

  // 115 오르나 방어구
  ['오르나 무기', '/images/items/equipment/115/o-weapon.png'],
  ['오르나 메일', '/images/items/equipment/115/o-upper.png'],
  ['오르나 그리브즈', '/images/items/equipment/115/o-lower.png'],
  ['오르나 헬름', '/images/items/equipment/115/o-head.png'],
  ['오르나 건틀릿', '/images/items/equipment/115/o-hand.png'],
  ['오르나 부츠', '/images/items/equipment/115/o-leg.png'],

  ['+15 오르나 무기', '/images/items/equipment/115/o-weapon.png'],
  ['+15 오르나 메일', '/images/items/equipment/115/o-upper.png'],
  ['+15 오르나 그리브즈', '/images/items/equipment/115/o-lower.png'],
  ['+15 오르나 헬름', '/images/items/equipment/115/o-head.png'],
  ['+15 오르나 건틀릿', '/images/items/equipment/115/o-hand.png'],
  ['+15 오르나 부츠', '/images/items/equipment/115/o-leg.png'],

  ['오르나의 서', '/images/items/equipment/115/o-book-115.png'],

  // 115 오르나 무기
  ['오르나 듀얼소드', '/images/items/equipment/115/dualsword-115.png'],
  ['오르나 듀얼스피어', '/images/items/equipment/115/dualspear-115.png'],
  ['오르나 바스타드소드', '/images/items/equipment/115/bastardsword-115.png'],
  ['오르나 배틀액스', '/images/items/equipment/115/battleaxe-115.png'],
  ['오르나 블뤼테', '/images/items/equipment/115/blute-115.png'],
  ['오르나 하스타', '/images/items/equipment/115/hasta-115.png'],
  ['오르나 배틀글레이브', '/images/items/equipment/115/battleglaive-115.png'],
  ['오르나 블래스터', '/images/items/equipment/115/blaster-115.png'],
  ['오르나 보우', '/images/items/equipment/115/bow-115.png'],
  ['오르나 드레이커', '/images/items/equipment/115/draker-115.png'],
  ['오르나 크레스트', '/images/items/equipment/115/crest-115.png'],
  ['오르나 크로스건', '/images/items/equipment/115/crossgun-115.png'],
  ['오르나 듀얼블레이드', '/images/items/equipment/115/dualblade-115.png'],
  ['오르나 듀얼나이프', '/images/items/equipment/115/dualknife-115.png'],
  ['오르나 그레이트소드', '/images/items/equipment/115/greatsword-115.png'],
  ['오르나 롱해머', '/images/items/equipment/115/longhammer-115.png'],
  ['오르나 롱소드', '/images/items/equipment/115/longsword-115.png'],
  ['오르나 롱블레이드', '/images/items/equipment/115/longblade-115.png'],
  ['오르나 헤비캐넌', '/images/items/equipment/115/heavycannon-115.png'],
  ['오르나 윕', '/images/items/equipment/115/whip-115.png'],
  ['오르나 랜스', '/images/items/equipment/115/lance-115.png'],
  ['오르나 레이피어', '/images/items/equipment/115/rapier-115.png'],
  ['오르나 소울블레이드', '/images/items/equipment/115/soulblade-115.png'],
  ['오르나 마나리볼버', '/images/items/equipment/115/manarevolver-115.png'],
  ['오르나 스태프', '/images/items/equipment/115/staff-115.png'],
  ['오르나 팬텀대거', '/images/items/equipment/115/phantomdagger-115.png'],
  ['오르나 테이드', '/images/items/equipment/115/teide-115.png'],
  ['오르나 소드스피어', '/images/items/equipment/115/swordspear-115.png'],
  ['오르나 배틀필러', '/images/items/equipment/115/battlepillar-115.png'],
  ['오르나 카타마르', '/images/items/equipment/115/catamadhar-115.png'],
  ['오르나 사이드', '/images/items/equipment/115/scythe-115.png'],
  ['오르나 홀리파이크', '/images/items/equipment/115/pike-115.png'],
  ['오르나 오르비스', '/images/items/equipment/115/orbis-115.png'],
  [
    '오르나 오리엔탈블레이드',
    '/images/items/equipment/115/orientalblade-115.png',
  ],

  //
  ['전승의 서', '/images/items/equipment/j-book.png'],
  // 120 와드네 방어구
  ['와드네 스몰실드', '/images/items/equipment/120/s-shild.png'],
  ['와드네 라지실드', '/images/items/equipment/120/r-shild.png'],
  ['와드네 그랜드타지', '/images/items/equipment/120/g-shild.png'],
  ['와드네의 서', '/images/items/equipment/120/u-book.png'],
  ['와드네 캐스틀릿', '/images/items/equipment/120/cas.png'],

  ['와드네 무기', '/images/items/equipment/120/u-weapon.png'],
  ['초급 와드네 무기', '/images/items/equipment/120/u-weapon.png'],
  ['중급 와드네 무기', '/images/items/equipment/120/u-weapon.png'],
  ['고급 와드네 무기', '/images/items/equipment/120/u-weapon.png'],
  ['레어 와드네 무기', '/images/items/equipment/120/u-weapon.png'],
  ['전설 와드네 무기', '/images/items/equipment/120/u-weapon.png'],

  ['와드네 헬름', '/images/items/equipment/120/uaithne-head.png'],
  ['초급 와드네 헬름', '/images/items/equipment/120/uaithne-head.png'],
  ['중급 와드네 헬름', '/images/items/equipment/120/uaithne-head.png'],
  ['고급 와드네 헬름', '/images/items/equipment/120/uaithne-head.png'],
  ['레어 와드네 헬름', '/images/items/equipment/120/uaithne-head.png'],
  ['전설 와드네 헬름', '/images/items/equipment/120/uaithne-head.png'],

  ['와드네 메일', '/images/items/equipment/120/uaithne-upper.png'],
  ['초급 와드네 메일', '/images/items/equipment/120/uaithne-upper.png'],
  ['중급 와드네 메일', '/images/items/equipment/120/uaithne-upper.png'],
  ['고급 와드네 메일', '/images/items/equipment/120/uaithne-upper.png'],
  ['레어 와드네 메일', '/images/items/equipment/120/uaithne-upper.png'],
  ['전설 와드네 메일', '/images/items/equipment/120/uaithne-upper.png'],

  ['와드네 그리브즈', '/images/items/equipment/120/uaithne-lower.png'],
  ['초급 와드네 그리브즈', '/images/items/equipment/120/uaithne-lower.png'],
  ['중급 와드네 그리브즈', '/images/items/equipment/120/uaithne-lower.png'],
  ['고급 와드네 그리브즈', '/images/items/equipment/120/uaithne-lower.png'],
  ['레어 와드네 그리브즈', '/images/items/equipment/120/uaithne-lower.png'],
  ['전설 와드네 그리브즈', '/images/items/equipment/120/uaithne-lower.png'],

  ['와드네 건틀릿', '/images/items/equipment/120/uaithne-hand.png'],
  ['초급 와드네 건틀릿', '/images/items/equipment/120/uaithne-hand.png'],
  ['중급 와드네 건틀릿', '/images/items/equipment/120/uaithne-hand.png'],
  ['고급 와드네 건틀릿', '/images/items/equipment/120/uaithne-hand.png'],
  ['레어 와드네 건틀릿', '/images/items/equipment/120/uaithne-hand.png'],
  ['전설 와드네 건틀릿', '/images/items/equipment/120/uaithne-hand.png'],

  ['와드네 부츠', '/images/items/equipment/120/uaithne-leg.png'],
  ['초급 와드네 부츠', '/images/items/equipment/120/uaithne-leg.png'],
  ['중급 와드네 부츠', '/images/items/equipment/120/uaithne-leg.png'],
  ['고급 와드네 부츠', '/images/items/equipment/120/uaithne-leg.png'],
  ['레어 와드네 부츠', '/images/items/equipment/120/uaithne-leg.png'],
  ['전설 와드네 부츠', '/images/items/equipment/120/uaithne-leg.png'],

  // 120 와드네 무기
  ['와드네 듀얼소드', '/images/items/equipment/120/dualsword-120.png'],
  ['와드네 듀얼스피어', '/images/items/equipment/120/dualspear-120.png'],
  ['와드네 바스타드소드', '/images/items/equipment/120/bastardsword-120.png'],
  ['와드네 배틀액스', '/images/items/equipment/120/battleaxe-120.png'],
  ['와드네 블뤼테', '/images/items/equipment/120/blute-120.png'],
  ['와드네 하스타', '/images/items/equipment/120/hasta-120.png'],
  ['와드네 배틀글레이브', '/images/items/equipment/120/battleglaive-120.png'],
  ['와드네 블래스터', '/images/items/equipment/120/blaster-120.png'],
  ['와드네 보우', '/images/items/equipment/120/bow-120.png'],
  ['와드네 드레이커', '/images/items/equipment/120/draker-120.png'],
  ['와드네 크레스트', '/images/items/equipment/120/crest-120.png'],
  ['와드네 크로스건', '/images/items/equipment/120/crossgun-120.png'],
  ['와드네 듀얼블레이드', '/images/items/equipment/120/dualblade-120.png'],
  ['와드네 듀얼나이프', '/images/items/equipment/120/dualknife-120.png'],
  ['와드네 그레이트소드', '/images/items/equipment/120/greatsword-120.png'],
  ['와드네 롱해머', '/images/items/equipment/120/longhammer-120.png'],
  ['와드네 롱소드', '/images/items/equipment/120/longsword-120.png'],
  ['와드네 롱블레이드', '/images/items/equipment/120/longblade-120.png'],
  ['와드네 헤비캐넌', '/images/items/equipment/120/heavycannon-120.png'],
  ['와드네 윕', '/images/items/equipment/120/whip-120.png'],
  ['와드네 랜스', '/images/items/equipment/120/lance-120.png'],
  ['와드네 레이피어', '/images/items/equipment/120/rapier-120.png'],
  ['와드네 소울블레이드', '/images/items/equipment/120/soulblade-120.png'],
  ['와드네 마나리볼버', '/images/items/equipment/120/manarevolver-120.png'],
  ['와드네 스태프', '/images/items/equipment/120/staff-120.png'],
  ['와드네 팬텀대거', '/images/items/equipment/120/phantomdagger-120.png'],
  ['와드네 테이드', '/images/items/equipment/120/teide-120.png'],
  ['와드네 소드스피어', '/images/items/equipment/120/swordspear-120.png'],
  ['와드네 배틀필러', '/images/items/equipment/120/battlepillar-120.png'],
  ['와드네 카타마르', '/images/items/equipment/120/catamadhar-120.png'],
  ['와드네 사이드', '/images/items/equipment/120/scythe-120.png'],
  ['와드네 홀리파이크', '/images/items/equipment/120/pike-120.png'],
  ['와드네 오르비스', '/images/items/equipment/120/orbis-120.png'],
  [
    '와드네 오리엔탈블레이드',
    '/images/items/equipment/120/orientalblade-120.png',
  ],

  // 로드
  ['찬탈자의 녹슨 로드', '/images/items/equipment/taros-01.png'],
  ['찬탈자의 로드', '/images/items/equipment/taros-02.png'],
  ['찬탈자의 빛나는 로드', '/images/items/equipment/taros-03.png'],
  ['찬탈자의 완전한 로드', '/images/items/equipment/taros-04.png'],

  ['몰락자의 녹슨 로드', '/images/items/equipment/fallen-01.png'],
  ['몰락자의 로드', '/images/items/equipment/fallen-02.png'],
  ['몰락자의 빛나는 로드', '/images/items/equipment/fallen-03.png'],
  ['몰락자의 완전한 로드', '/images/items/equipment/fallen-04.png'],

  // 팔찌
  ['미지의 가죽 팔찌 (증정)', '/images/items/equipment/bracelet-leather.png'],
  ['미지의 가죽 팔찌', '/images/items/equipment/bracelet-leather.png'],

  ['미지의 구리 팔찌 (증정)', '/images/items/equipment/bracelet-bronze.png'],
  ['미지의 구리 팔찌', '/images/items/equipment/bracelet-bronze.png'],

  ['미지의 순은 팔찌 (증정)', '/images/items/equipment/bracelet-cilver.png'],
  ['미지의 순은 팔찌', '/images/items/equipment/bracelet-cilver.png'],

  ['미지의 황금 팔찌 (증정)', '/images/items/equipment/bracelet-gold.png'],
  ['미지의 황금 팔찌', '/images/items/equipment/bracelet-gold.png'],

  // 브로치
  ['고양이 브로치', '/images/items/equipment/charm-01.png'],
  ['하얀 고양이 브로치', '/images/items/equipment/charm-02.png'],
  ['하얀 고양이 브로치 (30일)', '/images/items/equipment/charm-02.png'],
  ['파란 고양이 브로치', '/images/items/equipment/charm-03.png'],
  ['붉은 달 브로치', '/images/items/equipment/charm-04.png'],
  ['순백 깃털 브로치', '/images/items/equipment/charm-05.png'],
  ['잿빛 황혼 브로치', '/images/items/equipment/charm-06.png'],

  // 목걸이
  ['고양이 목걸이', '/images/items/equipment/necklace-01.png'],
  ['하얀 고양이 목걸이', '/images/items/equipment/necklace-02.png'],
  ['하얀 고양이 목걸이 (30일)', '/images/items/equipment/necklace-02.png'],
  ['파란 고양이 목걸이', '/images/items/equipment/necklace-03.png'],
  ['붉은 고양이 목걸이', '/images/items/equipment/necklace-04.png'],
  ['빛나는 고양이 목걸이', '/images/items/equipment/necklace-05.png'],

  // 허리띠
  ['어둠의 허리띠', '/images/items/equipment/belt-110.png'],
  ['투쟁의 허리띠', '/images/items/equipment/belt-115.png'],
  ['저주의 허리띠', '/images/items/equipment/belt-120.png'],

  // 귀걸이
  ['차원의 귀걸이', '/images/items/equipment/earring-110.png'],
  ['성소의 귀걸이', '/images/items/equipment/earring-115.png'],
  ['태양의 비원', '/images/items/equipment/sun_earring.png'],

  // 반지
  ['균열의 분노', '/images/items/equipment/ring-110-01.png'],
  ['균열의 공포', '/images/items/equipment/ring-110-02.png'],
  ['어둠 속 그림자', '/images/items/equipment/ring-115-01.png'],
  ['어둠 속 달빛', '/images/items/equipment/ring-115-02.png'],
  ['침묵의 증표', '/images/items/equipment/ring-120-01.png'],
  ['고요의 증표', '/images/items/equipment/ring-120-02.png'],

  // 아티팩트
  ['상급 청동 사자 조각상', '/images/items/equipment/abs.png'],
  ['서큐버스의 송곳니', '/images/items/equipment/succubus-00.png'],
  ['상급 서큐버스의 송곳니', '/images/items/equipment/succubus-01.png'],
  [
    '주시자의 녹슨 서큐버스의 송곳니',
    '/images/items/equipment/succubus-02.png',
  ],
  ['주시자의 서큐버스의 송곳니', '/images/items/equipment/succubus-03.png'],
  [
    '주시자의 빛나는 서큐버스의 송곳니',
    '/images/items/equipment/succubus-04.png',
  ],
  [
    '주시자의 완전한 서큐버스의 송곳니',
    '/images/items/equipment/succubus-05.png',
  ],

  ['의문의 고양이 조각상', '/images/items/equipment/mysterious-00.png'],
  ['상급 의문의 고양이 조각상', '/images/items/equipment/mysterious-01.png'],
  [
    '주시자의 녹슨 의문의 고양이 조각상',
    '/images/items/equipment/mysterious-02.png',
  ],
  [
    '주시자의 의문의 고양이 조각상',
    '/images/items/equipment/mysterious-03.png',
  ],
  [
    '주시자의 빛나는 의문의 고양이 조각상',
    '/images/items/equipment/mysterious-04.png',
  ],
  [
    '주시자의 완전한 의문의 고양이 조각상',
    '/images/items/equipment/mysterious-05.png',
  ],

  ['상급 전쟁 여신의 조각상', '/images/items/equipment/war-goddess-01.png'],
  [
    '주시자의 녹슨 전쟁 여신의 조각상',
    '/images/items/equipment/war-goddess-02.png',
  ],
  ['주시자의 전쟁 여신의 조각상', '/images/items/equipment/war-goddess-03.png'],
  [
    '주시자의 빛나는 전쟁 여신의 조각상',
    '/images/items/equipment/war-goddess-04.png',
  ],
  [
    '주시자의 완전한 전쟁 여신의 조각상',
    '/images/items/equipment/war-goddess-05.png',
  ],

  ['웨어울프의 앞발', '/images/items/equipment/werewolf-00.png'],
  ['웨어울프의 앞발 (30일)', '/images/items/equipment/werewolf-00.png'],
  ['상급 웨어울프의 앞발', '/images/items/equipment/werewolf-01.png'],
  ['주시자의 녹슨 웨어울프의 앞발', '/images/items/equipment/werewolf-02.png'],
  ['주시자의 웨어울프의 앞발', '/images/items/equipment/werewolf-03.png'],
  [
    '주시자의 빛나는 웨어울프의 앞발',
    '/images/items/equipment/werewolf-04.png',
  ],
  [
    '주시자의 완전한 웨어울프의 앞발',
    '/images/items/equipment/werewolf-05.png',
  ],

  ['칠흑빛 고양이 목걸이', '/images/items/equipment/bl-nec.png'],

  // 스킬

  // 리시타
  // 공통
  [
    '액티브: 스피릿 오브 버서커',
    '/images/characters/skill/double-crescent.png',
  ],
  ['글라이딩 퓨리', '/images/characters/skill/g-f.png'],
  ['윈드밀', '/images/characters/skill/w-m.png'],
  ['라이트닝 퓨리', '/images/characters/skill/l-f.png'],
  ['액티브: 코멧 대시', '/images/characters/skill/k-dash.png'],
  ['액티브: 퓨리 No.7', '/images/characters/skill/no7.png'],

  // 듀얼소드
  ['거트 스팅어', '/images/characters/skill/rose-thorns.png'],
  ['베어 블로어', '/images/characters/skill/pummelstorm.png'],
  ['슬립대시', '/images/characters/skill/slip-dash.png'],
  ['슬립스루', '/images/characters/skill/nimble-dash.png'],
  ['액티브: 래디컬 피버', '/images/characters/skill/a-r-p.png'],
  ['크레센트 라이징', '/images/characters/skill/rising-crescent.png'],
  ['트윈엣지 450', '/images/characters/skill/blade-tornado.png'],
  ['패닝 슬래시', '/images/characters/skill/fanning-slash.png'],
  ['사우전드 니들', '/images/characters/skill/thousand-needles.png'],
  ['더블 크레센트', '/images/characters/skill/double-crescent.png'],

  // 슈얼스피어
  ['3960 허리케인', '/images/characters/skill/3960.png'],
  ['문 스플리터', '/images/characters/skill/m-sf.png'],
  ['사일런트 호크', '/images/characters/skill/s-hf.png'],
  ['서든 블래스트', '/images/characters/skill/s-bl.png'],
  ['퀵 리버레이트', '/images/characters/skill/q-re.png'],

  // 피오나
  // 공통
  ['액티브: 방패 질주', '/images/characters/skill/shield-dash.png'],
  ['헤비스탠더 카운터', '/images/characters/skill/heavy-stander-counter.png'],
  ['카운터 어택', '/images/characters/skill/counterattack.png'],
  ['액티브: 타운트', '/images/characters/skill/active-taunt.png'],
  ['액티브: 피해 감쇄', '/images/characters/skill/iron-defense.png'],
  ['다운 카운터', '/images/characters/skill/alchemy-mercury.png'],
  ['액티브: 슬래싱 하이', '/images/characters/skill/slashing-high.png'],
  ['액티브: 방패 돌진', '/images/characters/skill/shield-charge.png'],
  ['액티브: 스프링클 카멜리아', '/images/characters/skill/camellia.png'],
  ['방패 흘리기', '/images/characters/skill/shield-deflection.png'],
  ['액티브: 방패 강타', '/images/characters/skill/heavy-stander.png'],

  // 피오나 롱소드
  ['스파이크 로즈', '/images/characters/skill/rose-thorns.png'],
  ['아마란스 킥', '/images/characters/skill/amaranth-kick.png'],
  ['아이비 스위퍼', '/images/characters/skill/ivys-weep.png'],
  ['페탈 블로우', '/images/characters/skill/p-blow.png'],
  ['해피 블로섬', '/images/characters/skill/alchemy-mercury.png'],
  ['액티브: 방패 강화', '/images/characters/skill/active-shield.png'],
  ['액티브: 어썰트 크로톤', '/images/characters/skill/assault.png'],

  // 피오나 롱해머
  ['그랜드 슬램 칼라', '/images/characters/skill/hammer-crushing.png'],
  ['버터플라이 스윙', '/images/characters/skill/alchemy-mercury.png'],
  ['비틀 크러쉬', '/images/characters/skill/beetle-crusher.png'],
  ['스티그마 해머', '/images/characters/skill/long-hammer.png'],
  ['하니 비 스팅', '/images/characters/skill/long-hammer-honeybee.png'],
  ['액티브: 블루밍 바이올렛', '/images/characters/skill/violet.png'],
  ['액티브: 짓누르기', '/images/characters/skill/a-crush.png'],

  // 이비
  // 공통
  ['이글 탈론', '/images/characters/skill/eagle.png'],
  ['액티브: 미티어 스웜', '/images/characters/skill/meteor-swarm.png'],
  ['액티브: 중력 역전', '/images/characters/skill/gra.png'],

  // 스태프
  ['매직 애로우', '/images/characters/skill/magic.png'],
  ['액티브: 라이트닝 볼트', '/images/characters/skill/lightning-bolt.png'],
  ['액티브: 마나 마인', '/images/characters/skill/mana-mine.png'],
  ['액티브: 아이스 스피어', '/images/characters/skill/ice-spear.png'],
  ['액티브: 파이어볼트', '/images/characters/skill/firebolt.png'],
  ['액티브: 아이스 블래스트', '/images/characters/skill/ice-bl.png'],
  ['액티브: 힐링 펄', '/images/characters/skill/healring.png'],
  ['액티브: 파이어 스톰', '/images/characters/skill/firestorm.png'],
  ['액티브: 재생', '/images/characters/skill/rec.png'],
  ['액티브: 라이트닝 웨이브', '/images/characters/skill/lightning-wave.png'],
  ['액티브: 라이트닝 가이드', '/images/characters/skill/guided-lightning.png'],
  ['액티브: 아이스 블로우', '/images/characters/skill/ice-blow.png'],
  ['액티브: 파이어 쇼크', '/images/characters/skill/fire-shock.png'],
  ['액티브: 레이즈', '/images/characters/skill/rage.png'],
  ['액티브: 연속 집중', '/images/characters/skill/a-m.png'],

  // 배틀사이드
  ['라이프 스틸', '/images/characters/skill/life-still.png'],
  ['새크리파이스', '/images/characters/skill/secp.png'],
  ['스피릿 바인드', '/images/characters/skill/spirit-bind.png'],
  ['액티브: 컨퓨전 홀', '/images/characters/skill/void-star.png'],
  ['데몬 스플리터', '/images/characters/skill/demon-sp.png'],
  ['블링크 문라이트', '/images/characters/skill/blank-m.png'],
  ['헬 퀘이크', '/images/characters/skill/hell-quake.png'],
  ['데스 레이블', '/images/characters/skill/mark-of-death.png'],
  ['소울 스큐어', '/images/characters/skill/soul-skewer.png'],
  ['피어 스크림', '/images/characters/skill/scream.png'],
  ['액티브: 인세인 리퍼', '/images/characters/skill/insane-r.png'],
  ['블러디 스레드', '/images/characters/skill/bloody-thread.png'],
  ['액티브: 아케인 게이트', '/images/characters/skill/a-ks.png'],
  ['인비지블 룸', '/images/characters/skill/loom.png'],

  // 카록
  // 카록 공통
  ['액티브: 하울링', '/images/characters/skill/k-h.png'],
  ['액티브: 샤우트', '/images/characters/skill/k-s.png'],

  // 카록 배틀필러
  ['매머드 스윕', '/images/characters/skill/k-m-sw.png'],
  ['워 스톰프', '/images/characters/skill/k-1-warstomp.png'],
  ['바이슨 차지', '/images/characters/skill/k-b-cge.png'],
  ['액티브: 데들리 컴퍼스', '/images/characters/skill/k-d-p.png'],
  ['웨일 밤', '/images/characters/skill/k-w-b.png'],
  ['점보 스턱', '/images/characters/skill/j-stk.png'],
  ['드롭킥', '/images/characters/skill/k-kick.png'],
  ['매머드 크래쉬', '/images/characters/skill/k-m-crush.png'],
  ['액티브: 돌개바람', '/images/characters/skill/k-d-wind.png'],
  ['라이노 고어', '/images/characters/skill/k-r-go.png'],
  ['웨일 뱅', '/images/characters/skill/k-bang.png'],
  ['액티브: 멸절', '/images/characters/skill/k-a-mul.png'],
  ['액티브: 어스퀘이크', '/images/characters/skill/k-a-ask.png'],
  ['볼버라이즈', '/images/characters/skill/k-b-rise.png'],
  ['매머드 프래셔', '/images/characters/skill/k-m-pre.png'],
  ['그리즐리 범프', '/images/characters/skill/k-g-bum.png'],
  ['롤링 어택', '/images/characters/skill/k-1-ratk.png'],
  ['라이노 헤드벗', '/images/characters/skill/k-1-r-head.png'],
  ['전투 돌진', '/images/characters/skill/k-1-dash.png'],

  // 카록 블래스터
  ['빅뱅', '/images/characters/skill/k-bigbang.png'],
  ['차징 버스트', '/images/characters/skill/k-2-c-bust.png'],
  ['볼로 펀치', '/images/characters/skill/k-2-bolo.png'],
  ['스트레이트 펀치', '/images/characters/skill/k-2-s-punch.png'],
  ['선데이 펀치', '/images/characters/skill/k-2-sun-punch.png'],
  ['웨이스트 피벗', '/images/characters/skill/k-2-pe.png'],
  ['액티브: 폭풍', '/images/characters/skill/k-2-stom.png'],
  ['액티브: 화산 폭발', '/images/characters/skill/k-2-hk.png'],
  ['액티브: 힘의 해방', '/images/characters/skill/k-2-unlimit.png'],
  ['액티브: 격노', '/images/characters/skill/k-2-kn.png'],
  ['액티브: 인파이팅', '/images/characters/skill/k-2-infight.png'],
  ['J.F 버스트', '/images/characters/skill/k-2-jf.png'],
  ['뎀프시롤', '/images/characters/skill/k-2-ds.png'],

  ['공격력', '/images/icon/att.png'],
  ['크리티컬', '/images/icon/cri.png'],
  ['밸런스', '/images/icon/bal.png'],
  ['대항력', '/images/icon/reg.png'],
  ['크리티컬 저항', '/images/icon/cridef.png'],
  ['추가피해', '/images/icon/atkplus.png'],
  ['방어력', '/images/icon/def.png'],
  ['공격속도', '/images/icon/atkspeed.png'],
  ['해제', '/images/icon/limit.png'],
  ['해제 2', '/images/icon/limit.png'],

  // 카이
  // 공통 X

  // 카이 활
  ['속사', '/images/characters/skill/ka-1-ss.png'],
  ['쓰러스트킥', '/images/characters/skill/ka-1-skick.png'],
  ['액티브: 밴딩샷', '/images/characters/skill/ka-1-banding.png'],
  ['차징샷', '/images/characters/skill/ka-1-charging-shot.png'],
  ['스핀킥', '/images/characters/skill/ka-1-spin-kick.png'],
  ['매그넘샷', '/images/characters/skill/ka-1-m-shot.png'],
  ['마운팅', '/images/characters/skill/ka-1-m-ting.png'],
  ['액티브: 애로우 스톰', '/images/characters/skill/ka-1-ar-st.png'],
  ['액티브: 듀얼링크', '/images/characters/skill/ka-1-d-link.png'],
  ['액티브: 멀티 스나이핑', '/images/characters/skill/ka-1-mul-s.png'],
  ['액티브: 페이탈 애로우', '/images/characters/skill/ka-1-pay.png'],

  // 카이 총
  ['스핀 스매시', '/images/characters/skill/ka-2-spin-smash.png'],
  ['액티브: 할로우샷', '/images/characters/skill/ka-2-halow.png'],
  ['액티브: 피어싱', '/images/characters/skill/ka-2-pi.png'],
  ['액티브: 블렛6', '/images/characters/skill/ka-2-b6.png'],
  ['액티브: 핸드밤', '/images/characters/skill/ka-2-handb.png'],
  ['액티브: 밴드 서포트', '/images/characters/skill/ka-2-bands.png'],
  ['액티브: 인핸스 볼트', '/images/characters/skill/ka-2-i-bolt.png'],
  ['액티브: 거스팅 볼트', '/images/characters/skill/ka-2-g-bolt.png'],
  ['액티브: 벙커 버스터', '/images/characters/skill/ka-2-b-bust.png'],
  ['액티브: 아토믹', '/images/characters/skill/ka-2-atomic.png'],

  // 벨라
  // 벨라 공통 X

  // 벨라 듀얼소드
  ['데들리 게일', '/images/characters/skill/bel-1-d-g.png'],
  ['디바이딩 에디', '/images/characters/skill/bel-1-d-ady.png'],
  ['메나싱 게일', '/images/characters/skill/bel-1-ma-g.png'],
  ['스핀 러시', '/images/characters/skill/bel-1-spin-r.png'],
  ['액티브: 타이푼 슬래쉬', '/images/characters/skill/bel-1-ty-sh.png'],
  ['크로스 스트라이크', '/images/characters/skill/bel-1-cross-st.png'],
  ['백래쉬', '/images/characters/skill/bel-1-back.png'],
  ['거스티 블레이드', '/images/characters/skill/bel-1-g-blade.png'],
  ['액티브: 검의 의지', '/images/characters/skill/bel-1-s-soul.png'],
  ['액티브: 템페스트', '/images/characters/skill/bel-1-tps.png'],
  ['액티브: 게일 스플리터', '/images/characters/skill/bel-1-a-split.png'],

  // 벨라 듀얼블레이드
  ['루미너스 러시', '/images/characters/skill/bel-2-lu-rush.png'],
  ['미스트 슬래쉬', '/images/characters/skill/bel-2-m-shl.png'],
  ['스파이럴 스핀', '/images/characters/skill/bel-2-s-spin.png'],
  ['액티브: 뱀파이어의 키스', '/images/characters/skill/bel-2-b-kiss.png'],
  ['액티브: 도미네이트', '/images/characters/skill/bel-2-dom.png'],
  ['모먼트 블로우', '/images/characters/skill/bel-2-moblow.png'],
  ['소노러스 필', '/images/characters/skill/bel-2-sono.png'],
  ['액티브: 레드 아이즈', '/images/characters/skill/bel-2-red-e.png'],
  ['액티브: 냉각', '/images/characters/skill/bel-2-cold.png'],
  ['액티브: 글라시얼 브레이커', '/images/characters/skill/bel-2-g-break.png'],
  ['액티브: 폴라리스 소나타', '/images/characters/skill/bel-2-f-so.png'],
  ['액티브: 블레이드 댄스', '/images/characters/skill/bel-2-blade-d.png'],

  // 허크
  // 허크 공통 X

  // 허크 그레이트 소드
  ['만월', '/images/characters/skill/huk-1-ma.png'],
  ['붕괴', '/images/characters/skill/huk-1-b.png'],
  ['신월', '/images/characters/skill/huk-1-sin.png'],
  ['액티브: 심판', '/images/characters/skill/huk-1-a-simp.png'],
  ['처형', '/images/characters/skill/huk-1-kill.png'],
  ['학살', '/images/characters/skill/huk-1-h-kill.png'],
  ['액티브: 기합 베기', '/images/characters/skill/huk-1-g-bi.png'],
  ['소용돌이', '/images/characters/skill/huk-1-wind.png'],
  ['액티브: 필살의 일격', '/images/characters/skill/huk-1-fil.png'],
  ['액티브: 광폭화', '/images/characters/skill/huk-1-gp.png'],
  ['액티브: 절명', '/images/characters/skill/huk-1-jm.png'],

  // 허크 테이드
  ['액티브: 스플릿 슬래쉬', '/images/characters/skill/huk-2-split-s.png'],
  ['액티브: 퍼펙트 리로드', '/images/characters/skill/huk-2-perfect.png'],
  ['액티브: 임펙트 슈어 샷', '/images/characters/skill/huk-2-imfact.png'],
  ['액티브: 스피닝 슬래쉬', '/images/characters/skill/huk-2-s-sha.png'],
  ['액티브: 페이탈 슬래쉬', '/images/characters/skill/huk-2-p-s.png'],
  ['액티브: 슬랩 더 킬러', '/images/characters/skill/huk-2-s-t-k.png'],
  ['액티브: 데스페라도', '/images/characters/skill/huk-2-des.png'],

  // 린
  // 린 공통 X
  // 린 배틀 글레이브
  ['뇌전', '/images/characters/skill/ry-1-n.png'],
  ['비류', '/images/characters/skill/ry-1-b.png'],
  ['섬격창', '/images/characters/skill/ry-1-s-3.png'],
  ['액티브: 일섬', '/images/characters/skill/ry-1-ils.png'],
  ['천격', '/images/characters/skill/ry-1-cun.png'],
  ['파진', '/images/characters/skill/ry-1-p-jin.png'],
  ['환류창', '/images/characters/skill/ry-1-hwan.png'],
  ['낙화', '/images/characters/skill/ry-1-n-hwa.png'],
  ['액티브: 삼연섬', '/images/characters/skill/ry-1-3-sum.png'],
  ['액티브: 화접무', '/images/characters/skill/ry-1-hwa-j.png'],
  ['연풍참', '/images/characters/skill/ry-1-y-p.png'],
  ['비상천', '/images/characters/skill/ty-1-b-sang.png'],
  ['천뢰창', '/images/characters/skill/ry-1-c-l.png'],
  ['액티브: 비연격', '/images/characters/skill/ry-1-by.png'],
  ['액티브: 유연단화', '/images/characters/skill/ry-1-uyd.png'],
  ['액티브: 멸화참', '/images/characters/skill/ry-1-mhwac.png'],

  // 린 블뤼테
  ['비화격', '/images/characters/skill/ry-2-behwa.png'],
  ['비화풍', '/images/characters/skill/ry-2-behwa-p.png'],
  ['액티브: 비풍일격', '/images/characters/skill/ry-2-be-i.png'],
  ['월연격', '/images/characters/skill/ry-2-buk.png'],
  ['월연풍', '/images/characters/skill/ry-2-byp.png'],
  ['진풍격', '/images/characters/skill/ry-2-j-p.png'],
  ['화진격', '/images/characters/skill/ry-2-hwa-j.png'],
  ['화진각', '/images/characters/skill/ry-2-hwa-k.png'],
  ['액티브: 화신풍', '/images/characters/skill/ry-2-a-hwasin.png'],
  ['액티브: 투산철격', '/images/characters/skill/ry-2-tosan.png'],
  ['액티브: 반화격', '/images/characters/skill/ry-2-ban-hwa.png'],
  ['액티브: 기천비무', '/images/characters/skill/ry-2-ri-j.png'],
  ['액티브: 유화강기', '/images/characters/skill/ry-2-u-hwa.png'],
  ['액티브: 유원백화', '/images/characters/skill/ry-2-u-won.png'],
  ['액티브: 운심월성', '/images/characters/skill/ry-2-u-w-s.png'],

  // 아리샤
  // 아리샤 공통 X

  // 아리샤 롱블레이드
  ['마나 스톤', '/images/characters/skill/ar-1-mana-stone.png'],
  ['샤픈 마나', '/images/characters/skill/ar-1-shwa-mana.png'],
  ['액티브: 디멘션 홀', '/images/characters/skill/ar-1-d-h.png'],
  ['액티브: 마나 리전', '/images/characters/skill/ar-1-mana-re.png'],
  ['액티브: 캐스트 마나', '/images/characters/skill/ar-1-cast-mana.png'],
  ['액티브: 루인 블레이드', '/images/characters/skill/ar-1-ru-b.png'],
  ['피스트 오브 블레이드', '/images/characters/skill/ar-1-f-b.png'],
  ['액티브: 둠세이어', '/images/characters/skill/ar-1-d-sa.png'],
  ['액티브: 레저넌스', '/images/characters/skill/ar-1-rjn.png'],
  ['워프 홀', '/images/characters/skill/ar-1-warp-h.png'],
  ['액티브: 로드 오브 마나', '/images/characters/skill/ar-1-rhod-of.png'],
  ['스위치 마나', '/images/characters/skill/ar-1-switch.png'],

  // 아리샤 윕
  ['린포르찬도 피네', '/images/characters/skill/ar-2-r-p.png'],
  ['마르카토 러시', '/images/characters/skill/ar-2-m-rush.png'],
  ['액티브: 배턴 포 왈츠', '/images/characters/skill/ar-2-b-w.png'],
  ['마나 디소넌스', '/images/characters/skill/ar-2-mana-d.png'],
  ['마나 아그레망', '/images/characters/skill/ar-2-m-ar.png'],
  ['스크리밍 콰이어', '/images/characters/skill/ar-2-s-c.png'],
  ['스트린젠도 슬랩', '/images/characters/skill/ar-2-sc-j.png'],
  ['액티브: 모티베이션', '/images/characters/skill/ar-2-mot.png'],
  ['액티브: 인스피레이션', '/images/characters/skill/ar-2-ins.png'],
  ['리시딩 인터류드', '/images/characters/skill/ar-2-inr.png'],
  ['액티브: 마나 카프리치오', '/images/characters/skill/ar-2-mana-c.png'],
  ['액티브: 액시덴탈 악센트', '/images/characters/skill/ar-2-a-ac.png'],
  ['액티브: 크레셴도 심포니', '/images/characters/skill/ar-2-c-sim.png'],

  // 델리아
  ['라스트 슈팅스타', '/images/characters/skill/del-1-last-s.png'],
  ['스타 디바이더', '/images/characters/skill/del-1-s-di.png'],
  ['스타 스크래퍼', '/images/characters/skill/del-1-s-sc.png'],
  ['스타 스트라이크', '/images/characters/skill/del-1-sun-s.png'],
  ['썬 플레어', '/images/characters/skill/del-1-sun-f.png'],
  ['이니셜 슈팅스타', '/images/characters/skill/del-1-su.png'],
  ['제미니 스타라이트', '/images/characters/skill/del-1-j-st.png'],
  ['주피터스 벨트', '/images/characters/skill/del-1-jup.png'],
  ['액티브 : 위스퍼링 로즈', '/images/characters/skill/del-1-a-rose.png'],
  ['와일드 스타', '/images/characters/skill/del-1-wild.png'],
  ['퀸즈 그레이스', '/images/characters/skill/del-1-qu.png'],
  ['액티브 : 와일드 스타', '/images/characters/skill/del-1-a-wild.png'],
  ['액티브 : 로즈 크러시', '/images/characters/skill/del-1-a-rose-crush.png'],

  // 헤기 팬텀대거
  ['라이징 샷', '/images/characters/skill/he-1-ra.png'],
  ['라이징 슬래쉬', '/images/characters/skill/he-1-ra-sh.png'],
  ['사이클론 엣지', '/images/characters/skill/he-1-sae.png'],
  ['사이클론 크래쉬', '/images/characters/skill/he-1-si-cr.png'],
  ['얼티밋 블레이드', '/images/characters/skill/he-1-ual.png'],
  ['팬텀 슈터', '/images/characters/skill/he-1-pen.png'],
  ['액티브: 스팩트럴 스팅', '/images/characters/skill/he-1-a-spe.png'],
  ['액티브: 판타즈마 슬래쉬', '/images/characters/skill/he-1-pan-s.png'],
  ['스피릿 커터', '/images/characters/skill/he-1-spi.png'],
  ['얼티밋 차지', '/images/characters/skill/he-1-u-cr.png'],
  ['액티브: 익스팅션 로어', '/images/characters/skill/he-1-ex-ro.png'],
  ['액티브: 인피니티 레퀴엠', '/images/characters/skill/he-1-infi.png'],

  // 미리
  ['데스 토네일', '/images/characters/skill/miri-1-des.png'],
  ['러싱 스파인', '/images/characters/skill/miri-1-ru-sa.png'],
  ['레비징 투스', '/images/characters/skill/miri-1-toos.png'],
  ['액티브: 플레임 브레스', '/images/characters/skill/miri-1-bress.png'],
  ['크러싱 네일', '/images/characters/skill/miri-1-c-ne.png'],
  ['피니싱 테일', '/images/characters/skill/miri-f-tail.png'],
  ['피어싱 암', '/images/characters/skill/miri-1-f-ar.png'],
  ['안세스터스 윌: 스트라이커', '/images/characters/skill/miri-1-a-str.png'],
  ['액티브: 레클리스 차지', '/images/characters/skill/miri-1-pri.png'],
  ['안세스터스 윌: 리벤저', '/images/characters/skill/miri-1-a-re.png'],
  ['액티브: 라스트 디센던트', '/images/characters/skill/miri-1-last-d.png'],
  ['액티브: 라스트 드레이커', '/images/characters/skill/miri-1-last-dre.png'],

  // 그림덴
  ['모털 아츠', '/images/characters/skill/gr-1-moa.png'],
  ['섬멸', '/images/characters/skill/gr-1-kill.png'],
  ['액티브: 디컬레이션', '/images/characters/skill/gr-1-a-d.png'],
  ['액티브: 스파인 브레이커', '/images/characters/skill/gr-1-a-breaker.png'],
  ['에이질 스트라이크', '/images/characters/skill/gr-1-agil.png'],
  ['일리걸 스턱커도', '/images/characters/skill/gr-1-struk.png'],
  ['일리걸 워크', '/images/characters/skill/gr-1-work.png'],
  ['액티브: 스트라이더', '/images/characters/skill/gr-1-stt.png'],
  ['크사나', '/images/characters/skill/gr-1-ksana.png'],
  ['액티브: 밀리언 데거', '/images/characters/skill/gr-1-mil.png'],
  ['액티브: 리썰 크로스', '/images/characters/skill/gr-1-cross.png'],

  // 미울
  ['데들리 스핀', '/images/characters/skill/mi-1-d-spin.png'],
  ['데들리 트위스터', '/images/characters/skill/mi-1-d-tw.png'],
  ['데들리 트위스트', '/images/characters/skill/mi-d-twst.png'],
  ['브레이킹 블래스트', '/images/characters/skill/mi-1-b-blast.png'],
  ['브레이킹 샷', '/images/characters/skill/mi-1-break-s.png'],
  ['어썰트 블래스트', '/images/characters/skill/mi-1-ass-b.png'],
  ['액티브: 패닝 샷', '/images/characters/skill/mi-a-a-pas.png'],
  ['어썰트 샷', '/images/characters/skill/mi-1-as-so.png'],
  ['액티브: 립 밴 윙클', '/images/characters/skill/mi-a-r-wing.png'],
  ['디바인 백플립 샷', '/images/characters/skill/mi-a-back-s.png'],
  ['중력탄', '/images/characters/skill/mi-a-gr-s.png'],
  ['액티브: 더블 패닝 샷', '/images/characters/skill/mi-a-double-s.png'],
  ['약화탄', '/images/characters/skill/mi-1-down.png'],
  ['액티브: 루인 스피어', '/images/characters/skill/mi-a-ru-s.png'],
  ['액티브: 퀀텀 스페이스', '/images/characters/skill/mi-a-q-space.png'],

  // 벨
  ['가지 치기', '/images/characters/skill/bb-1-ka.png'],
  ['밑동 자르기', '/images/characters/skill/bb-1-un-k.png'],
  ['뿌리 뽑기', '/images/characters/skill/bb-1-poo.png'],
  ['솎아주기', '/images/characters/skill/bb-1-sor.png'],
  ['액티브: 참 가르기', '/images/characters/skill/bb-1-a-cham.png'],
  ['잡초 뽑기', '/images/characters/skill/bb-1-jab.png'],
  ['장작 쪼개기', '/images/characters/skill/bb-1-jjo.png'],
  ['가문비 가르기', '/images/characters/skill/bb-1-jamon.png'],
  ['산림욕', '/images/characters/skill/bb-1-san.png'],
  ['액티브: 솔 가르기', '/images/characters/skill/bb-1-solg.png'],
  ['액티브: 흑단 가르기', '/images/characters/skill/bb-1-h-dak.png'],
  ['액티브: 물푸레 가르기', '/images/characters/skill/bb-1-m-ga.png'],

  // 레서
  ['망월연무', '/images/characters/skill/re-1-my.png'],
  ['반월연무', '/images/characters/skill/re-1-by.png'],
  ['액티브: 호조', '/images/characters/skill/re-1-hojo.png'],
  ['초월연무', '/images/characters/skill/re-1-co-y.png'],
  ['호격', '/images/characters/skill/re-1-ho-k.png'],
  ['회륜격', '/images/characters/skill/re-1-h-k.png'],
  ['액티브: 용아', '/images/characters/skill/re-1-a-you.png'],
  ['액티브: 멸령폭진', '/images/characters/skill/re-1-m-p.png'],
  ['용격', '/images/characters/skill/re-1-yk.png'],
  ['액티브: 뇌락', '/images/characters/skill/re-1-nk.png'],
  ['액티브: 무아연격', '/images/characters/skill/re-1-ma.png'],

  // 카엘
  ['가디언즈 블레이드: 스트라이크', '/images/characters/skill/kl-1-st.png'],
  ['썬더버드 슬래쉬', '/images/characters/skill/kl-sun-b.png'],
  ['액티브: 레이지 레지스탕스', '/images/characters/skill/kl-1-r-rage.png'],
  ['가디언즈 블레이드: 카운터', '/images/characters/skill/kl-1-counter.png'],
  ['레드호크 크러쉬', '/images/characters/skill/kl-1-red.png'],
  ['이글 플라이트', '/images/characters/skill/kl-1-hok.png'],
  ['액티브: 로우 플라이트', '/images/characters/skill/kl-1-low.png'],
  ['액티브: 디모스 업라이징', '/images/characters/skill/kl-1-dmos.png'],
  ['액티브: 서클 오브 라이트', '/images/characters/skill/kl-01-of-l.png'],

  // 테사
  ['발레스트라: 루비', '/images/characters/skill/te-1-rubi.png'],
  ['발레스트라: 사파이어', '/images/characters/skill/te-1-sapa.png'],
  ['발레스트라: 토파즈', '/images/characters/skill/te-1-topaz.png'],
  ['스피넬 플레쉬', '/images/characters/skill/te-1-spn.png'],
  ['액티브: 다이아몬드 더블릿', '/images/characters/skill/te-1-a-dia.png'],
  ['에메랄드 이베이전', '/images/characters/skill/te-1-em.png'],
  ['베릴 슬래쉬', '/images/characters/skill/te-1-be-s.png'],
  ['스핀 스피어', '/images/characters/skill/te-1-spin-s.png'],
  ['액티브: 셸 디펜시브', '/images/characters/skill/te-1-s-de.png'],
  ['액티브: 아메지스트 플로우', '/images/characters/skill/te-1-a-ame.png'],
  ['액티브: 엔스터타이트', '/images/characters/skill/te-1-ns.png'],
  ['액티브: 인컴패러블', '/images/characters/skill/te-1-inc.png'],

  // 단아
  ['명도: 돌려 베기', '/images/characters/skill/da-1-upb.png'],
  ['명도: 모아 베기', '/images/characters/skill/da-1-moa.png'],
  ['명도: 올려 베기', '/images/characters/skill/da-1-upbb.png'],
  ['명도: 찌르기', '/images/characters/skill/da-1-jj.png'],
  ['명도: 칼집 치기', '/images/characters/skill/da-1-kj.png'],
  ['명도: 하단 베기', '/images/characters/skill/da-h-b.png'],
  ['명도: 회전 베기', '/images/characters/skill/da-1-h-b.png'],
  ['액티브: 기복참', '/images/characters/skill/da-1-a-gi.png'],
  ['영혼 추적', '/images/characters/skill/da-1-soul.png'],
  ['액운 가르기', '/images/characters/skill/da-1-ak.png'],
  ['액티브: 사령곡', '/images/characters/skill/da-1-sa.png'],
  ['액티브: 치병무', '/images/characters/skill/da-1-cb.png'],
  ['흉살 가르기', '/images/characters/skill/da-1-hsa.png'],
  ['액티브: 무신극', '/images/characters/skill/da-1-mos.png'],
  ['액티브: 천도', '/images/characters/skill/da-1-cdo.png'],

  // 레티
  ['스위프트 리코일', '/images/characters/skill/rt-1-swift.png'],
  ['액티브: 뷰티풀 블레이즈', '/images/characters/skill/rt-1-betu.png'],
  ['트루퍼: 스톰 스마이트', '/images/characters/skill/rt-1-stom-s.png'],
  ['트루퍼: 스파이크', '/images/characters/skill/re-1-spi.png'],
  ['트루퍼: 크러쉬 블로우', '/images/characters/skill/re-1-crush.png'],
  ['트루퍼: 트위스트 블로우', '/images/characters/skill/re-1-blo.png'],
  ['트루퍼: 피어스 스트라이크', '/images/characters/skill/re-1-p-st.png'],
  ['스탠딩 플립', '/images/characters/skill/re-1-stand.png'],
  ['크라디 블래스트', '/images/characters/skill/re-1-blast.png'],
  ['액티브: 파이어 크래커', '/images/characters/skill/re-1-fire-c.png'],
  ['크라디 버스트', '/images/characters/skill/re-1-bust.png'],
  ['액티브: 레티 봄바', '/images/characters/skill/re-1-boom.png'],
  ['액티브: 디 데이', '/images/characters/skill/re-1-d-day.png'],

  // 라티야
  ['라이노 피어스', '/images/characters/skill/ra-1-rap.png'],
  ['베어 슬래쉬', '/images/characters/skill/ra-1-bes.png'],
  ['액티브: 라이온 레이지', '/images/characters/skill/ra-1-a-rion.png'],
  ['와일드 피어스', '/images/characters/skill/ra-1-wild.png'],
  ['울프 블로우', '/images/characters/skill/ra-1-wolf.png'],
  ['이글 피어스', '/images/characters/skill/ra-1-eag.png'],
  ['치타 스트라이크', '/images/characters/skill/ra-1-c-stk.png'],
  ['액티브: 스네이크 스핀', '/images/characters/skill/ra-1-s-pin.png'],
  ['라이노 러쉬', '/images/characters/skill/ra-1-ra-rush.png'],
  ['액티브: 쿠자의 빛', '/images/characters/skill/ra-1-kuja.png'],
  ['액티브: 엘리펀트 스매시', '/images/characters/skill/ra-1-e-smash.png'],
  ['액티브: 레오파드 온폴', '/images/characters/skill/ra-1-on-p.png'],

  // 체른
  ['프로히비션: 루치아', '/images/characters/skill/cr-1-lu.png'],
  ['룬 스펙트럼', '/images/characters/skill/cr-1-rune.png'],
  ['액티브: 쿼터 에비던스', '/images/characters/skill/cr-1-qut.png'],
  ['오르비스: 라이도', '/images/characters/skill/cr-1-ra.png'],
  ['오르비스: 케나즈', '/images/characters/skill/cr-1-c-na.png'],
  ['오르비스: 티르', '/images/characters/skill/cr-1-tr.png'],
  ['액티브: 크레센트 노바', '/images/characters/skill/cr-1-c-nova.png'],
  ['액티브: 문 오버섀도우', '/images/characters/skill/cr-1-moon.png'],
  ['액티브: 익시드 페이스', '/images/characters/skill/cr-1-ex.png'],
  ['칼레이도 폴', '/images/characters/skill/cr-1-pool.png'],
  ['액티브: 셀레스티얼', '/images/characters/skill/cr-1-s-ar.png'],
  ['액티브: 아포칼립스', '/images/characters/skill/cr-1-a-po.png'],

  // 아켈
  ['디바이딩 컷', '/images/characters/skill/ac-1-diva.png'],
  ['브루탈 트러스트', '/images/characters/skill/ac-1-b-tr.png'],
  ['스파이럴 슬래쉬', '/images/characters/skill/ac-1-sah.png'],
  ['스플릿 앵클', '/images/characters/skill/ac-1-ang.png'],
  ['액티브: 스트라이크 다운', '/images/characters/skill/ac-a-down.png'],
  ['체이싱 슬래쉬', '/images/characters/skill/ac-1-c-s.png'],
  ['크루얼 엑스큐션', '/images/characters/skill/ac-1-c-ex.png'],
  ['액티브: 피어싱 크러쉬', '/images/characters/skill/ac-1-p-cru.png'],
  ['타지 어썰트', '/images/characters/skill/ac-1-ta-g.png'],
  ['파이트백', '/images/characters/skill/ac-1-fight.png'],
  ['프랜틱 대시', '/images/characters/skill/ac-1-a-dash.png'],
  ['그랜드 스트라이크', '/images/characters/skill/ac-1-gr-s.png'],
  ['퓨리어스 스플리터', '/images/characters/skill/ac-1-p-spli.png'],
  ['액티브: 다운폴', '/images/characters/skill/ac-1-down-po.png'],
  ['액티브: 토탈 디스트럭션', '/images/characters/skill/ac-1-total.png'],

  // 소우
  ['가르기', '/images/characters/skill/so-1-ga.png'],
  ['급소 찌르기', '/images/characters/skill/so-1-jji.png'],
  ['단천', '/images/characters/skill/so-1-d-c.png'],
  ['단천: 난무', '/images/characters/skill/so-1-nan.png'],
  ['액티브: 운무', '/images/characters/skill/so-1-moo.png'],
  ['일문자 베기', '/images/characters/skill/so-1-1.png'],
  ['회전 가르기', '/images/characters/skill/so-1-h-j.png'],
  ['단천: 쾌', '/images/characters/skill/so-1-d-q.png'],
  ['단천: 강', '/images/characters/skill/so-1-d-k.png'],
  ['액티브: 양단', '/images/characters/skill/so-1-1d.png'],
  ['칼날 폭풍', '/images/characters/skill/so-1-pp.png'],
  ['액티브: 흑현', '/images/characters/skill/so-1-hh.png'],
  ['단천: 섬', '/images/characters/skill/so-1-sum.png'],
  ['액티브: 비천락', '/images/characters/skill/so-1-bc.png'],
  ['액티브: 귀천', '/images/characters/skill/so-1-jc.png'],

  // 사냐
  ['리플렉션 스파이럴', '/images/characters/skill/sa-1-r-spa.png'],
  ['스탭 스틸레토', '/images/characters/skill/sa-1-s-stil.png'],
  ['스파이럴 아크', '/images/characters/skill/sa-1-spa-a.png'],
  ['아크로바틱 스파이럴', '/images/characters/skill/sa-1-a-spae.png'],
  ['액티브: 템페스트 킥', '/images/characters/skill/sa-1-temp-k.png'],
  ['체인 스플리터', '/images/characters/skill/sa-1-chain.png'],
  ['페이탈 스팅어', '/images/characters/skill/sa-1-pa-st.png'],
  ['피어싱 스틸레토', '/images/characters/skill/sa-1-pay-st.png'],
  ['스위프트 나이프', '/images/characters/skill/sa-1-swif-k.png'],
  ['플랩핑 카운터', '/images/characters/skill/sa-1-p-cou.png'],
  ['스위프트 러쉬', '/images/characters/skill/sa-1-swi-ru.png'],
  ['액티브: 미드나이츠 터치', '/images/characters/skill/sa-1-mid-tou.png'],
  ['액티브: 베니싱 댄스', '/images/characters/skill/sa-1-b-dan.png'],
  ['트리플 스팅어', '/images/characters/skill/sa-1-tre-s.png'],
  ['액티브: 트위스트 슬래시', '/images/characters/skill/sa-1-tw-s.png'],
  ['액티브: 댄싱 실루엣', '/images/characters/skill/sa-1-dan-s.png'],

  // 네반
  ['게일 슬래쉬', '/images/characters/skill/n-1-gail.png'],
  ['디바인 슬래쉬', '/images/characters/skill/n-1-d-sh.png'],
  ['라이트닝 피어스', '/images/characters/skill/n-1-right.png'],
  ['라피드 파이크', '/images/characters/skill/n-1-r-pa.png'],
  ['라피드 피어스', '/images/characters/skill/n-1-r-pir.png'],
  ['블링크 파이크', '/images/characters/skill/n-1-blink.png'],
  ['시프팅 슬래쉬', '/images/characters/skill/n-1-sah.png'],
  ['어센션 슬래쉬', '/images/characters/skill/n-1-a-ah.png'],
  ['카운터 슬래쉬', '/images/characters/skill/n-1-counter.png'],
  ['액티브: 제미니 스파이럴', '/images/characters/skill/n-1-j-spa.png'],
  ['액티브: 헤븐즈 테일', '/images/characters/skill/n-1-haven.png'],
  ['피어싱 러쉬', '/images/characters/skill/n-1-p-rush.png'],
  ['코멧 임팩트', '/images/characters/skill/n-1-komat.png'],
  ['헤븐즈 임팩트', '/images/characters/skill/n-1-haven-im.png'],
  ['액티브: 게이트 오브 아르세널', '/images/characters/skill/n-1-a-ars.png'],
  ['액티브: 어센던트 임팩트', '/images/characters/skill/n-1-a-imp.png'],
]);
