export const imageMap = new Map<string, string>([
  // 캐릭터
  ["리시타", "/images/characters/lethita.png"],
  ["피오나", "/images/characters/fiona.png"],
  ["이비", "/images/characters/evy.png"],
  ["카록", "/images/characters/kalok.png"],
  ["카이", "/images/characters/kay.png"],
  ["벨라", "/images/characters/vella.png"],
  ["허크", "/images/characters/hurk.png"],
  ["린", "/images/characters/lynn.png"],
  ["아리샤", "/images/characters/arisha.png"],
  ["헤기", "/images/characters/hagie.png"],
  ["델리아", "/images/characters/delia.png"],
  ["미리", "/images/characters/miri.png"],
  ["그림덴", "/images/characters/grimden.png"],
  ["미울", "/images/characters/miul.png"],
  ["벨", "/images/characters/bel.png"],
  ["레서", "/images/characters/lethor.png"],
  ["카엘", "/images/characters/kael.png"],
  ["테사", "/images/characters/tessa.png"],
  ["단아", "/images/characters/danah.png"],
  ["레티", "/images/characters/letty.png"],
  ["라티야", "/images/characters/latiya.png"],
  ["체른", "/images/characters/czern.png"],
  ["아켈", "/images/characters/achel.png"],
  ["소우", "/images/characters/sou.png"],
  ["사냐", "/images/characters/sanyaa.png"],
  ["네반", "/images/characters/neamhain.png"],

  // 시즌 2
  ["마신의 탑", "/images/monster/s2/tower-of-demon-god.png"],
  ["죽음의 그림자", "/images/monster/s2/the-shadow-of-death.png"],
  ["지하 도시", "/images/monster/s2/the-underground-city.png"],
  ["끝없는 질문", "/images/monster/s2/endless-questions.png"],
  ["지배자의 안식처", "/images/monster/s2/the-ruler-s-resting-place.png"],
  ["바다의 악마", "/images/monster/s2/sea-devil.png"],
  ["흘러간 기억", "/images/monster/s2/the-memories-that-flowed-away.png"],
  ["사막의 공주", "/images/monster/s2/desert-princess.png"],
  ["기이한 기계", "/images/monster/s2/strange-machine.png"],
  ["심연에서", "/images/monster/s2/in-the-abyss.png"],
  ["불타는 신전", "/images/monster/s2/burning-temple.png"],
  [
    "저승을 지키는 문지기",
    "/images/monster/s2/the-gatekeeper-of-the-underworld.png",
  ],
  ["황폐한 모르반", "/images/monster/s2/the-desolate-morvan.png"],
  ["죽음의 신", "/images/monster/s2/god-of-death.png"],

  // 시즌 3
  ["영혼의 부재", "/images/monster/s3/absence-of-the-soul.png"],
  ["붉은 낙인", "/images/monster/s3/red-brand.png"],
  ["왜곡된 진실", "/images/monster/s3/distorted-truth.png"],
  ["광휘의 루", "/images/monster/s3/tower-of-glory.png"],
  ["통제", "/images/monster/s3/control.png"],
  ["급습", "/images/monster/s3/raid.png"],
  ["실패와 대가", "/images/monster/s3/failure-and-the-price.png"],
  ["이웨카의 몽마", "/images/monster/s3/iweka-s-dream.png"],
  ["광기의 무덤", "/images/monster/s3/tomb-of-madness.png"],
  ["잊지 않기 위하여", "/images/monster/s3/to-not-forget.png"],
  ["지저의 실험실", "/images/monster/s3/laboratory-of-the-underworld.png"],

  // 시즌 4
  ["어둠의 일족", "/images/monster/s4/dark-clan.png"],
  ["라다톤 대교", "/images/monster/s4/ladaton-bridge.png"],
  ["로체스트 공방전", "/images/monster/s4/rochester-s-battle.png"],
  ["으스름달 아래서", "/images/monster/s4/under-the-crimson-moon.png"],
  ["실낙원의 첨병", "/images/monster/s4/the-vanguard-of-paradise-lost.png"],
  ["왕성 지하감옥", "/images/monster/s4/wangseong-dungeon.png"],
  ["잊혀진 제단", "/images/monster/s4/the-forgotten-altar.png"],
  ["왕성 토파즈 홀", "/images/monster/s4/wangseong-topaz-hall.png"],
  ["죽음의 변증법", "/images/monster/s4/dialectics-of-death.png"],
  ["원한의 암굴", "/images/monster/s4/cave-of-grudge.png"],
  ["위대한 사역", "/images/monster/s4/great-mission.png"],
  ["로흘란의 바람", "/images/monster/s4/rohlan-s-wind.png"],
  [
    "창조와 파괴의 성소",
    "/images/monster/s4/sanctuary-of-creation-and-destruction.png",
  ],
  ["검의 무덤", "/images/monster/s4/tomb-of-the-sword.png"],
  ["시드 별궁", "/images/monster/s4/seed-s-palace.png"],
  ["제단을 지키는 자", "/images/monster/s4/the-guardian-of-the-altar.png"],
  ["그릇된 고해", "/images/monster/s4/false-confession.png"],
  ["탐욕의 연회장", "/images/monster/s4/banquet-hall-of-greed.png"],

  // 스페셜
  ["스페셜 전투", "/images/monster/special/garden-of-tears.png"],
  [
    "스페셜 던전: 인챈트 주머니",
    "/images/items/reward/random-special-dungeon-enchant.png",
  ],

  // 결사대
  ["사념의 바다", "/images/monster/forlornhope/the-sea-of-thoughts.png"],
  ["달의 이면", "/images/monster/forlornhope/the-back-side-of-the-moon.png"],
  ["모루 위의 검", "/images/monster/forlornhope/the-sword-on-the-moru.png"],
  ["생명의 나무", "/images/monster/forlornhope/the-tree-of-life.png"],

  // 결사대 [헬]
  ["사념의 바다 [헬]", "/images/monster/forlornhope/the-sea-of-thoughts.png"],
  [
    "달의 이면 [헬]",
    "/images/monster/forlornhope/the-back-side-of-the-moon.png",
  ],
  [
    "모루 위의 검 [헬]",
    "/images/monster/forlornhope/the-sword-on-the-moru.png",
  ],
  ["생명의 나무 [헬]", "/images/monster/forlornhope/the-tree-of-life.png"],

  // 시공간 왜곡
  ["찬탈자의 성채", "/images/monster/space/soul-usurper-taros.png"],
  ["몰락한 기사의 전당", "/images/monster/space/fallen-eisenritter.png"],
  ["주시자의 신전", "/images/monster/space/temple-of-the-watcher.png"],
  [
    "시공의 상자: 찬탈자의 성채",
    "/images/items/reward/space-time-box-usurpers-fortress.png",
  ],
  [
    "시공의 상자: 몰락한 기사의 전당",
    "/images/items/reward/space-time-box-hall-of-fallen-knights.png",
  ],
  [
    "시공의 상자: 주시자의 신전",
    "/images/items/reward/space-time-box-the-watchers-temple.png",
  ],

  // 재료
  ["스렝의 정수", "/images/items/materials/s4/essence-of-sreng.png"],
  ["스피노스의 정수", "/images/items/materials/s4/essence-of-spinos.png"],
  [
    "와드네의 파편: 무기",
    "/images/items/materials/s4/fragment-of-uaithne-weapon.png",
  ],
  [
    "와드네의 파편: 보조 장비",
    "/images/items/materials/s4/fragment-of-uaithne-weapon-secondary.png",
  ],
  [
    "와드네의 파편: 태양의 비원",
    "/images/items/materials/s4/fragment-of-uaithne-sun.png",
  ],
  [
    "와드네의 파편: 머리 방어구",
    "/images/items/materials/s4/fragment-of-uaithne-head.png",
  ],
  [
    "와드네의 파편: 가슴 방어구",
    "/images/items/materials/s4/fragment-of-uaithne-upper.png",
  ],
  [
    "와드네의 파편: 다리 방어구",
    "/images/items/materials/s4/fragment-of-uaithne-lower.png",
  ],
  [
    "와드네의 파편: 저주의 허리띠",
    "/images/items/materials/s4/fragment-of-uaithne-belt.png",
  ],
  [
    "와드네 승급석: 무기",
    "/images/items/materials/s4/uaithne-promotion-stone-weapon.png",
  ],
  [
    "와드네 승급석: 머리 방어구",
    "/images/items/materials/s4/uaithne-promotion-stone-head.png",
  ],
  [
    "와드네 승급석: 가슴 방어구",
    "/images/items/materials/s4/uaithne-promotion-stone-upper.png",
  ],
  [
    "와드네 승급석: 다리 방어구",
    "/images/items/materials/s4/uaithne-promotion-stone-lower.png",
  ],
  [
    "단단한 와드네의 결정",
    "/images/items/materials/s4/solid-uaithne-crystal.png",
  ],
  [
    "매끈한 와드네의 결정",
    "/images/items/materials/s4/smooth-uaithne-crystal.png",
  ],
  [
    "예리한 와드네의 결정",
    "/images/items/materials/s4/incisive-uaithne-crystal.png",
  ],
  [
    "가벼운 와드네의 결정",
    "/images/items/materials/s4/light-uaithne-crystal.png",
  ],
  [
    "안정된 와드네의 결정",
    "/images/items/materials/s4/stable-uaithne-crystal.png",
  ],
  [
    "견고한 와드네의 결정",
    "/images/items/materials/s4/noble-uaithne-crystal.png",
  ],
  ["미지의 조각 1단계", "/images/items/materials/s4/shard-unknown-1.png"],
  ["미지의 조각 2단계", "/images/items/materials/s4/shard-unknown-2.png"],
  ["미지의 조각 3단계", "/images/items/materials/s4/shard-unknown-3.png"],
  ["투쟁의 조각 1단계", "/images/items/materials/s4/shard_struggle-1.png"],
  ["투쟁의 조각 2단계", "/images/items/materials/s4/shard_struggle-2.png"],
  ["투쟁의 조각 3단계", "/images/items/materials/s4/shard_struggle-3.png"],
  ["미지의 결정", "/images/items/materials/s4/unknown-uaithne-crystal.png"],
  ["투쟁의 결정", "/images/items/materials/s4/fight-uaithne-crystal.png"],
  ["추출의 룬", "/images/items/materials/s4/extraction_rune.png"],
  [
    "고급 강화의 비약",
    "/images/items/materials/s4/elixir-of-advanced-strengthening.png",
  ],
  ["와드네의 결정", "/images/items/materials/s4/uaithne-crystal.png"],
  ["고르바스의 정수", "/images/items/materials/s4/essence-of-gorbas.png"],
  ["강화의 룬", "/images/items/materials/s4/rune-of-strengthening.png"],
  [
    "프리미엄 강화의 룬",
    "/images/items/materials/s4/preminu-rune-of-strengthening.png",
  ],
  [
    "+ 프리미엄 강화의 룬",
    "/images/items/materials/s4/preminu-rune-of-strengthening-plus.png",
  ],
  [
    "프리미엄 방어구 강화의 룬",
    "/images/items/materials/s4/preminu-rune-of-strengthening-armor.png",
  ],
  ["자르딘 강철", "/images/items/materials/s4/jardin-steel.png"],
  ["게브네의 강화석", "/images/items/materials/s4/gevne.png"],
  ["+ 게브네의 강화석", "/images/items/materials/s4/gevne-plus.png"],
  ["전승의 힘: 파편", "/images/items/materials/s4/j-limit-stone.png"],
  ["봉인의 힘: 파편", "/images/items/materials/s4/r-limit-stone.png"],

  [
    "오르나 무기 강화 촉진제",
    "/images/items/materials/s4/orna-accelerator-weapon.png",
  ],
  [
    "오르나 방어구 강화 촉진제: 가슴, 다리",
    "/images/items/materials/s4/orna-accelerator-upper-lower.png",
  ],
  [
    "오르나 방어구 강화 촉진제: 머리, 손, 발",
    "/images/items/materials/s4/orna-accelerator-head-hand-leg.png",
  ],
  ["신비의 힘: 파편", "/images/items/materials/s4/mystical-power-fragment.png"],
  ["불안정한 강화의 룬", "/images/items/materials/s4/rune_unstable.png"],

  ["힘이 주입된 뉴에라의 옷감", "/images/items/materials/s4/power-cloth.png"],
  ["힘이 주입된 뉴에라의 오브", "/images/items/materials/s4/power-orb.png"],
  ["힘이 주입된 뉴에라의 광석", "/images/items/materials/s4/power-ore.png"],
  ["힘이 주입된 뉴에라의 가죽", "/images/items/materials/s4/power-leather.png"],
  ["와드네의 흔적", "/images/items/materials/s4/uaithne-sign.png"],
  ["다마스쿠스 강철", "/images/items/materials/s4/damascus.png"],
  ["뉴에라의 오브", "/images/items/materials/s4/n-orb.png"],
  ["뉴에라의 광석", "/images/items/materials/s4/n-ore.png"],
  ["뉴에라의 가죽", "/images/items/materials/s4/n-leather.png"],
  ["뉴에라의 옷감", "/images/items/materials/s4/n-cloth.png"],

  ["오르나의 봉인된 힘", "/images/items/materials/s4/combine-orna.png"],
  [
    "오르나의 봉인된 힘: 머리 방어구",
    "/images/items/materials/s4/combine-orna-head.png",
  ],
  [
    "오르나의 봉인된 힘: 가슴 방어구",
    "/images/items/materials/s4/combine-orna-upper.png",
  ],
  [
    "오르나의 봉인된 힘: 다리 방어구",
    "/images/items/materials/s4/combine-orna-lower.png",
  ],
  [
    "오르나의 봉인된 힘: 손 방어구",
    "/images/items/materials/s4/combine-orna-hand.png",
  ],
  [
    "오르나의 봉인된 힘: 발 방어구",
    "/images/items/materials/s4/combine-orna-leg.png",
  ],
  [
    "오르나의 봉인된 힘: 무기",
    "/images/items/materials/s4/combine-orna-weapon.png",
  ],
  ["오르나의 봉인된 힘", "/images/items/materials/s4/combine-orna-b.png"],
  ["골드", "/images/items/materials/basic/gold.png"],
  ["고급 철광석", "/images/items/materials/basic/high-grade-iron-ore.png"],
  ["마나 더스트", "/images/items/materials/basic/mana-dust.png"],
  ["마나 리포머", "/images/items/materials/basic/mana-reformer.png"],
  ["정령의 흔적", "/images/items/materials/basic/trace-of-the-spirit.png"],
  ["불의 흔적", "/images/items/materials/basic/fire-of-the-spirit.png"],
  ["냉기의 흔적", "/images/items/materials/basic/cool-of-the-spirit.png"],
  ["생명의 흔적", "/images/items/materials/basic/life-of-the-spirit.png"],
  ["대지의 흔적", "/images/items/materials/basic/st-of-the-spirit.png"],
  ["마법 가루", "/images/items/materials/basic/magic-powder.png"],
  ["최고급 강화석", "/images/items/materials/basic/best-k-stone.png"],
  ["생명의 에르그 결정", "/images/items/materials/basic/life-erg-crystal.png"],
  ["빈 병", "/images/items/materials/basic/empties.png"],
  ["오브", "/images/items/materials/basic/orb.png"],
  ["상급 생명력 포션", "/images/items/materials/basic/life-p-1.png"],
  ["고급 생명력 포션", "/images/items/materials/basic/life-p-2.png"],
  ["최고급 생명력 포션", "/images/items/materials/basic/life-p-3.png"],

  ["단단한 계승 원석", "/images/items/materials/s4/solid-115.png"],
  ["매끈한 계승 원석", "/images/items/materials/s4/smarmy-115.png"],
  ["예리한 계승 원석", "/images/items/materials/s4/incisive-115.png"],
  ["안정된 계승 원석", "/images/items/materials/s4/stable-115.png"],
  ["가벼운 계승 원석", "/images/items/materials/s4/light-115.png"],
  ["오롯한 계승 원석", "/images/items/materials/s4/all-115.png"],
  ["낙원의 강화석", "/images/items/materials/s4/nk.png"],
  ["마법력 엘릭서", "/images/items/materials/s4/ml.png"],
  ["생명의 마법력 엘릭서", "/images/items/materials/s4/sml.png"],
  ["축복의 마법력 엘릭서", "/images/items/materials/s4/csml.png"],
  ["축복받은 마법 가루", "/images/items/materials/s4/cmk.png"],
  ["뉴에라의 강화석", "/images/items/materials/s4/new-era-stone.png"],

  // 장비
  // 105 액세서리
  ["황혼의 수호", "/images/items/equipment/105/finger-105-01.png"],
  ["황혼의 칼날", "/images/items/equipment/105/finger-105-02.png"],
  ["묵언의 결의", "/images/items/equipment/105/earring-105.png"],
  ["정신의 허리띠", "/images/items/equipment/105/belt-105.png"],

  // 105 밀레시안 방어구
  ["밀레시안 메일", "/images/items/equipment/105/m-upper.png"],
  ["밀레시안 그리브즈", "/images/items/equipment/105/m-lower.png"],
  ["밀레시안 헬름", "/images/items/equipment/105/m-head.png"],
  ["밀레시안 건틀릿", "/images/items/equipment/105/m-hand.png"],
  ["밀레시안 부츠", "/images/items/equipment/105/m-leg.png"],

  ["밀레시안의 서", "/images/items/equipment/105/m-book-105.png"],

  // 105 밀레시안 무기
  ["밀레시안 듀얼소드", "/images/items/equipment/105/dualsword-105.png"],
  ["밀레시안 듀얼스피어", "/images/items/equipment/105/dualspear-105.png"],
  ["밀레시안 바스타드소드", "/images/items/equipment/105/bastardsword-105.png"],
  ["밀레시안 배틀액스", "/images/items/equipment/105/battleaxe-105.png"],
  ["밀레시안 블뤼테", "/images/items/equipment/105/blute-105.png"],
  ["밀레시안 하스타", "/images/items/equipment/105/hasta-105.png"],
  ["밀레시안 배틀글레이브", "/images/items/equipment/105/battleglaive-105.png"],
  ["밀레시안 블래스터", "/images/items/equipment/105/blaster-105.png"],
  ["밀레시안 보우", "/images/items/equipment/105/bow-105.png"],
  ["밀레시안 드레이커", "/images/items/equipment/105/draker-105.png"],
  ["밀레시안 크레스트", "/images/items/equipment/105/crest-105.png"],
  ["밀레시안 크로스건", "/images/items/equipment/105/crossgun-105.png"],
  ["밀레시안 듀얼블레이드", "/images/items/equipment/105/dualblade-105.png"],
  ["밀레시안 듀얼나이프", "/images/items/equipment/105/dualknife-105.png"],
  ["밀레시안 그레이트소드", "/images/items/equipment/105/greatsword-105.png"],
  ["밀레시안 롱해머", "/images/items/equipment/105/longhammer-105.png"],
  ["밀레시안 롱소드", "/images/items/equipment/105/longsword-105.png"],
  ["밀레시안 롱블레이드", "/images/items/equipment/105/longblade-105.png"],
  ["밀레시안 헤비캐넌", "/images/items/equipment/105/heavycannon-105.png"],
  ["밀레시안 윕", "/images/items/equipment/105/whip-105.png"],
  ["밀레시안 랜스", "/images/items/equipment/105/lance-105.png"],
  ["밀레시안 레이피어", "/images/items/equipment/105/rapier-105.png"],
  ["밀레시안 소울블레이드", "/images/items/equipment/105/soulblade-105.png"],
  ["밀레시안 마나리볼버", "/images/items/equipment/105/manarevolver-105.png"],
  ["밀레시안 스태프", "/images/items/equipment/105/staff-105.png"],
  ["밀레시안 팬텀대거", "/images/items/equipment/105/phantomdagger-105.png"],
  ["밀레시안 테이드", "/images/items/equipment/105/teide-105.png"],
  ["밀레시안 소드스피어", "/images/items/equipment/105/swordspear-105.png"],
  ["밀레시안 배틀필러", "/images/items/equipment/105/battlepillar-105.png"],
  ["밀레시안 카타마르", "/images/items/equipment/105/catamadhar-105.png"],
  ["밀레시안 사이드", "/images/items/equipment/105/scythe-105.png"],
  ["밀레시안 홀리파이크", "/images/items/equipment/105/pike-105.png"],
  ["밀레시안 오르비스", "/images/items/equipment/105/orbis-105.png"],
  [
    "밀레시안 오리엔탈블레이드",
    "/images/items/equipment/105/orientalblade-105.png",
  ],

  // 110 아르드리 방어구
  ["아르드리 무기", "/images/items/equipment/110/a-weapon.png"],
  ["아르드리 메일", "/images/items/equipment/110/a-upper.png"],
  ["아르드리 그리브즈", "/images/items/equipment/110/a-lower.png"],
  ["아르드리 헬름", "/images/items/equipment/110/a-head.png"],
  ["아르드리 건틀릿", "/images/items/equipment/110/a-hand.png"],
  ["아르드리 부츠", "/images/items/equipment/110/a-leg.png"],
  ["아르드리의 서", "/images/items/equipment/110/ar-book.png"],

  // 110 아르드리 무기
  ["아르드리 듀얼소드", "/images/items/equipment/110/dualsword-110.png"],
  ["아르드리 듀얼스피어", "/images/items/equipment/110/dualspear-110.png"],
  ["아르드리 바스타드소드", "/images/items/equipment/110/bastardsword-110.png"],
  ["아르드리 배틀액스", "/images/items/equipment/110/battleaxe-110.png"],
  ["아르드리 블뤼테", "/images/items/equipment/110/blute-110.png"],
  ["아르드리 하스타", "/images/items/equipment/110/hasta-110.png"],
  ["아르드리 배틀글레이브", "/images/items/equipment/110/battleglaive-110.png"],
  ["아르드리 블래스터", "/images/items/equipment/110/blaster-110.png"],
  ["아르드리 보우", "/images/items/equipment/110/bow-110.png"],
  ["아르드리 드레이커", "/images/items/equipment/110/draker-110.png"],
  ["아르드리 크레스트", "/images/items/equipment/110/crest-110.png"],
  ["아르드리 크로스건", "/images/items/equipment/110/crossgun-110.png"],
  ["아르드리 듀얼블레이드", "/images/items/equipment/110/dualblade-110.png"],
  ["아르드리 듀얼나이프", "/images/items/equipment/110/dualknife-110.png"],
  ["아르드리 그레이트소드", "/images/items/equipment/110/greatsword-110.png"],
  ["아르드리 롱해머", "/images/items/equipment/110/longhammer-110.png"],
  ["아르드리 롱소드", "/images/items/equipment/110/longsword-110.png"],
  ["아르드리 롱블레이드", "/images/items/equipment/110/longblade-110.png"],
  ["아르드리 헤비캐넌", "/images/items/equipment/110/heavycannon-110.png"],
  ["아르드리 윕", "/images/items/equipment/110/whip-110.png"],
  ["아르드리 랜스", "/images/items/equipment/110/lance-110.png"],
  ["아르드리 레이피어", "/images/items/equipment/110/rapier-110.png"],
  ["아르드리 소울블레이드", "/images/items/equipment/110/soulblade-110.png"],
  ["아르드리 마나리볼버", "/images/items/equipment/110/manarevolver-110.png"],
  ["아르드리 스태프", "/images/items/equipment/110/staff-110.png"],
  ["아르드리 팬텀대거", "/images/items/equipment/110/phantomdagger-110.png"],
  ["아르드리 테이드", "/images/items/equipment/110/teide-110.png"],
  ["아르드리 소드스피어", "/images/items/equipment/110/swordspear-110.png"],
  ["아르드리 배틀필러", "/images/items/equipment/110/battlepillar-110.png"],
  ["아르드리 카타마르", "/images/items/equipment/110/catamadhar-110.png"],
  ["아르드리 사이드", "/images/items/equipment/110/scythe-110.png"],
  ["아르드리 홀리파이크", "/images/items/equipment/110/pike-110.png"],
  ["아르드리 오르비스", "/images/items/equipment/110/orbis-110.png"],
  [
    "아르드리 오리엔탈블레이드",
    "/images/items/equipment/110/orientalblade-110.png",
  ],

  // 115 오르나 방어구
  ["오르나 무기", "/images/items/equipment/115/o-weapon.png"],
  ["오르나 메일", "/images/items/equipment/115/o-upper.png"],
  ["오르나 그리브즈", "/images/items/equipment/115/o-lower.png"],
  ["오르나 헬름", "/images/items/equipment/115/o-head.png"],
  ["오르나 건틀릿", "/images/items/equipment/115/o-hand.png"],
  ["오르나 부츠", "/images/items/equipment/115/o-leg.png"],

  ["+15 오르나 무기", "/images/items/equipment/115/o-weapon.png"],
  ["+15 오르나 메일", "/images/items/equipment/115/o-upper.png"],
  ["+15 오르나 그리브즈", "/images/items/equipment/115/o-lower.png"],
  ["+15 오르나 헬름", "/images/items/equipment/115/o-head.png"],
  ["+15 오르나 건틀릿", "/images/items/equipment/115/o-hand.png"],
  ["+15 오르나 부츠", "/images/items/equipment/115/o-leg.png"],

  ["오르나의 서", "/images/items/equipment/115/o-book-115.png"],

  // 115 오르나 무기
  ["오르나 듀얼소드", "/images/items/equipment/115/dualsword-115.png"],
  ["오르나 듀얼스피어", "/images/items/equipment/115/dualspear-115.png"],
  ["오르나 바스타드소드", "/images/items/equipment/115/bastardsword-115.png"],
  ["오르나 배틀액스", "/images/items/equipment/115/battleaxe-115.png"],
  ["오르나 블뤼테", "/images/items/equipment/115/blute-115.png"],
  ["오르나 하스타", "/images/items/equipment/115/hasta-115.png"],
  ["오르나 배틀글레이브", "/images/items/equipment/115/battleglaive-115.png"],
  ["오르나 블래스터", "/images/items/equipment/115/blaster-115.png"],
  ["오르나 보우", "/images/items/equipment/115/bow-115.png"],
  ["오르나 드레이커", "/images/items/equipment/115/draker-115.png"],
  ["오르나 크레스트", "/images/items/equipment/115/crest-115.png"],
  ["오르나 크로스건", "/images/items/equipment/115/crossgun-115.png"],
  ["오르나 듀얼블레이드", "/images/items/equipment/115/dualblade-115.png"],
  ["오르나 듀얼나이프", "/images/items/equipment/115/dualknife-115.png"],
  ["오르나 그레이트소드", "/images/items/equipment/115/greatsword-115.png"],
  ["오르나 롱해머", "/images/items/equipment/115/longhammer-115.png"],
  ["오르나 롱소드", "/images/items/equipment/115/longsword-115.png"],
  ["오르나 롱블레이드", "/images/items/equipment/115/longblade-115.png"],
  ["오르나 헤비캐넌", "/images/items/equipment/115/heavycannon-115.png"],
  ["오르나 윕", "/images/items/equipment/115/whip-115.png"],
  ["오르나 랜스", "/images/items/equipment/115/lance-115.png"],
  ["오르나 레이피어", "/images/items/equipment/115/rapier-115.png"],
  ["오르나 소울블레이드", "/images/items/equipment/115/soulblade-115.png"],
  ["오르나 마나리볼버", "/images/items/equipment/115/manarevolver-115.png"],
  ["오르나 스태프", "/images/items/equipment/115/staff-115.png"],
  ["오르나 팬텀대거", "/images/items/equipment/115/phantomdagger-115.png"],
  ["오르나 테이드", "/images/items/equipment/115/teide-115.png"],
  ["오르나 소드스피어", "/images/items/equipment/115/swordspear-115.png"],
  ["오르나 배틀필러", "/images/items/equipment/115/battlepillar-115.png"],
  ["오르나 카타마르", "/images/items/equipment/115/catamadhar-115.png"],
  ["오르나 사이드", "/images/items/equipment/115/scythe-115.png"],
  ["오르나 홀리파이크", "/images/items/equipment/115/pike-115.png"],
  ["오르나 오르비스", "/images/items/equipment/115/orbis-115.png"],
  [
    "오르나 오리엔탈블레이드",
    "/images/items/equipment/115/orientalblade-115.png",
  ],

  //
  ["전승의 서", "/images/items/equipment/j-book.png"],
  // 120 와드네 방어구
  ["와드네 스몰실드", "/images/items/equipment/120/s-shild.png"],
  ["와드네 라지실드", "/images/items/equipment/120/r-shild.png"],
  ["와드네 그랜드타지", "/images/items/equipment/120/g-shild.png"],
  ["와드네의 서", "/images/items/equipment/120/u-book.png"],
  ["와드네 캐스틀릿", "/images/items/equipment/120/cas.png"],

  ["와드네 무기", "/images/items/equipment/120/u-weapon.png"],
  ["초급 와드네 무기", "/images/items/equipment/120/u-weapon.png"],
  ["중급 와드네 무기", "/images/items/equipment/120/u-weapon.png"],
  ["고급 와드네 무기", "/images/items/equipment/120/u-weapon.png"],

  ["와드네 헬름", "/images/items/equipment/120/uaithne-head.png"],
  ["초급 와드네 헬름", "/images/items/equipment/120/uaithne-head.png"],
  ["중급 와드네 헬름", "/images/items/equipment/120/uaithne-head.png"],
  ["고급 와드네 헬름", "/images/items/equipment/120/uaithne-head.png"],
  ["레어 와드네 헬름", "/images/items/equipment/120/uaithne-head.png"],
  ["전설 와드네 헬름", "/images/items/equipment/120/uaithne-head.png"],

  ["와드네 메일", "/images/items/equipment/120/uaithne-upper.png"],
  ["초급 와드네 메일", "/images/items/equipment/120/uaithne-upper.png"],
  ["중급 와드네 메일", "/images/items/equipment/120/uaithne-upper.png"],
  ["고급 와드네 메일", "/images/items/equipment/120/uaithne-upper.png"],
  ["레어 와드네 메일", "/images/items/equipment/120/uaithne-upper.png"],
  ["전설 와드네 메일", "/images/items/equipment/120/uaithne-upper.png"],

  ["와드네 그리브즈", "/images/items/equipment/120/uaithne-lower.png"],
  ["초급 와드네 그리브즈", "/images/items/equipment/120/uaithne-lower.png"],
  ["중급 와드네 그리브즈", "/images/items/equipment/120/uaithne-lower.png"],
  ["고급 와드네 그리브즈", "/images/items/equipment/120/uaithne-lower.png"],
  ["레어 와드네 그리브즈", "/images/items/equipment/120/uaithne-lower.png"],
  ["전설 와드네 그리브즈", "/images/items/equipment/120/uaithne-lower.png"],

  // 120 와드네 무기
  ["와드네 듀얼소드", "/images/items/equipment/120/dualsword-120.png"],
  ["와드네 듀얼스피어", "/images/items/equipment/120/dualspear-120.png"],
  ["와드네 바스타드소드", "/images/items/equipment/120/bastardsword-120.png"],
  ["와드네 배틀액스", "/images/items/equipment/120/battleaxe-120.png"],
  ["와드네 블뤼테", "/images/items/equipment/120/blute-120.png"],
  ["와드네 하스타", "/images/items/equipment/120/hasta-120.png"],
  ["와드네 배틀글레이브", "/images/items/equipment/120/battleglaive-120.png"],
  ["와드네 블래스터", "/images/items/equipment/120/blaster-120.png"],
  ["와드네 보우", "/images/items/equipment/120/bow-120.png"],
  ["와드네 드레이커", "/images/items/equipment/120/draker-120.png"],
  ["와드네 크레스트", "/images/items/equipment/120/crest-120.png"],
  ["와드네 크로스건", "/images/items/equipment/120/crossgun-120.png"],
  ["와드네 듀얼블레이드", "/images/items/equipment/120/dualblade-120.png"],
  ["와드네 듀얼나이프", "/images/items/equipment/120/dualknife-120.png"],
  ["와드네 그레이트소드", "/images/items/equipment/120/greatsword-120.png"],
  ["와드네 롱해머", "/images/items/equipment/120/longhammer-120.png"],
  ["와드네 롱소드", "/images/items/equipment/120/longsword-120.png"],
  ["와드네 롱블레이드", "/images/items/equipment/120/longblade-120.png"],
  ["와드네 헤비캐넌", "/images/items/equipment/120/heavycannon-120.png"],
  ["와드네 윕", "/images/items/equipment/120/whip-120.png"],
  ["와드네 랜스", "/images/items/equipment/120/lance-120.png"],
  ["와드네 레이피어", "/images/items/equipment/120/rapier-120.png"],
  ["와드네 소울블레이드", "/images/items/equipment/120/soulblade-120.png"],
  ["와드네 마나리볼버", "/images/items/equipment/120/manarevolver-120.png"],
  ["와드네 스태프", "/images/items/equipment/120/staff-120.png"],
  ["와드네 팬텀대거", "/images/items/equipment/120/phantomdagger-120.png"],
  ["와드네 테이드", "/images/items/equipment/120/teide-120.png"],
  ["와드네 소드스피어", "/images/items/equipment/120/swordspear-120.png"],
  ["와드네 배틀필러", "/images/items/equipment/120/battlepillar-120.png"],
  ["와드네 카타마르", "/images/items/equipment/120/catamadhar-120.png"],
  ["와드네 사이드", "/images/items/equipment/120/scythe-120.png"],
  ["와드네 홀리파이크", "/images/items/equipment/120/pike-120.png"],
  ["와드네 오르비스", "/images/items/equipment/120/orbis-120.png"],
  [
    "와드네 오리엔탈블레이드",
    "/images/items/equipment/120/orientalblade-120.png",
  ],

  // 로드
  ["찬탈자의 녹슨 로드", "/images/items/equipment/taros-01.png"],
  ["찬탈자의 로드", "/images/items/equipment/taros-02.png"],
  ["찬탈자의 빛나는 로드", "/images/items/equipment/taros-03.png"],
  ["찬탈자의 완전한 로드", "/images/items/equipment/taros-04.png"],

  ["몰락자의 녹슨 로드", "/images/items/equipment/fallen-01.png"],
  ["몰락자의 로드", "/images/items/equipment/fallen-02.png"],
  ["몰락자의 빛나는 로드", "/images/items/equipment/fallen-03.png"],
  ["몰락자의 완전한 로드", "/images/items/equipment/fallen-04.png"],

  // 팔찌
  ["미지의 가죽 팔찌 (증정)", "/images/items/equipment/bracelet-leather.png"],
  ["미지의 가죽 팔찌", "/images/items/equipment/bracelet-leather.png"],

  ["미지의 구리 팔찌 (증정)", "/images/items/equipment/bracelet-bronze.png"],
  ["미지의 구리 팔찌", "/images/items/equipment/bracelet-bronze.png"],

  ["미지의 순은 팔찌 (증정)", "/images/items/equipment/bracelet-cilver.png"],
  ["미지의 순은 팔찌", "/images/items/equipment/bracelet-cilver.png"],

  ["미지의 황금 팔찌 (증정)", "/images/items/equipment/bracelet-gold.png"],
  ["미지의 황금 팔찌", "/images/items/equipment/bracelet-gold.png"],

  // 브로치
  ["고양이 브로치", "/images/items/equipment/charm-01.png"],
  ["하얀 고양이 브로치", "/images/items/equipment/charm-02.png"],
  ["하얀 고양이 브로치 (30일)", "/images/items/equipment/charm-02.png"],
  ["파란 고양이 브로치", "/images/items/equipment/charm-03.png"],
  ["붉은 달 브로치", "/images/items/equipment/charm-04.png"],
  ["순백 깃털 브로치", "/images/items/equipment/charm-05.png"],
  ["잿빛 황혼 브로치", "/images/items/equipment/charm-06.png"],

  // 목걸이
  ["고양이 목걸이", "/images/items/equipment/necklace-01.png"],
  ["하얀 고양이 목걸이", "/images/items/equipment/necklace-02.png"],
  ["하얀 고양이 목걸이 (30일)", "/images/items/equipment/necklace-02.png"],
  ["파란 고양이 목걸이", "/images/items/equipment/necklace-03.png"],
  ["붉은 고양이 목걸이", "/images/items/equipment/necklace-04.png"],
  ["빛나는 고양이 목걸이", "/images/items/equipment/necklace-05.png"],

  // 허리띠
  ["어둠의 허리띠", "/images/items/equipment/belt-110.png"],
  ["투쟁의 허리띠", "/images/items/equipment/belt-115.png"],
  ["저주의 허리띠", "/images/items/equipment/belt-120.png"],

  // 귀걸이
  ["차원의 귀걸이", "/images/items/equipment/earring-110.png"],
  ["성소의 귀걸이", "/images/items/equipment/earring-115.png"],
  ["태양의 비원", "/images/items/equipment/sun_earring.png"],

  // 반지
  ["균열의 분노", "/images/items/equipment/ring-110-01.png"],
  ["균열의 공포", "/images/items/equipment/ring-110-02.png"],
  ["어둠 속 그림자", "/images/items/equipment/ring-115-01.png"],
  ["어둠 속 달빛", "/images/items/equipment/ring-115-02.png"],

  // 아티팩트
  ["서큐버스의 송곳니", "/images/items/equipment/succubus-00.png"],
  ["상급 서큐버스의 송곳니", "/images/items/equipment/succubus-01.png"],
  [
    "주시자의 녹슨 서큐버스의 송곳니",
    "/images/items/equipment/succubus-02.png",
  ],
  ["주시자의 서큐버스의 송곳니", "/images/items/equipment/succubus-03.png"],
  [
    "주시자의 빛나는 서큐버스의 송곳니",
    "/images/items/equipment/succubus-04.png",
  ],
  [
    "주시자의 완전한 서큐버스의 송곳니",
    "/images/items/equipment/succubus-05.png",
  ],

  ["의문의 고양이 조각상", "/images/items/equipment/mysterious-00.png"],
  ["상급 의문의 고양이 조각상", "/images/items/equipment/mysterious-01.png"],
  [
    "주시자의 녹슨 의문의 고양이 조각상",
    "/images/items/equipment/mysterious-02.png",
  ],
  [
    "주시자의 의문의 고양이 조각상",
    "/images/items/equipment/mysterious-03.png",
  ],
  [
    "주시자의 빛나는 의문의 고양이 조각상",
    "/images/items/equipment/mysterious-04.png",
  ],
  [
    "주시자의 완전한 의문의 고양이 조각상",
    "/images/items/equipment/mysterious-05.png",
  ],

  ["상급 전쟁 여신의 조각상", "/images/items/equipment/war-goddess-01.png"],
  [
    "주시자의 녹슨 전쟁 여신의 조각상",
    "/images/items/equipment/war-goddess-02.png",
  ],
  ["주시자의 전쟁 여신의 조각상", "/images/items/equipment/war-goddess-03.png"],
  [
    "주시자의 빛나는 전쟁 여신의 조각상",
    "/images/items/equipment/war-goddess-04.png",
  ],
  [
    "주시자의 완전한 전쟁 여신의 조각상",
    "/images/items/equipment/war-goddess-05.png",
  ],

  ["웨어울프의 앞발", "/images/items/equipment/werewolf-00.png"],
  ["웨어울프의 앞발 (30일)", "/images/items/equipment/werewolf-00.png"],
  ["상급 웨어울프의 앞발", "/images/items/equipment/werewolf-01.png"],
  ["주시자의 녹슨 웨어울프의 앞발", "/images/items/equipment/werewolf-02.png"],
  ["주시자의 웨어울프의 앞발", "/images/items/equipment/werewolf-03.png"],
  [
    "주시자의 빛나는 웨어울프의 앞발",
    "/images/items/equipment/werewolf-04.png",
  ],
  [
    "주시자의 완전한 웨어울프의 앞발",
    "/images/items/equipment/werewolf-05.png",
  ],
]);
