export const keyword = {
  statName: {
    str: "힘",
    agi: "민첩",
    int: "지능",
    wil: "의지",
    luk: "운",
    max_hp: "최대 생명력",
    max_sta: "",
    balance: "밸런스",
    att_speed: "공격 속도",
    att_surplus: "",
    att: "공격력",
    def: "방어력",
    critical: "크리티컬",
    critical_damage: "크리티컬 대미지",
    critical_resist: "크리티컬 저항",
    max_stamina: "최대 스태미나",
  },
  slot: {
    righthand: "Right Hand",
    leftthand: "Left Hand",
    head: "Head",
    upper: "Upper",
    lower: "Lower",
    hand: "Hand",
    leg: "Leg",
    materials: "Materials",
    accessories: "Accessories",
  },
  itemName: {
    ardri: "아르드리",
    orna: "오르나",
    uaithne: "와드네",
  },
  upgreadeType: {
    infusion: "infusion",
    prefix: "prefix",
    suffix: "suffix",
  },
  project: {
    name: "망스비",
    url: "https://heroes-dev.com/",
  },
};
